In [33]:
from codes.python import load_DF_beats as DF
import numpy as np
from codes.python import metric
from codes. python import post_process_features_ex as post_features

from sklearn.metrics import classification_report, confusion_matrix 
ls = []
ls.extend(['N', 'L', 'R'])                    # N
#ls.extend(['A', 'a', 'J', 'S', 'e', 'j'])     # SVEB 
ls.extend(['V', 'E'])                         # VEB
ls.extend(['F'])
ls2.extend([ 'P', '/', 'f', 'u'])
patient_l_1 = [101]
#patient_l_2 = [100]
patient_ls_1 = [101,106,108,109,112,114,115,116,118,119,122,124,201,203,205,207,208,209,215,220,223,230]
patient_ls_2 = [100,103,105,111,113,117,121,123,200,202,210,212,213,214,219,221,222,228,231,232,233,234]


ls2 = []
ls2.extend(["['N']","['L']", "['R']"])                    # N
ls2.extend(["['A']", "['a']", "['J']", "['S']",  "['e']", "['j']"])     # SVEB 
ls2.extend(["['V']", "['E']"])                         # VEB
ls2.extend(["['F']"])
#ls.extend([ "['P']","[ '/']"," ['f']", "['u']"])


In [27]:
np_clinic_1_old, np_clinic_2_old,np_non_var_1_old, np_non_var_2_old, np_class_ID_1_old, np_class_ID_2_old, patients_ls_1, patients_ls_2, DB1, DB2, DB1_V1, DB2_V1, DB1_non_cli, DB2_non_cli, DB1_dwt, DB2_dwt, DB1_dwt_V1, DB2_dwt_V1 = DF.get_all_dataframe(patient_l_1=patient_ls_1,patient_l_2=patient_ls_2 , ls=ls, ls2=ls2 )

In [16]:
np_clinic_1, np_clinic_2,np_non_var_1, np_non_var_2, np_class_ID_1, np_class_ID_2 = DF.get_all_dataframe_patient_specific(200,patient_l_1=patient_ls_1,patient_l_2=patient_ls_2 , ls=ls, ls2=ls2 )

done norm
row 0 done
done norm
row 1 done


In [30]:
np_class_ID_1 = [int(i) for i in np_class_ID_1]
np_class_ID_2 = [int(i) for i in np_class_ID_2]

X_train = np_clinic_1
X_test = np_clinic_2
y_train = np.asarray(np_class_ID_1)
y_test = np.asarray(np_class_ID_2)
input_size=X_train.shape[1]

NameError: name 'np_class_ID_1' is not defined

In [28]:
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np_class_ID_1_old
y_test = np_class_ID_2_old
input_size=X_train.shape[1]

In [44]:
np_class_ID_1 = [int(i) for i in np_class_ID_1]
np_class_ID_2 = [int(i) for i in np_class_ID_2]


X_train = np_non_var_1
X_test = np_non_var_2
y_train = np.asarray(np_class_ID_1)
y_test = np.asarray(np_class_ID_2)
input_size=X_train.shape[1]

In [36]:
X_train = np_non_var_1_old
X_test = np_non_var_2_old
y_train = np_class_ID_1_old
y_test = np_class_ID_2_old
input_size=X_train.shape[1]

In [12]:
norm_var_1_clinic = post_features.normalised_values_multiples(np_clinic_1)
norm_var_2_clinic = post_features.normalised_values_multiples(np_clinic_2)
np_class_ID_1 = [int(i) for i in np_class_ID_1]
np_class_ID_2 = [int(i) for i in np_class_ID_2]
np_clinic_new_1 = np.hstack((np_clinic_1, norm_var_1_clinic))
np_clinic_new_2 = np.hstack((np_clinic_2, norm_var_2_clinic))

X_train = np_clinic_new_1
X_test =np_clinic_new_2
y_train = np.asarray(np_class_ID_1)
y_test = np.asarray(np_class_ID_2)
input_size=X_train.shape[1]

NameError: name 'np_clinic_1' is not defined

In [11]:
from sklearn.ensemble import IsolationForest
old_beats_train = y_train
n_beat = X_train[y_train==0]
s_beat = X_train[y_train==1]
v_beat = X_train[y_train==2]
f_beat = X_train[y_train==3]

print(len(n_beat), len(s_beat), len(v_beat),len(f_beat) )

n_beat_y = y_train[y_train==0]
s_beat_y = y_train[y_train==1]
v_beat_y = y_train[y_train==2]
f_beat_y = y_train[y_train==3]

print(len(n_beat_y), len(s_beat_y), len(v_beat_y),len(f_beat_y) )

outdetect = IsolationForest(max_features = input_size)

outliers_n = outdetect.fit_predict(n_beat)
outliers_s = outdetect.fit_predict(s_beat)
outliers_v = outdetect.fit_predict(v_beat)
outliers_f = outdetect.fit_predict(f_beat)

print(len(outliers_n), len(outliers_s), len(outliers_v),len(outliers_f) )

n_beat = n_beat[outliers_n==1]
s_beat = s_beat[outliers_s==1]
v_beat = v_beat[outliers_v==1]
f_beat = f_beat[outliers_f==1]

print(len(n_beat), len(s_beat), len(v_beat),len(f_beat) )

n_beat_y = n_beat_y[outliers_n==1]
s_beat_y = s_beat_y[outliers_s==1]
v_beat_y = v_beat_y[outliers_v==1]
f_beat_y = f_beat_y[outliers_f==1]

print(len(n_beat_y), len(s_beat_y), len(v_beat_y),len(f_beat_y) )

n_beat_y = n_beat_y.reshape(n_beat_y.shape[0],1)
s_beat_y = s_beat_y.reshape(s_beat_y.shape[0],1)
v_beat_y = v_beat_y.reshape(v_beat_y.shape[0],1)
f_beat_y = f_beat_y.reshape(f_beat_y.shape[0],1)


X_train = np.vstack((n_beat,s_beat, v_beat, f_beat))
y_train = np.vstack((n_beat_y,s_beat_y, v_beat_y, f_beat_y))


#outlers_test = outdetect.fit_predict(X_test)

45809 976 3788 414
45809 976 3788 414


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:213: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:223: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:417: DeprecationWarning: threshold_ attribute is deprecated in 0.20 and will be removed in 0.22.
  " be removed in 0.22.", DeprecationWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:213: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-pa

45809 976 3788 414
41228 878 3409 372
41228 878 3409 372


In [12]:
from sklearn.ensemble import IsolationForest
old_beats_train = y_test
n_beat = X_test[y_test==0]
s_beat = X_test[y_test==1]
v_beat = X_test[y_test==2]
f_beat = X_test[y_test==3]

print(len(n_beat), len(s_beat), len(v_beat),len(f_beat) )

n_beat_y = y_test[y_test==0]
s_beat_y = y_test[y_test==1]
v_beat_y = y_test[y_test==2]
f_beat_y = y_test[y_test==3]

print(len(n_beat_y), len(s_beat_y), len(v_beat_y),len(f_beat_y) )

outdetect = IsolationForest(max_features = input_size)

outliers_n = outdetect.fit_predict(n_beat)
outliers_s = outdetect.fit_predict(s_beat)
outliers_v = outdetect.fit_predict(v_beat)
outliers_f = outdetect.fit_predict(f_beat)

print(len(outliers_n), len(outliers_s), len(outliers_v),len(outliers_f) )

n_beat = n_beat[outliers_n==1]
s_beat = s_beat[outliers_s==1]
v_beat = v_beat[outliers_v==1]
f_beat = f_beat[outliers_f==1]

print(len(n_beat), len(s_beat), len(v_beat),len(f_beat) )

n_beat_y = n_beat_y[outliers_n==1]
s_beat_y = s_beat_y[outliers_s==1]
v_beat_y = v_beat_y[outliers_v==1]
f_beat_y = f_beat_y[outliers_f==1]

print(len(n_beat_y), len(s_beat_y), len(v_beat_y),len(f_beat_y) )

n_beat_y = n_beat_y.reshape(n_beat_y.shape[0],1)
s_beat_y = s_beat_y.reshape(s_beat_y.shape[0],1)
v_beat_y = v_beat_y.reshape(v_beat_y.shape[0],1)
f_beat_y = f_beat_y.reshape(f_beat_y.shape[0],1)


X_test = np.vstack((n_beat,s_beat, v_beat, f_beat))
y_test = np.vstack((n_beat_y,s_beat_y, v_beat_y, f_beat_y))


#outlers_test = outdetect.fit_predict(X_test)

44021 2050 3220 388
44021 2050 3220 388


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:213: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:223: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:417: DeprecationWarning: threshold_ attribute is deprecated in 0.20 and will be removed in 0.22.
  " be removed in 0.22.", DeprecationWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:213: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-pa

44021 2050 3220 388
39619 1845 2898 349
39619 1845 2898 349


In [6]:
from sklearn.model_selection import KFold, GroupKFold # import KFold
kf = KFold(n_splits=10) # Define the split - into 2 folds 
kf.get_n_splits(X_train, y_train)#, group) # returns the number of splitting iterations in the cross-validator


X_train_list = []
y_train_list = []
for one, two in kf.split(X_train, y_train):
    
    X_train_list.append(X_train[one])
    #X_train_list.append(X_train[two])
    y_train_list.append(y_train[one])
    #y_train_list.append(y_train[two])

"""""
kf.get_n_splits(X_test) # returns the number of splitting iterations in the cross-validator


X_test_list = []
y_test_list = []
for one, two in kf.split(X_test):
    
    X_test_list.append(X_test[one])
    X_test_list.append(X_test[two])
    y_test_list.append(y_test[one])
    y_test_list.append(y_test[two])
"""""

'""\nkf.get_n_splits(X_test) # returns the number of splitting iterations in the cross-validator\n\n\nX_test_list = []\ny_test_list = []\nfor one, two in kf.split(X_test):\n    \n    X_test_list.append(X_test[one])\n    X_test_list.append(X_test[two])\n    y_test_list.append(y_test[one])\n    y_test_list.append(y_test[two])\n'

In [34]:
 X_train=gooddata_X_train
y_train=gooddata_y_train 
X_test=gooddata_X_test 
y_test=gooddata_y_test 

In [19]:
from sklearn.model_selection import train_test_split



X_train, X_test, y_train, y_test = train_test_split(X_train,y_train, test_size=0.33, random_state=42)

In [29]:
from imblearn.under_sampling import RandomUnderSampler, ClusterCentroids

ada=RandomUnderSampler(sampling_strategy='all', replacement=True)
train, train_labels=ada.fit_sample(X_train, y_train)
test, test_labels=ada.fit_sample(X_test, y_test)

X_train = train
#X_test = test
y_train = train_labels
#y_test = test_labels
input_size=X_train.shape[1]

In [23]:
from sklearn.svm import LinearSVC

def linear_svc(X_train, y_train, X_test, y_test,penalty='l2', loss='squared_hinge', dual=True, tol=0.001, C=10, multi_class='crammer_singer', fit_intercept=True, intercept_scaling=10, class_weight='balanced'):
    linearclass = LinearSVC(penalty=penalty, loss=loss, dual=dual, tol=tol, C=C, multi_class=multi_class, fit_intercept=fit_intercept, intercept_scaling=intercept_scaling, class_weight=class_weight)
    linearclass.fit(X_train, y_train)
    y_pred = linearclass.predict(X_test)    
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))
    print(metric.get_metrics(y_pred,y_test))
    
    return metric.get_metrics(y_pred,y_test)[2]

In [122]:
from sklearn.ensemble import RandomForestClassifier

## Number of feature at 50 or 100 is good too
## numner of estimators leaves at 1000 

def randomForest(X_train, y_train, X_test, y_test,n_estimators=1000, criterion='gini', max_depth=16, min_samples_split=2, min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, max_features=50, max_leaf_nodes=None, class_weight='balanced'):
    
    rf = RandomForestClassifier(n_estimators=n_estimators, criterion=criterion, max_depth=max_depth, min_samples_split=min_samples_split, min_samples_leaf=min_samples_leaf,min_weight_fraction_leaf=min_weight_fraction_leaf, class_weight=class_weight, min_impurity_decrease=min_impurity_decrease,max_features=max_features)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)    
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))
    print(metric.get_metrics(y_pred,y_test))
    
    return rf, metric.get_metrics(y_pred,y_test)[2]

In [25]:
from sklearn import svm

## Number of feature at 50 or 100 is good too


def svm_model_linear(X_train, y_train, X_test, y_test, C=10, kernel='inear', degree=3, gamma='auto', 
                        coef0=0.0, shrinking=True, probability=True, tol=0.1, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None):
    
    svm_model_linear = svm.SVC(C=C, kernel=kernel, degree=degree, gamma=gamma, 
                        coef0=coef0, shrinking=shrinking, probability=probability, tol=tol, 
                        cache_size=cache_size, verbose=verbose, 
                        max_iter=max_iter, decision_function_shape='ovo', random_state=random_state) 
    
    svm_model_linear.fit(X_train, y_train)
    y_pred = svm_model_linear.predict(X_test)    
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))
    print(metric.get_metrics(y_pred,y_test))
    
    return svm_model_linear, metric.get_metrics(y_pred,y_test)[2]

In [26]:
from sklearn import svm

## small C from 1 to 3 seems to be good for f class recalled
## degree 3 is better all around
## Tol at 0.01 seems best

def svm_model_poly(X_train, y_train, X_test, y_test, C=10, kernel='poly', degree=3, gamma='auto', 
                        coef0=0.001, shrinking=True, probability=True, tol=0.01, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None):
    
    svm_model_linear = svm.SVC(C=C, kernel=kernel, degree=degree, gamma=gamma, 
                        coef0=coef0, shrinking=shrinking, probability=probability, tol=tol, 
                        cache_size=cache_size, verbose=verbose, 
                        max_iter=max_iter, decision_function_shape='ovo', random_state=random_state) 
    
    svm_model_linear.fit(X_train, y_train)
    y_pred = svm_model_linear.predict(X_test)    
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))
    print(metric.get_metrics(y_pred,y_test))
    
    return svm_model_linear, metric.get_metrics(y_pred,y_test)[2]

In [27]:
from sklearn import svm

## quite greedy on the v class
## might remove this one

def svm_model_rbf(X_train, y_train, X_test, y_test, C=10, kernel='rbf', degree=3, gamma='auto', 
                        coef0=0.001, shrinking=True, probability=True, tol=0.1, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None):
    
    svm_model_linear = svm.SVC(C=C, kernel=kernel, degree=degree, gamma=gamma, 
                        coef0=coef0, shrinking=shrinking, probability=probability, tol=tol, 
                        cache_size=cache_size, verbose=verbose, 
                        max_iter=max_iter, decision_function_shape='ovo', random_state=random_state) 
    
    svm_model_linear.fit(X_train, y_train)
    y_pred = svm_model_linear.predict(X_test)    
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))
    print(metric.get_metrics(y_pred,y_test))
    
    return svm_model_linear, metric.get_metrics(y_pred,y_test)[2]

In [28]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

def Linear_D(X_train, y_train, X_test, y_test):
    clf = LinearDiscriminantAnalysis()
    clf.fit(X_train, y_train)  
    y_pred = clf.predict(X_test)
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))
    print(metric.get_metrics(y_pred,y_test))
    
    return clf, metric.get_metrics(y_pred,y_test)[2]

In [29]:
from sklearn.ensemble import ExtraTreesClassifier

def ExtraTree(X_train, y_train, X_test, y_test,n_estimators=1000, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, max_features=50, max_leaf_nodes=None, class_weight='balanced'):
    clf = ExtraTreesClassifier(n_estimators=n_estimators, criterion=criterion, max_depth=max_depth, min_samples_split=min_samples_split, min_samples_leaf=min_samples_leaf,min_weight_fraction_leaf=min_weight_fraction_leaf, class_weight=class_weight, min_impurity_decrease=min_impurity_decrease,max_features=max_features)
    clf.fit(X_train, y_train)  
    y_pred = clf.predict(X_test)
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))
    print(metric.get_metrics(y_pred,y_test))
    
    return clf, metric.get_metrics(y_pred,y_test)[2]

In [30]:
from sklearn.linear_model import LogisticRegression
## L1 one is good , l2 would be used
## very good at f class recall
## solver = ['newton-cg', 'lbfgs', 'liblinear'are all good, ensemble with all would be good

## false dual is better
def logisticRegress(X_train, y_train, X_test, y_test, penalty='l2', dual=False, tol=0.0001, C=100, fit_intercept=True, intercept_scaling=10, class_weight='balanced', random_state=None, solver='warn', max_iter=100, multi_class='warn', verbose=0, warm_start=False, n_jobs=None):
    lr = LogisticRegression(penalty=penalty, dual=dual, tol=tol, C=C, fit_intercept=fit_intercept, intercept_scaling=intercept_scaling, class_weight=class_weight, random_state=random_state, solver=solver, max_iter=max_iter, multi_class=multi_class, verbose=verbose, warm_start=warm_start, n_jobs=n_jobs)
        # dual=dual, tol=tol, C=C, fit_intercept=fit_intercept, intercept_scaling=1, class_weight=None, random_state=None, solver=’warn’, max_iter=100, multi_class=’warn’, verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
    lr.fit(X_train, y_train.ravel())  
    y_pred = lr.predict(X_test)
    print(confusion_matrix(y_test.ravel(),y_pred.ravel()))  
    print(classification_report(y_test.ravel(),y_pred.ravel()))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel()))
    
    return lr, metric.get_metrics(y_pred,y_test)[2]

In [78]:
ld, score = logisticRegress(X_train, y_train, X_test, y_test)

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[27212  3605  4501  4301]
 [ 1186   510    53    96]
 [  194   188  2408   108]
 [    0     0     0   349]]
              precision    recall  f1-score   support

           0       0.95      0.69      0.80     39619
           1       0.12      0.28      0.17      1845
           2       0.35      0.83      0.49      2898
           3       0.07      1.00      0.13       349

   micro avg       0.68      0.68      0.68     44711
   macro avg       0.37      0.70      0.40     44711
weighted avg       0.87      0.68      0.75     44711

[0.23927842243753328, 1.5717402214192098, 0.31610673889616786]


In [118]:
from sklearn.ensemble import AdaBoostClassifier

rf = RandomForestClassifier(n_estimators=2500, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, max_features=50, max_leaf_nodes=None, class_weight='balanced')


ada = AdaBoostClassifier(base_estimator=rf, n_estimators=50 )
ada.fit(X_train, y_train)  
y_pred = ada.predict(X_test)
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))
print(metric.get_metrics(y_pred,y_test))
    


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


KeyboardInterrupt: 

In [111]:
### xgbo is good for normal classes too
## do this one next 
## XGB is very goos for V class
## XGboost tree classifcation is good with 5 or more tree depth
from xgboost import XGBClassifier


def xgboost(X_train,y_train, X_test, y_test, max_depth = 8, eta = 1, gamma = 0.001, min_child_weight=0.1,max_delta_step=10, subsample=0.6,colsample_bytree = 0.7, colsample_bylevel= 1, colsample_bynode=1, alpha=0, reg_lambda= 1, tree_method='exact', grow_policy='depthwise', refresh_leaf=True, process_type='default', predictor= 'cpu_predictor'): 
    model = XGBClassifier(max_depth = max_depth, eta = eta, gamma = gamma,min_child_weight=min_child_weight,subsample=subsample, max_delta_step= max_delta_step,colsample_bytree=colsample_bytree,colsample_bylevel=colsample_bylevel,colsample_bynode=colsample_bynode,alpha=alpha,reg_lambda=reg_lambda,grow_policy=grow_policy, tree_method=tree_method,refresh_leaf=refresh_leaf,process_type=process_type, predictor= predictor,objective = 'reg:logistic')
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    
    print(confusion_matrix(y_test.ravel(),y_pred.ravel()))  
    print(classification_report(y_test.ravel(),y_pred.ravel()))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel()))
    
    return model, metric.get_metrics(y_pred,y_test)[2]


In [116]:
### xgbo is good for normal classes too
## do this one next 
## XGB is very goos for V class
## XGboost tree classifcation is good with 5 or more tree depth
from xgboost import XGBClassifier


def xgboost(X_train,y_train, X_test, y_test,  predictor= 'cpu_predictor'): 
    model = XGBClassifier( booster = 'dart',predictor= predictor,objective = 'reg:logistic')
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    
    print(confusion_matrix(y_test.ravel(),y_pred.ravel()))  
    print(classification_report(y_test.ravel(),y_pred.ravel()))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel()))
    
    return model, metric.get_metrics(y_pred,y_test)[2]

In [117]:
xgboost(X_train, y_train, X_test, y_test)[1]

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[33610  1910  1959  2140]
 [ 1467   289    69    20]
 [   87   116  2669    26]
 [   22     0   109   218]]
              precision    recall  f1-score   support

           0       0.96      0.85      0.90     39619
           1       0.12      0.16      0.14      1845
           2       0.56      0.92      0.69      2898
           3       0.09      0.62      0.16       349

   micro avg       0.82      0.82      0.82     44711
   macro avg       0.43      0.64      0.47     44711
weighted avg       0.89      0.82      0.85     44711

[0.39533479259712656, 1.7578050478657792, 0.4173930272817857]


0.4173930272817857

In [14]:
from sklearn.neighbors import KNeighborsClassifier
nbrs = KNeighborsClassifier(n_neighbors=100, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None)
nbrs.fit(X_train, y_train)
y_pred = nbrs.predict(X_test)
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))
print(metric.get_metrics(y_pred,y_test))

C:\Users\chont\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


[[33617    50  5949     3]
 [ 1740     0   105     0]
 [  626     4  2268     0]
 [    0     0   349     0]]
              precision    recall  f1-score   support

           0       0.93      0.85      0.89     39619
           1       0.00      0.00      0.00      1845
           2       0.26      0.78      0.39      2898
           3       0.00      0.00      0.00       349

   micro avg       0.80      0.80      0.80     44711
   macro avg       0.30      0.41      0.32     44711
weighted avg       0.84      0.80      0.81     44711

[0.28019892330281276, 1.0441702225810172, 0.27062073947403353]


In [53]:
columns = ['features', 'rfscore']
import pandas as pd
df = pd.DataFrame(features,columns=columns)

In [54]:
#df[df['rfscore'] >= 0.01]

df = df.sort_values(['rfscore', 'features'], ascending=[0,1])
df[df['rfscore'] >= 0.004]


features   rfscore
43   wave_MLII43  0.064886
42   wave_MLII42  0.054265
51      wave_V16  0.043476
22   wave_MLII22  0.043289
32   wave_MLII32  0.037404
31   wave_MLII31  0.034340
50      wave_V15  0.026865
29   wave_MLII29  0.026337
88     wave_V143  0.024959
96     hbf_MLII6  0.024383
70     wave_V125  0.022057
23   wave_MLII23  0.021505
11   wave_MLII11  0.021087
30   wave_MLII30  0.019891
28   wave_MLII28  0.019269
10   wave_MLII10  0.015870
87     wave_V142  0.015707
24   wave_MLII24  0.013854
33   wave_MLII33  0.013631
5     wave_MLII5  0.013398
92     hbf_MLII2  0.013316
6     wave_MLII6  0.013172
52      wave_V17  0.012964
44   wave_MLII44  0.012335
7     wave_MLII7  0.011036
16   wave_MLII16  0.010482
25   wave_MLII25  0.010347
34   wave_MLII34  0.010029
66     wave_V121  0.009461
26   wave_MLII26  0.009421
..           ...       ...
41   wave_MLII41  0.008518
68     wave_V123  0.007694
4     wave_MLII4  0.007422
9     wave_MLII9  0.007342
35   wave_MLII35  0.007097
14   wave_MLII14  0.006979
80     wave_V135  0.006750
76     wave_V131  0.006649
21   wave_MLII21  0.006171
111      hbf_V16  0.006135
91     hbf_MLII1  0.006089
89     wave_V144  0.005969
74     wave_V129  0.005891
77     wave_V132  0.005619
101   hbf_MLII11  0.005422
75     wave_V130  0.005249
53      wave_V18  0.005034
79     wave_V134  0.004578
18   wave_MLII18  0.004571
67     wave_V122  0.004546
8     wave_MLII8  0.004442
49      wave_V14  0.004403
81     wave_V136  0.004378
19   wave_MLII19  0.004369
36   wave_MLII36  0.004277
15   wave_MLII15  0.004226
12   wave_MLII12  0.004177
105      hbf_V10  0.004069
120    hos_MLII0  0.004041
63     wave_V118  0.004004

[63 rows x 2 columns]

In [45]:
feat_labels = ["R_duration", "R_height", "R_amp0", "R_amp1","R_amp2","R_amp3", "R_amp4", "R_amp5", "R_amp6", "R_amp7", "R_amp8", "R_amp9", "R_prominence","R_areas","Q_duration", "Q_height", "Q_amp0", "Q_amp1","Q_amp2","Q_amp3", "Q_amp4", "Q_amp5", "Q_amp6", "Q_amp7", "Q_amp8", "Q_amp9", "Q_prominence","Q_areas", "S_duration", "S_height", "S_amp0", "S_amp1","S_amp2","S_amp3", "S_amp4", "S_amp5", "S_amp6", "S_amp7", "S_amp8", "S_amp9", "S_prominence","S_areas", "P_duration", "P_height", "P_amp0", "P_amp1","P_amp2","P_amp3", "P_amp4", "P_amp5", "P_amp6", "P_amp7", "P_amp8", "P_amp9", "P_prominence","P_areas", "P_neg_duration", "P_neg_height", "P_neg_amp0", "P_neg_amp1","P_neg_amp2","P_neg_amp3", "P_neg_amp4", "P_neg_amp5", "P_neg_amp6", "P_neg_amp7", "P_neg_amp8", "P_neg_amp9", "P_neg_prominence","P_neg_areas", "T_duration", "T_height", "T_amp0", "T_amp1","T_amp2","T_amp3", "T_amp4", "T_amp5", "T_amp6", "T_amp7", "T_amp8", "T_amp9", "T_prominence","T_areas","T_neg_durations","T_neg_height", "T_neg_amp0", "T_neg_amp1", "T_neg_amp2", "T_neg_amp3", "T_neg_amp4", "T_neg_amp5", "T_neg_amp6", "T_neg_amp7", "T_neg_amp8", "T_neg_amp9","T_neg_prominence","T_neg_areas", "rr_int_pre", "rr_int_post", "rr_int_10", "rr_int_50", "rr_int_all", "QRS_int", "QRS_int_10", "QRS_int_50", "PQ_int", "PQ_int_10", "PQ_int_50", "PR_int", "PR_int_10", "PR_int_50", "ST_int", "ST_int_10", "ST_int_50", "RT_int", "RT_int_10", "RT_int_50", "PT_int", "PT_int_10", "PT_int_50", "RP","TR","neg_RQ", "neg_PR", "neg_ST", "neg_RT", "neg_PT", "P_neg_T", "neg_P_neg_T"]
feat_labels_V = ["R_duration_V", "R_height_V", "R_amp0_V", "R_amp1_V","R_amp2_V","R_amp3_V", "R_amp4_V", "R_amp5_V", "R_amp6_V", "R_amp7_V", "R_amp8_V", "R_amp9_V", "R_prominence_V","R_areas_V","Q_duration_V", "Q_height_V", "Q_amp0_V", "Q_amp1_V","Q_amp2_V","Q_amp3_V", "Q_amp4_V", "Q_amp5_V", "Q_amp6_V", "Q_amp7_V", "Q_amp8_V", "Q_amp9_V", "Q_prominence_V","Q_areas_V", "S_duration_V", "S_height_V", "S_amp0_V", "S_amp1_V","S_amp2_V","S_amp3_V", "S_amp4_V", "S_amp5_V", "S_amp6_V", "S_amp7_V", "S_amp8_V", "S_amp9_V", "S_prominence_V","S_areas_V", "P_duration_V", "P_height_V", "P_amp0_V", "P_amp1_V","P_amp2_V","P_amp3_V", "P_amp4_V", "P_amp5_V", "P_amp6_V", "P_amp7_V", "P_amp8_V", "P_amp9_V", "P_prominence_V","P_areas_V", "P_neg_duration_V", "P_neg_height_V", "P_neg_amp0_V", "P_neg_amp1_V","P_neg_amp2_V","P_neg_amp3_V", "P_neg_amp4_V", "P_neg_amp5_V", "P_neg_amp6_V", "P_neg_amp7_V", "P_neg_amp8_V", "P_neg_amp9_V", "P_neg_prominence_V","P_neg_areas_V", "T_duration_V", "T_height_V", "T_amp0_V", "T_amp1_V","T_amp2_V","T_amp3_V", "T_amp4_V", "T_amp5_V", "T_amp6_V", "T_amp7_V", "T_amp8_V", "T_amp9_V", "T_prominence_V","T_areas_V","T_neg_durations_V","T_neg_height_V", "T_neg_amp0_V", "T_neg_amp1_V", "T_neg_amp2_V", "T_neg_amp3_V", "T_neg_amp4_V", "T_neg_amp5_V", "T_neg_amp6_V", "T_neg_amp7_V", "T_neg_amp8_V", "T_neg_amp9_V","T_neg_prominence_V","T_neg_areas_V", "rr_int_pre_V", "rr_int_post_V", "rr_int_10_V", "rr_int_50_V", "rr_int_all_V", "QRS_int_V", "QRS_int_10_V", "QRS_int_50_V", "PQ_int_V", "PQ_int_10_V", "PQ_int_50_V", "PR_int_V", "PR_int_10_V", "PR_int_50_V", "ST_int_V", "ST_int_10_V", "ST_int_50_V", "RT_int_V", "RT_int_10_V", "RT_int_50_V", "PT_int_V", "PT_int_10_V", "PT_int_50_V", "RP_V","TR_V","neg_RQ_V", "neg_PR_V", "neg_ST_V", "neg_RT_V", "neg_PT_V", "P_neg_T_V", "neg_P_neg_T_V"]
feat_labels_dtw = ["dtw1","dtw2"]
norm_dtw = ["dtw1_v1","dtw2_v1"]
classID = ["classID"]
non_clinic = list(DB1_non_cli.iloc[:,0:140].columns.values)

feature_norm_mill = []
for i in range(len(feat_labels)):
    feature_norm_mill.append(str(feat_labels[i]+"_n_MLII"))

feature_norm_V1 = []
for i in range(len(feat_labels)):
    feature_norm_V1.append(str(feat_labels[i]+"_n_V1"))
    

c_ID = np.asarray(classID)
f_M = np.asarray(feat_labels)
f_V = np.asarray(feat_labels_V)
f_d = np.asarray(feat_labels_dtw)
non_cli = np.asarray(non_clinic)
norm_mlii = np.asarray(feature_norm_mill)
norm_v1 = np.asarray(feature_norm_V1)
norm_dtw = np.asarray(norm_dtw)


#features_clinic = np.hstack((c_ID,non_cli))#f_M,f_V, f_d,non_cli,norm_mlii, norm_v1,norm_dtw))
features_clinic = np.hstack((f_M,f_V, f_d,))
#features_clinic = np.hstack((non_cli))

features = []
for feature in zip(features_clinic):
    
    features.append(feature)

In [39]:
#rf, score = randomForest(X_train, y_train, X_test, y_test)

#rf.feature_importances_

feat_labels = ["R_duration", "R_height", "R_amp0", "R_amp1","R_amp2","R_amp3", "R_amp4", "R_amp5", "R_amp6", "R_amp7", "R_amp8", "R_amp9", "R_prominence","R_areas","Q_duration", "Q_height", "Q_amp0", "Q_amp1","Q_amp2","Q_amp3", "Q_amp4", "Q_amp5", "Q_amp6", "Q_amp7", "Q_amp8", "Q_amp9", "Q_prominence","Q_areas", "S_duration", "S_height", "S_amp0", "S_amp1","S_amp2","S_amp3", "S_amp4", "S_amp5", "S_amp6", "S_amp7", "S_amp8", "S_amp9", "S_prominence","S_areas", "P_duration", "P_height", "P_amp0", "P_amp1","P_amp2","P_amp3", "P_amp4", "P_amp5", "P_amp6", "P_amp7", "P_amp8", "P_amp9", "P_prominence","P_areas", "P_neg_duration", "P_neg_height", "P_neg_amp0", "P_neg_amp1","P_neg_amp2","P_neg_amp3", "P_neg_amp4", "P_neg_amp5", "P_neg_amp6", "P_neg_amp7", "P_neg_amp8", "P_neg_amp9", "P_neg_prominence","P_neg_areas", "T_duration", "T_height", "T_amp0", "T_amp1","T_amp2","T_amp3", "T_amp4", "T_amp5", "T_amp6", "T_amp7", "T_amp8", "T_amp9", "T_prominence","T_areas","T_neg_durations","T_neg_height", "T_neg_amp0", "T_neg_amp1", "T_neg_amp2", "T_neg_amp3", "T_neg_amp4", "T_neg_amp5", "T_neg_amp6", "T_neg_amp7", "T_neg_amp8", "T_neg_amp9","T_neg_prominence","T_neg_areas", "rr_int_pre", "rr_int_post", "rr_int_10", "rr_int_50", "rr_int_all", "QRS_int", "QRS_int_10", "QRS_int_50", "PQ_int", "PQ_int_10", "PQ_int_50", "PR_int", "PR_int_10", "PR_int_50", "ST_int", "ST_int_10", "ST_int_50", "RT_int", "RT_int_10", "RT_int_50", "PT_int", "PT_int_10", "PT_int_50", "RP","TR","neg_RQ", "neg_PR", "neg_ST", "neg_RT", "neg_PT", "P_neg_T", "neg_P_neg_T"]
feat_labels_V = ["R_duration_V", "R_height_V", "R_amp0_V", "R_amp1_V","R_amp2_V","R_amp3_V", "R_amp4_V", "R_amp5_V", "R_amp6_V", "R_amp7_V", "R_amp8_V", "R_amp9_V", "R_prominence_V","R_areas_V","Q_duration_V", "Q_height_V", "Q_amp0_V", "Q_amp1_V","Q_amp2_V","Q_amp3_V", "Q_amp4_V", "Q_amp5_V", "Q_amp6_V", "Q_amp7_V", "Q_amp8_V", "Q_amp9_V", "Q_prominence_V","Q_areas_V", "S_duration_V", "S_height_V", "S_amp0_V", "S_amp1_V","S_amp2_V","S_amp3_V", "S_amp4_V", "S_amp5_V", "S_amp6_V", "S_amp7_V", "S_amp8_V", "S_amp9_V", "S_prominence_V","S_areas_V", "P_duration_V", "P_height_V", "P_amp0_V", "P_amp1_V","P_amp2_V","P_amp3_V", "P_amp4_V", "P_amp5_V", "P_amp6_V", "P_amp7_V", "P_amp8_V", "P_amp9_V", "P_prominence_V","P_areas_V", "P_neg_duration_V", "P_neg_height_V", "P_neg_amp0_V", "P_neg_amp1_V","P_neg_amp2_V","P_neg_amp3_V", "P_neg_amp4_V", "P_neg_amp5_V", "P_neg_amp6_V", "P_neg_amp7_V", "P_neg_amp8_V", "P_neg_amp9_V", "P_neg_prominence_V","P_neg_areas_V", "T_duration_V", "T_height_V", "T_amp0_V", "T_amp1_V","T_amp2_V","T_amp3_V", "T_amp4_V", "T_amp5_V", "T_amp6_V", "T_amp7_V", "T_amp8_V", "T_amp9_V", "T_prominence_V","T_areas_V","T_neg_durations_V","T_neg_height_V", "T_neg_amp0_V", "T_neg_amp1_V", "T_neg_amp2_V", "T_neg_amp3_V", "T_neg_amp4_V", "T_neg_amp5_V", "T_neg_amp6_V", "T_neg_amp7_V", "T_neg_amp8_V", "T_neg_amp9_V","T_neg_prominence_V","T_neg_areas_V", "rr_int_pre_V", "rr_int_post_V", "rr_int_10_V", "rr_int_50_V", "rr_int_all_V", "QRS_int_V", "QRS_int_10_V", "QRS_int_50_V", "PQ_int_V", "PQ_int_10_V", "PQ_int_50_V", "PR_int_V", "PR_int_10_V", "PR_int_50_V", "ST_int_V", "ST_int_10_V", "ST_int_50_V", "RT_int_V", "RT_int_10_V", "RT_int_50_V", "PT_int_V", "PT_int_10_V", "PT_int_50_V", "RP_V","TR_V","neg_RQ_V", "neg_PR_V", "neg_ST_V", "neg_RT_V", "neg_PT_V", "P_neg_T_V", "neg_P_neg_T_V"]
feat_labels_dtw = ["dtw1","dtw2"]
f_M = np.asarray(feat_labels)
f_V = np.asarray(feat_labels_V)
f_d = np.asarray(feat_labels_dtw)
features_clinic = np.hstack((f_M,f_V, f_d ))
features = []
 
#for feature in zip(features_clinic, rf.feature_importances_):
    
    #features.append(feature)

In [121]:
penalty = ['l1','l2']
loss = ['hinge', 'squared_hinge'] 
fit_intercept = [True, False]
tol = [0.00001, 0.0001, 0.001, 0.01, 0.1]
g = [0.00001, 0.0001, 0.001, 0.01, 0.1, 1]
cache_size = [100, 500, 1000, 1500, 2000,2500,3000,3500,4000]
criterion = ['gini', 'entropy']
min_samples_split = [2,3,5,10,20,50,100,200,500,1000]
#fit_in
clf = []
class_weight = [None,'balanced']
min_samples_leaf = [1,2,3,5,10,20,40,50,100]
min_weight_fraction_leaf = [0,0.0001,0.001,0.01,0.1]
min_impurity_decrease = [0,0.0001,0.001,0.01,0.1, 1]
gamma = ['scale','auto']
coef0 = [0.00001,0.0001,0.001,0.01,0.1,1,10,100]
max_features = ['auto', 'sqrt','log2', None, 10, 50, 100, 200]
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
C=[0.01,0.1,1,2,5,10,20,50,100]
degree = [1,2,3,4,5,6,7,8,9,10,11,12]
shrinking = [True, False]
multi_class=['ovr', 'multinomial', 'auto']
max_depth = [1,2,4,8,16,32,64,128,236,500,1000]

max_depth = [10,16,20,30,50]

min_child_weight = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7,0.8]
gamma = [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10,100]
subsample = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7,0.8]
max_delta_step = [0,0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10,100]

colsample_bytree =  [0.01,0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7,0.8,1]
colsample_bylevel =  [0.01,0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7,0.8,1]
colsample_bynode =  [0.01,0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7,0.8,1]
reg_lambda = [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10,100]
alpha = [0,0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10,100]

tree_method = ['auto', 'exact', 'approx', 'hist', 'gpu_hist']
#updater = [('distcol','grow_histmaker', 'grow_local_histmaker','grow_skmaker','sync', 'refresh', 'prune'), ('grow_colmaker','prune')]

grow_policy=['depthwise', 'lossguide']
refresh_leaf = [True,False]


predictor= ['cpu_predictor','gpu_predictor']

process_type = ['default', 'update']

ls = max_depth

for i in range(len(ls)):
    print(ls[i])
    clf.append(randomForest(X_train, y_train, X_test, y_test, max_depth=ls[i])[1])

10


C:\Users\chont\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':


[[33119  1879  1352  3269]
 [ 1021   249   572     3]
 [   72   130  2657    39]
 [    0     0    34   315]]
              precision    recall  f1-score   support

           0       0.97      0.84      0.90     39619
           1       0.11      0.13      0.12      1845
           2       0.58      0.92      0.71      2898
           3       0.09      0.90      0.16       349

   micro avg       0.81      0.81      0.81     44711
   macro avg       0.44      0.70      0.47     44711
weighted avg       0.90      0.81      0.85     44711

[0.40098866856017795, 1.737804439257663, 0.41771988918729686]
16


C:\Users\chont\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':


[[32850  1862  1504  3403]
 [  995   249   600     1]
 [   75   131  2654    38]
 [    0     0    23   326]]
              precision    recall  f1-score   support

           0       0.97      0.83      0.89     39619
           1       0.11      0.13      0.12      1845
           2       0.56      0.92      0.69      2898
           3       0.09      0.93      0.16       349

   micro avg       0.81      0.81      0.81     44711
   macro avg       0.43      0.70      0.47     44711
weighted avg       0.90      0.81      0.84     44711

[0.39306288486313334, 1.7169388974280861, 0.4111488046100774]
20


C:\Users\chont\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':


[[32885  1859  1532  3343]
 [  979   245   615     6]
 [   76   130  2652    40]
 [    0     0    28   321]]
              precision    recall  f1-score   support

           0       0.97      0.83      0.89     39619
           1       0.11      0.13      0.12      1845
           2       0.55      0.92      0.69      2898
           3       0.09      0.92      0.16       349

   micro avg       0.81      0.81      0.81     44711
   macro avg       0.43      0.70      0.46     44711
weighted avg       0.90      0.81      0.84     44711

[0.39390142664601635, 1.706983526306447, 0.41032365411131405]
30


C:\Users\chont\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':


[[33020  1807  1505  3287]
 [ 1007   249   582     7]
 [   75   135  2655    33]
 [    0     0    34   315]]
              precision    recall  f1-score   support

           0       0.97      0.83      0.90     39619
           1       0.11      0.13      0.12      1845
           2       0.56      0.92      0.69      2898
           3       0.09      0.90      0.16       349

   micro avg       0.81      0.81      0.81     44711
   macro avg       0.43      0.70      0.47     44711
weighted avg       0.90      0.81      0.84     44711

[0.3976268023806075, 1.7206596771794742, 0.413895860837738]
50


C:\Users\chont\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':


[[32982  1860  1556  3221]
 [  994   250   597     4]
 [   61   136  2670    31]
 [    0     0    40   309]]
              precision    recall  f1-score   support

           0       0.97      0.83      0.90     39619
           1       0.11      0.14      0.12      1845
           2       0.55      0.92      0.69      2898
           3       0.09      0.89      0.16       349

   micro avg       0.81      0.81      0.81     44711
   macro avg       0.43      0.69      0.47     44711
weighted avg       0.90      0.81      0.84     44711

[0.39778927347106235, 1.7171792006634614, 0.41354203681846385]


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[34882  1612  1245  1880]
 [ 1498   246    84    17]
 [   64    51  2762    21]
 [   25     0   108   216]]
              precision    recall  f1-score   support

           0       0.96      0.88      0.92     39619
           1       0.13      0.13      0.13      1845
           2       0.66      0.95      0.78      2898
           3       0.10      0.62      0.17       349

   micro avg       0.85      0.85      0.85     44711
   macro avg       0.46      0.65      0.50     44711
weighted avg       0.90      0.85      0.87     44711

[0.45085314000459276, 1.8730433569146072, 0.4595569896166223]


0.4595569896166223

In [ ]:
import matplotlib.pyplot as plt
ls = [str(i) for i in ls]
plt.plot(ls, clf)

In [42]:
bin_labels = y_train.copy()
bin_labels[y_train != 0]=1
bin_labels[y_train == 0]=0
bin_y_train=np.array(bin_labels, dtype=int)

bin_labels_test = y_test.copy()
bin_labels_test[y_test != 0]=1
bin_labels_test[y_test == 0]=0
bin_y_test=np.array(bin_labels_test, dtype=int)

voting_ensemble(X_train, bin_y_train, X_test,bin_y_test)

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[30001  9618]
 [ 1363  3729]]
              precision    recall  f1-score   support

           0       0.96      0.76      0.85     39619
           1       0.28      0.73      0.40      5092

   micro avg       0.75      0.75      0.75     44711
   macro avg       0.62      0.74      0.62     44711
weighted avg       0.88      0.75      0.80     44711



IndexError: index 2 is out of bounds for axis 0 with size 2

In [41]:
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import VotingClassifier
import time
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm



def voting_ensemble(X_train, y_train, X_test,y_test):
    svm_model_linear = svm.SVC(C=10, kernel='linear', degree=3, gamma='auto', 
                            coef0=0.0, shrinking=True, probability=True, tol=0.1, 
                            cache_size=200, verbose=False, 
                            max_iter=-1, decision_function_shape='ovo', random_state=None)

    svm_model_poly = svm.SVC(C=10, kernel='poly', degree=3, gamma='auto', 
                            coef0=0.001, shrinking=True, probability=True, tol=0.01, 
                            cache_size=200, verbose=False, 
                            max_iter=-1, decision_function_shape='ovo', random_state=None)


    rf = RandomForestClassifier(n_estimators=1000, criterion='gini', max_depth=16, min_samples_split=2, 
                                min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, 
                                max_features=50, max_leaf_nodes=None, class_weight='balanced')


    lr = LogisticRegression( penalty='l2', dual=False, tol=0.0001, C=100, fit_intercept=True, intercept_scaling=10, 
                            class_weight='balanced', random_state=None, solver='warn', max_iter=100, multi_class='warn',
                            verbose=0, warm_start=False, n_jobs=None)


    xgb = XGBClassifier(max_depth = 8, eta = 1, gamma = 0.001, min_child_weight=0.1,max_delta_step=10, 
                        subsample=0.6,colsample_bytree = 0.7, colsample_bylevel= 1, colsample_bynode=1, alpha=0, 
                        reg_lambda= 1, tree_method='exact', grow_policy='depthwise', refresh_leaf=True, 
                        process_type='default', predictor= 'cpu_predictor',objective = 'reg:logistic')




    eclf = VotingClassifier(estimators=[('svc_2', svm_model_poly), ('xgb',xgb),('rf',rf), ('lr',lr), ('svm_ln   ',svm_model_linear)],
                           voting='hard', weights=[2,2,2,2,2])



    #clf1 = clf1.fit(X, y)
    #clf2 = clf2.fit(X, y)
    #clf3 = clf3.fit(X, y)
    eclf = eclf.fit(X_train, bin_y_train)

    predict = eclf.predict(X_test)
    #scores = cross_val_score(X_train, y_train.data, iris.target, cv=10)
    #scores.mean()                             

    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict))
    print(metric.get_metrics(predict.ravel(),y_test.ravel()))
    
    return eclf, metric.get_metrics(predict.ravel(),y_test.ravel())[2]




In [39]:
from sklearn import svm

svm_model_poly = svm.SVC(C=10, kernel='poly', degree=3, gamma='auto', 
                        coef0=0.001, shrinking=True, probability=True, tol=0.01, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None)

svm_model_linear = svm.SVC(C=10, kernel='linear', degree=3, gamma='auto', 
                        coef0=0.0, shrinking=True, probability=True, tol=0.1, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None)

rf = RandomForestClassifier(n_estimators=1000, criterion='gini', max_depth=16, min_samples_split=2, 
                            min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, 
                            max_features=50, max_leaf_nodes=None, class_weight='balanced')


In [43]:
svm_model_poly.fit(X_train, y_train)

predict = svm_model_poly.predict(X_test)
#scores = cross_val_score(X_train, y_train.data, iris.target, cv=10)
#scores.mean()                             

print(confusion_matrix(y_test,predict))  
print(classification_report(y_test,predict))
print(metric.get_metrics(predict.ravel(),y_test.ravel()))

svm_model_linear.fit(X_train, y_train)

predict = svm_model_linear.predict(X_test)
#scores = cross_val_score(X_train, y_train.data, iris.target, cv=10)
#scores.mean()                             

print(confusion_matrix(y_test,predict))  
print(classification_report(y_test,predict))
print(metric.get_metrics(predict.ravel(),y_test.ravel()))


rf.fit(X_train, y_train)

predict = rf.predict(X_test)
#scores = cross_val_score(X_train, y_train.data, iris.target, cv=10)
#scores.mean()                             

print(confusion_matrix(y_test,predict))  
print(classification_report(y_test,predict))
print(metric.get_metrics(predict.ravel(),y_test.ravel()))

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[34391  1094  2826  1308]
 [  462  1180   198     5]
 [  276   235  2338    49]
 [   63     0     0   286]]
              precision    recall  f1-score   support

           0       0.98      0.87      0.92     39619
           1       0.47      0.64      0.54      1845
           2       0.44      0.81      0.57      2898
           3       0.17      0.82      0.29       349

   micro avg       0.85      0.85      0.85     44711
   macro avg       0.51      0.78      0.58     44711
weighted avg       0.91      0.85      0.88     44711

[0.5011853165216339, 2.3526679074581622, 0.5446761466930872]


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[33583  2956   787  2293]
 [ 1162   435   169    79]
 [  287    98  2421    92]
 [  128    13     3   205]]
              precision    recall  f1-score   support

           0       0.96      0.85      0.90     39619
           1       0.12      0.24      0.16      1845
           2       0.72      0.84      0.77      2898
           3       0.08      0.59      0.14       349

   micro avg       0.82      0.82      0.82     44711
   macro avg       0.47      0.63      0.49     44711
weighted avg       0.90      0.82      0.85     44711

[0.38751074006272596, 1.9116630082182284, 0.43271324605864153]


C:\Users\chont\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


[[31058  2769  2053  3739]
 [  399   298  1148     0]
 [   45    83  2689    81]
 [    0     0     8   341]]
              precision    recall  f1-score   support

           0       0.99      0.78      0.87     39619
           1       0.09      0.16      0.12      1845
           2       0.46      0.93      0.61      2898
           3       0.08      0.98      0.15       349

   micro avg       0.77      0.77      0.77     44711
   macro avg       0.40      0.71      0.44     44711
weighted avg       0.91      0.77      0.82     44711

[0.36469031325907675, 1.6399193473140068, 0.3873350750437892]


In [16]:
from sklearn.ensemble import AdaBoostClassifier



ada = AdaBoostClassifier(base_estimator=svm_model_poly, n_estimators=50 )
ada.fit(X_train, y_train)  
y_pred = ada.predict(X_test)
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))
print(metric.get_metrics(y_pred,y_test))

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


KeyboardInterrupt: 

In [ ]:
rf = RandomForestClassifier(n_estimators=1000, criterion='gini', max_depth=16, min_samples_split=2, 
                            min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, 
                            max_features=50, max_leaf_nodes=None, class_weight='balanced')

In [47]:
import pandas as pd

#df = pd.DataFrame(features,columns=columns)(features,columns=columns)

dataframe_X = pd.DataFrame(X_train,columns=features)
dataframe_y = pd.DataFrame(y_train)



In [48]:
dataframe_X.to_csv('database/good_X_train.csv')
dataframe_y.to_csv('database/good_y_train.csv')