In [2]:
from codes.python import load_DF_beats as DF
import numpy as np
from codes.python import metric
from codes.python import features_columns as col
from codes. python import post_process_features_ex as post_features
import pandas as pd
from codes.python import TunedClassifier as classifier
from sklearn.metrics import classification_report, confusion_matrix 
ls = []
ls.extend(['N', 'L', 'R'])                    # N
ls.extend(['A', 'a', 'J', 'S', 'e', 'j'])     # SVEB 
ls.extend(['V', 'E'])                         # VEB
ls.extend(['F'])
#ls.extend([ 'P', '/', 'f', 'u'])
patient_l_1 = [101]
#patient_l_2 = [100]
patient_ls_1 = [101,106,108,109,112,114,115,116,118,119,122,124,201,203,205,207,208,209,215,220,223,230]
patient_ls_2 = [100,103,105,111,113,117,121,123,200,202,210,212,213,214,219,221,222,228,231,232,233,234]


ls2 = []
ls2.extend(["['N']","['L']", "['R']"])                    # N
ls2.extend(["['A']", "['a']", "['J']", "['S']",  "['e']", "['j']"])     # SVEB 
ls2.extend(["['V']", "['E']"])                         # VEB
ls2.extend(["['F']"])
#ls.extend([ "['P']","[ '/']"," ['f']", "['u']"])


good_features_X = np.asarray(pd.read_csv("database/gooddata_X_train_no_outliers.csv").iloc[:,1:263])
good_features_y = np.asarray(pd.read_csv("database/gooddata_y_train_no_outliers.csv").iloc[:,1])



np_clinic_1_old, np_clinic_2_old,np_non_var_1_old, np_non_var_2_old, np_class_ID_1_old, np_class_ID_2_old, patients_ls_1, patients_ls_2, DB1, DB2, DB1_V1, DB2_V1, DB1_non_cli, DB2_non_cli, DB1_dwt, DB2_dwt, DB1_dwt_V1, DB2_dwt_V1 = DF.get_all_dataframe(patient_l_1=patient_ls_1,patient_l_2=patient_ls_2 , ls=ls, ls2=ls2 )

np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]

features_clinic,c_ID,f_M, f_V, f_d , norm_mlii, norm_v1 , norm_dtw = col.get_columns()

    
X_train_balanced = pd.DataFrame(good_features_X,columns=features_clinic)
X_train = pd.DataFrame(X_train,columns=features_clinic)
X_test = pd.DataFrame(X_test,columns=features_clinic)

import pickle
f = open('database/nvs_lin.text', 'rb')
n_s = pickle.load(f)[1]
f.close()

f = open('database/nvv_lin.text', 'rb')
n_v = pickle.load(f)[1]
f.close()

f = open('database/nvf_lin.text', 'rb')
n_f = pickle.load(f)[1]
f.close()

f = open('database/svv_lin.text', 'rb')
s_v = pickle.load(f)[1]
f.close()

f = open('database/svf_lin.text', 'rb')
s_f = pickle.load(f)[1]
f.close()

f = open('database/vvf_lin.text', 'rb')
v_f = pickle.load(f)[1]
f.close()

In [5]:


np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]
features_clinic,c_ID,f_M, f_V, f_d , norm_mlii, norm_v1 , norm_dtw = col.get_columns()

#X_train_under = pd.DataFrame(under_X_train,columns=features_clinic)
X_train_balanced = pd.DataFrame(good_features_X,columns=features_clinic)
X_train = pd.DataFrame(X_train,columns=features_clinic)
X_test = pd.DataFrame(X_test,columns=features_clinic)

y_train[y_train != 2] = 0
y_train[y_train == 2] = 1

y_test[y_test != 2] = 0
y_test[y_test == 2] = 1



print("Log")
print("all")
#classifier.logisticRegress(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.logisticRegress(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.logisticRegress(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.logisticRegress(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.logisticRegress(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.logisticRegress(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.logisticRegress(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("Lin")
print("all")
#classifier.Linear_D(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.Linear_D(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.Linear_D(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.Linear_D(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.Linear_D(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.Linear_D(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.Linear_D(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("Random")
print("all")
#classifier.randomForest(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
## Use this first
classifier.randomForest(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.randomForest(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.randomForest(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.randomForest(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.randomForest(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.randomForest(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


print("ensamble ln")
print("all")
#classifier.voting_ensemble_lin(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.voting_ensemble_lin(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.voting_ensemble_lin(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.voting_ensemble_lin(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.voting_ensemble_lin(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.voting_ensemble_lin(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.voting_ensemble_lin(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])




Log
all
n_s
[[41034   955  1021  1011]
 [  512  1245   237    56]
 [  537   404  2226    53]
 [  361     0     6    21]]
              precision    recall  f1-score   support

           0       0.97      0.93      0.95     44021
           1       0.48      0.61      0.54      2050
           2       0.64      0.69      0.66      3220
           3       0.02      0.05      0.03       388

   micro avg       0.90      0.90      0.90     49679
   macro avg       0.53      0.57      0.54     49679
weighted avg       0.92      0.90      0.91     49679

[0.560565089690647, 2.4145543696453604, 0.5821018410509935]
n_v
[[39564  2044  2300   113]
 [ 1794   196    46    14]
 [  296   218  2413   293]
 [  191    61     6   130]]
              precision    recall  f1-score   support

           0       0.95      0.90      0.92     44021
           1       0.08      0.10      0.09      2050
           2       0.51      0.75      0.60      3220
           3       0.24      0.34      0.28       388


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[42710   778   416   117]
 [ 1076   857   117     0]
 [ 1866   359   939    56]
 [  360     0    16    12]]
              precision    recall  f1-score   support

           0       0.93      0.97      0.95     44021
           1       0.43      0.42      0.42      2050
           2       0.63      0.29      0.40      3220
           3       0.06      0.03      0.04       388

   micro avg       0.90      0.90      0.90     49679
   macro avg       0.51      0.43      0.45     49679
weighted avg       0.88      0.90      0.88     49679

[0.4086296431852523, 1.7705014425211902, 0.42562750190777493]
n_v
[[43521   258   212    30]
 [ 2019    14    16     1]
 [  764    57  2205   194]
 [  349    12     5    22]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96     44021
           1       0.04      0.01      0.01      2050
           2       0.90      0.68      0.78      3220
           3       0.09      0.06      0.07       388

   micro 

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[41005    19   458  2539]
 [ 1919     3   101    27]
 [ 1982    10  1027   201]
 [   34     0     7   347]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92     44021
           1       0.09      0.00      0.00      2050
           2       0.64      0.32      0.43      3220
           3       0.11      0.89      0.20       388

   micro avg       0.85      0.85      0.85     49679
   macro avg       0.44      0.54      0.39     49679
weighted avg       0.86      0.85      0.85     49679

[0.24992622275099316, 1.058853057013656, 0.2573197435022036]
s_v
[[39588    35  1862  2536]
 [ 2003     0     7    40]
 [  839    80  2016   285]
 [   22     0    44   322]]
              precision    recall  f1-score   support

           0       0.93      0.90      0.92     44021
           1       0.00      0.00      0.00      2050
           2       0.51      0.63      0.56      3220
           3       0.10      0.83      0.18       388

   micro a

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[40968    52   840  2161]
 [ 1991    10    41     8]
 [  727    15  2301   177]
 [   33     0     4   351]]
              precision    recall  f1-score   support

           0       0.94      0.93      0.93     44021
           1       0.13      0.00      0.01      2050
           2       0.72      0.71      0.72      3220
           3       0.13      0.90      0.23       388

   micro avg       0.88      0.88      0.88     49679
   macro avg       0.48      0.64      0.47     49679
weighted avg       0.88      0.88      0.88     49679

[0.43511968335932966, 1.5715666741647651, 0.4140056759502605]
Random
all
n_s
[[40557   681  1879   904]
 [ 1389   125   518    18]
 [  341    22  2853     4]
 [  129     0   259     0]]
              precision    recall  f1-score   support

           0       0.96      0.92      0.94     44021
           1       0.15      0.06      0.09      2050
           2       0.52      0.89      0.65      3220
           3       0.00      0.00      0.00       388

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[42843   776   396     6]
 [ 1084   850   116     0]
 [ 1954   389   859    18]
 [  378     0     8     2]]
              precision    recall  f1-score   support

           0       0.93      0.97      0.95     44021
           1       0.42      0.41      0.42      2050
           2       0.62      0.27      0.37      3220
           3       0.08      0.01      0.01       388

   micro avg       0.90      0.90      0.90     49679
   macro avg       0.51      0.41      0.44     49679
weighted avg       0.88      0.90      0.88     49679

[0.3981745973349851, 1.7261557168747879, 0.41485676327684107]
n_v


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[43563   272   174    12]
 [ 2020    14    16     0]
 [  831    66  2141   182]
 [  354    12     4    18]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96     44021
           1       0.04      0.01      0.01      2050
           2       0.92      0.66      0.77      3220
           3       0.08      0.05      0.06       388

   micro avg       0.92      0.92      0.92     49679
   macro avg       0.49      0.43      0.45     49679
weighted avg       0.89      0.92      0.90     49679

[0.5113663977480521, 1.627114127275056, 0.4590724647834081]
n_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[41030    61   411  2519]
 [ 1919     3   103    25]
 [ 2009    12  1001   198]
 [   34     0     7   347]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92     44021
           1       0.04      0.00      0.00      2050
           2       0.66      0.31      0.42      3220
           3       0.11      0.89      0.20       388

   micro avg       0.85      0.85      0.85     49679
   macro avg       0.43      0.53      0.39     49679
weighted avg       0.85      0.85      0.85     49679

[0.24648540674011496, 1.00949391767573, 0.24942944307952375]
s_v


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[40334    51  2070  1566]
 [ 2006     1    27    16]
 [  845   117  2137   121]
 [   65     1    67   255]]
              precision    recall  f1-score   support

           0       0.93      0.92      0.92     44021
           1       0.01      0.00      0.00      2050
           2       0.50      0.66      0.57      3220
           3       0.13      0.66      0.22       388

   micro avg       0.86      0.86      0.86     49679
   macro avg       0.39      0.56      0.43     49679
weighted avg       0.86      0.86      0.86     49679

[0.3710710129110553, 1.1668959491634308, 0.3313975001009565]
s_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[42489    29  1431    72]
 [ 2021     0    26     3]
 [ 2759    26   410    25]
 [  282     0   104     2]]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93     44021
           1       0.00      0.00      0.00      2050
           2       0.21      0.13      0.16      3220
           3       0.02      0.01      0.01       388

   micro avg       0.86      0.86      0.86     49679
   macro avg       0.28      0.27      0.27     49679
weighted avg       0.81      0.86      0.83     49679

[0.08563822160253709, 0.3353454279600795, 0.08473728929627848]
v_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[41059    56   794  2112]
 [ 1991    11    41     7]
 [  775    33  2236   176]
 [   35     0     4   349]]
              precision    recall  f1-score   support

           0       0.94      0.93      0.93     44021
           1       0.11      0.01      0.01      2050
           2       0.73      0.69      0.71      3220
           3       0.13      0.90      0.23       388

   micro avg       0.88      0.88      0.88     49679
   macro avg       0.48      0.63      0.47     49679
weighted avg       0.88      0.88      0.88     49679

[0.4311712029574429, 1.5369302630914508, 0.40770188436515276]


(VotingClassifier(estimators=[('ln', LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
               solver='svd', store_covariance=False, tol=0.0001)), ('lr', LogisticRegression(C=100, class_weight='balanced', dual=False,
           fit_intercept=True, intercept_scaling=10, max_iter=100,
           multi_class='warn', n_jobs=None, penalty='l2', random_state=None,
           solver='warn', tol=0.0001, verbose=0, warm_start=False))],
          flatten_transform=None, n_jobs=None, voting='hard', weights=None),
 array([0, 0, 0, ..., 0, 0, 0]),
 [0.4311712029574429, 1.5369302630914508, 0.40770188436515276])

In [ ]:
np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]
features_clinic,c_ID,f_M, f_V, f_d , norm_mlii, norm_v1 , norm_dtw = col.get_columns()

#X_train_under = pd.DataFrame(under_X_train,columns=features_clinic)
X_train_balanced = pd.DataFrame(good_features_X,columns=features_clinic)
X_train = pd.DataFrame(X_train,columns=features_clinic)
X_test = pd.DataFrame(X_test,columns=features_clinic)

y_train[y_train != 2] = 0
y_train[y_train == 2] = 1

y_test[y_test != 2] = 0
y_test[y_test == 2] = 1



print("svm_linear")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.svm_model_linear(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.svm_model_linear(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.svm_model_linear(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.svm_model_linear(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.svm_model_linear(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.svm_model_linear(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])


print("svm_poly")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.svm_model_poly(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.svm_model_poly(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.svm_model_poly(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.svm_model_poly(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.svm_model_poly(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.svm_model_poly(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])


print("randomforest")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.randomForest(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.randomForest(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.randomForest(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.randomForest(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.randomForest(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.randomForest(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])



print("xgboost")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.xgboost(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.xgboost(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.xgboost(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.xgboost(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.xgboost(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.xgboost(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])




print("ada")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.ada(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.ada(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.ada(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.ada(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.ada(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.ada(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])


print("ada")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.voting_ensemble(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.voting_ensemble(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.voting_ensemble(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.voting_ensemble(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.voting_ensemble(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.voting_ensemble(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])


print("Log")
print("all")
#classifier.logisticRegress(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.logisticRegress(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.logisticRegress(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.logisticRegress(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.logisticRegress(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.logisticRegress(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.logisticRegress(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("Lin")
print("all")
#classifier.Linear_D(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.Linear_D(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.Linear_D(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.Linear_D(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.Linear_D(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.Linear_D(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.Linear_D(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("Random")
print("all")
#classifier.randomForest(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
## Use this first
classifier.randomForest(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.randomForest(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.randomForest(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.randomForest(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.randomForest(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.randomForest(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



svm_linear
all
n_s
[[45976   483     0     0]
 [ 1444  1776     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98     46459
           1       0.79      0.55      0.65      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.96      0.96      0.96     49679
   macro avg       0.44      0.39      0.41     49679
weighted avg       0.96      0.96      0.96     49679

n_v


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[46199   260     0     0]
 [ 1493  1727     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98     46459
           1       0.87      0.54      0.66      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.96      0.96      0.96     49679
   macro avg       0.46      0.38      0.41     49679
weighted avg       0.96      0.96      0.96     49679

n_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[46459     0     0     0]
 [ 3220     0     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97     46459
           1       0.00      0.00      0.00      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.94      0.94      0.94     49679
   macro avg       0.23      0.25      0.24     49679
weighted avg       0.87      0.94      0.90     49679

s_v


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[44694  1765     0     0]
 [  772  2448     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.98      0.96      0.97     46459
           1       0.58      0.76      0.66      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.95      0.95      0.95     49679
   macro avg       0.39      0.43      0.41     49679
weighted avg       0.96      0.95      0.95     49679

s_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[45491   968     0     0]
 [ 2842   378     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.94      0.98      0.96     46459
           1       0.28      0.12      0.17      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.92      0.92      0.92     49679
   macro avg       0.31      0.27      0.28     49679
weighted avg       0.90      0.92      0.91     49679

v_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[46100   359     0     0]
 [ 1203  2017     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98     46459
           1       0.85      0.63      0.72      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.97      0.97      0.97     49679
   macro avg       0.46      0.40      0.43     49679
weighted avg       0.97      0.97      0.97     49679

svm_poly
all
n_s


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[46074   385     0     0]
 [ 1317  1903     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98     46459
           1       0.83      0.59      0.69      3220

   micro avg       0.97      0.97      0.97     49679
   macro avg       0.90      0.79      0.84     49679
weighted avg       0.96      0.97      0.96     49679

n_v
[[46449    10     0     0]
 [ 3219     1     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97     46459
           1       0.09      0.00      0.00      3220

   micro avg       0.94      0.94      0.94     49679
   macro avg       0.51      0.50      0.48     49679
weighted avg       0.88      0.94      0.90     49679

n_f
[[42645  3814     0     0]
 [ 1791  1429     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
           

In [ ]:



X_train = X_train_balanced

y_train = good_features_y

print("svm_linear")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.svm_model_linear(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.svm_model_linear(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.svm_model_linear(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.svm_model_linear(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.svm_model_linear(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.svm_model_linear(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


print("svm_poly")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.svm_model_poly(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.svm_model_poly(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.svm_model_poly(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.svm_model_poly(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.svm_model_poly(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.svm_model_poly(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


print("randomforest")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.randomForest(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.randomForest(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.randomForest(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.randomForest(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.randomForest(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.randomForest(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("xgboost")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.xgboost(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.xgboost(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.xgboost(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.xgboost(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.xgboost(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.xgboost(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])




print("ada")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.ada(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.ada(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.ada(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.ada(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.ada(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.ada(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


print("ada")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.voting_ensemble(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.voting_ensemble(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.voting_ensemble(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.voting_ensemble(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.voting_ensemble(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.voting_ensemble(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])

