In [1]:
from codes.python import load_DF_beats as DF
import numpy as np
from codes.python import metric
from codes.python import features_columns as col
from codes. python import post_process_features_ex as post_features
import pandas as pd
from codes.python import TunedClassifier as classifier
from sklearn.metrics import classification_report, confusion_matrix 
ls = []
ls.extend(['N', 'L', 'R'])                    # N
ls.extend(['A', 'a', 'J', 'S', 'e', 'j'])     # SVEB 
ls.extend(['V', 'E'])                         # VEB
ls.extend(['F'])
#ls.extend([ 'P', '/', 'f', 'u'])
patient_l_1 = [101]
#patient_l_2 = [100]
patient_ls_1 = [101,106,108,109,112,114,115,116,118,119,122,124,201,203,205,207,208,209,215,220,223,230]
patient_ls_2 = [100,103,105,111,113,117,121,123,200,202,210,212,213,214,219,221,222,228,231,232,233,234]


ls2 = []
ls2.extend(["['N']","['L']", "['R']"])                    # N
ls2.extend(["['A']", "['a']", "['J']", "['S']",  "['e']", "['j']"])     # SVEB 
ls2.extend(["['V']", "['E']"])                         # VEB
ls2.extend(["['F']"])
#ls.extend([ "['P']","[ '/']"," ['f']", "['u']"])


good_features_X = np.asarray(pd.read_csv("database/gooddata_X_train_no_outliers.csv").iloc[:,1:263])
good_features_y = np.asarray(pd.read_csv("database/gooddata_y_train_no_outliers.csv").iloc[:,1])



np_clinic_1_old, np_clinic_2_old,np_non_var_1_old, np_non_var_2_old, np_class_ID_1_old, np_class_ID_2_old, patients_ls_1, patients_ls_2, DB1, DB2, DB1_V1, DB2_V1, DB1_non_cli, DB2_non_cli, DB1_dwt, DB2_dwt, DB1_dwt_V1, DB2_dwt_V1 = DF.get_all_dataframe(patient_l_1=patient_ls_1,patient_l_2=patient_ls_2 , ls=ls, ls2=ls2 )

np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]

features_clinic,c_ID,f_M, f_V, f_d , norm_mlii, norm_v1 , norm_dtw = col.get_columns()

    
X_train_balanced = pd.DataFrame(good_features_X,columns=features_clinic)
X_train = pd.DataFrame(X_train,columns=features_clinic)
X_test = pd.DataFrame(X_test,columns=features_clinic)

import pickle
f = open('database/nvs_log.text', 'rb')
n_s = pickle.load(f)[1]
f.close()

f = open('database/nvv_log.text', 'rb')
n_v = pickle.load(f)[1]
f.close()

f = open('database/nvf_log.text', 'rb')
n_f = pickle.load(f)[1]
f.close()

f = open('database/svv_log.text', 'rb')
s_v = pickle.load(f)[1]
f.close()

f = open('database/svf_log.text', 'rb')
s_f = pickle.load(f)[1]
f.close()

f = open('database/vvf_log.text', 'rb')
v_f = pickle.load(f)[1]
f.close()

In [2]:
np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]


features_clinic,c_ID,f_M, f_V, f_d , norm_mlii, norm_v1 , norm_dtw = col.get_columns()

    
X_train = pd.DataFrame(X_train,columns=features_clinic)
X_test = pd.DataFrame(X_test,columns=features_clinic)






print("Log")
print("all")
#classifier.logisticRegress(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.logisticRegress(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.logisticRegress(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.logisticRegress(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.logisticRegress(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.logisticRegress(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.logisticRegress(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("Lin")
print("all")
#classifier.Linear_D(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.Linear_D(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.Linear_D(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.Linear_D(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.Linear_D(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.Linear_D(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.Linear_D(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("Random")
print("all")
#classifier.randomForest(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
## Use this first
classifier.randomForest(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.randomForest(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.randomForest(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.randomForest(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.randomForest(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.randomForest(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


print("ensamble ln")
print("all")
#classifier.voting_ensemble_lin(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.voting_ensemble_lin(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.voting_ensemble_lin(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.voting_ensemble_lin(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.voting_ensemble_lin(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.voting_ensemble_lin(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.voting_ensemble_lin(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


from imblearn.under_sampling import RandomUnderSampler, ClusterCentroids

ada=RandomUnderSampler(ratio='not minority')
train, train_labels=ada.fit_sample(X_train, y_train)
test, 
=ada.fit_sample(X_test, y_test)

X_train = train
#X_test = test
y_train = train_labels
#y_test = test_labels
input_size=X_train.shape[1]


X_train = pd.DataFrame(X_train,columns=features_clinic)


print("ensamble ln")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.svm_model_linear(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.svm_model_linear(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.svm_model_linear(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.svm_model_linear(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.svm_model_linear(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.svm_model_linear(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


Log
all
n_s
[[41636   977   889   519]
 [ 1117   431   461    41]
 [  249   150  2524   297]
 [  172     0     6   210]]
              precision    recall  f1-score   support

           0       0.96      0.95      0.96     44021
           1       0.28      0.21      0.24      2050
           2       0.65      0.78      0.71      3220
           3       0.20      0.54      0.29       388

   micro avg       0.90      0.90      0.90     49679
   macro avg       0.52      0.62      0.55     49679
weighted avg       0.91      0.90      0.90     49679

[0.560462419836804, 1.9212470117691272, 0.5203870863895429]
n_v
[[42258   511   840   412]
 [  963    96   924    67]
 [  645   130  2287   158]
 [  380     0     7     1]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96     44021
           1       0.13      0.05      0.07      2050
           2       0.56      0.71      0.63      3220
           3       0.00      0.00      0.00       388


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[42400   462  1040   119]
 [ 1611    60   379     0]
 [ 1043   176  1832   169]
 [  202     0    60   126]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95     44021
           1       0.09      0.03      0.04      2050
           2       0.55      0.57      0.56      3220
           3       0.30      0.32      0.31       388

   micro avg       0.89      0.89      0.89     49679
   macro avg       0.47      0.47      0.47     49679
weighted avg       0.87      0.89      0.88     49679

[0.43615731933906016, 1.2374794354069492, 0.37276358909539875]
n_v
[[43360   229   352    80]
 [ 1519    35   463    33]
 [ 1448    38  1669    65]
 [  381     0     7     0]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.96     44021
           1       0.12      0.02      0.03      2050
           2       0.67      0.52      0.58      3220
           3       0.00      0.00      0.00       388

   micro

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[42973    61   415   572]
 [ 2025     7    10     8]
 [  983    26  2037   174]
 [   38     0     6   344]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.95     44021
           1       0.07      0.00      0.01      2050
           2       0.83      0.63      0.72      3220
           3       0.31      0.89      0.46       388

   micro avg       0.91      0.91      0.91     49679
   macro avg       0.54      0.62      0.54     49679
weighted avg       0.89      0.91      0.90     49679

[0.5053122031734347, 1.535856082652062, 0.4446381119182251]
v_f
[[43123   139   231   528]
 [ 1755    40   240    15]
 [  616   119  2271   214]
 [   49     0     0   339]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.96     44021
           1       0.13      0.02      0.03      2050
           2       0.83      0.71      0.76      3220
           3       0.31      0.87      0.46       388

   micro av

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[42867   454   608    92]
 [ 1613    62   375     0]
 [ 1064   190  1818   148]
 [  224     0    47   117]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.95     44021
           1       0.09      0.03      0.04      2050
           2       0.64      0.56      0.60      3220
           3       0.33      0.30      0.31       388

   micro avg       0.90      0.90      0.90     49679
   macro avg       0.50      0.47      0.48     49679
weighted avg       0.88      0.90      0.89     49679

[0.4594172230813849, 1.3210015692440162, 0.39483380769619447]
n_v


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[43459   240   302    20]
 [ 1536    43   462     9]
 [ 1472    56  1656    36]
 [  385     0     3     0]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96     44021
           1       0.13      0.02      0.04      2050
           2       0.68      0.51      0.59      3220
           3       0.00      0.00      0.00       388

   micro avg       0.91      0.91      0.91     49679
   macro avg       0.43      0.38      0.39     49679
weighted avg       0.87      0.91      0.89     49679

[0.43427276252199265, 1.3455552501214054, 0.385330787526172]
n_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[41945    43   195  1838]
 [ 2006     2     9    33]
 [  368    84  2662   106]
 [  144     1    42   201]]
              precision    recall  f1-score   support

           0       0.94      0.95      0.95     44021
           1       0.02      0.00      0.00      2050
           2       0.92      0.83      0.87      3220
           3       0.09      0.52      0.16       388

   micro avg       0.90      0.90      0.90     49679
   macro avg       0.49      0.57      0.49     49679
weighted avg       0.90      0.90      0.90     49679

[0.516440592574184, 1.7584740768413119, 0.47802955589225593]
s_v


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[41945    43   195  1838]
 [ 2006     2     9    33]
 [  368    84  2662   106]
 [  144     1    42   201]]
              precision    recall  f1-score   support

           0       0.94      0.95      0.95     44021
           1       0.02      0.00      0.00      2050
           2       0.92      0.83      0.87      3220
           3       0.09      0.52      0.16       388

   micro avg       0.90      0.90      0.90     49679
   macro avg       0.49      0.57      0.49     49679
weighted avg       0.90      0.90      0.90     49679

[0.516440592574184, 1.7584740768413119, 0.47802955589225593]
s_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[43109    60   529   323]
 [ 2028     7    10     5]
 [ 1007    45  2005   163]
 [   68     0     6   314]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.96     44021
           1       0.06      0.00      0.01      2050
           2       0.79      0.62      0.69      3220
           3       0.39      0.81      0.53       388

   micro avg       0.91      0.91      0.91     49679
   macro avg       0.54      0.60      0.55     49679
weighted avg       0.88      0.91      0.90     49679

[0.503854905620098, 1.4748599514036793, 0.43628494673550894]
v_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[43184   148   208   481]
 [ 1757    44   238    11]
 [  643   182  2193   202]
 [   49     0     0   339]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.96     44021
           1       0.12      0.02      0.04      2050
           2       0.83      0.68      0.75      3220
           3       0.33      0.87      0.48       388

   micro avg       0.92      0.92      0.92     49679
   macro avg       0.56      0.64      0.56     49679
weighted avg       0.90      0.92      0.91     49679

[0.5668965080645184, 1.651162963696073, 0.4898436244942683]
ensamble ln
all
n_s
[[32976  2679  1931  6435]
 [  210  1465   354    21]
 [  116   428  2462   214]
 [   83     2     4   299]]
              precision    recall  f1-score   support

           0       0.99      0.75      0.85     44021
           1       0.32      0.71      0.44      2050
           2       0.52      0.76      0.62      3220
           3       0.04      0.77      0.08       

(SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
   decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
   max_iter=-1, probability=True, random_state=None, shrinking=True,
   tol=0.1, verbose=False),
 SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
   decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
   max_iter=-1, probability=True, random_state=None, shrinking=True,
   tol=0.1, verbose=False),
 array([1, 0, 0, ..., 0, 0, 0]),
 [0.2556523186107291, 1.73130609946325, 0.3442394217382708])

In [5]:
##N class majority
## V_f ensemble all 
#V_f lin
##1 n_v Low percision but high recall  (43360)

### 


print("n vs all results for various classifier")


np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]


features_clinic,c_ID,f_M, f_V, f_d , norm_mlii, norm_v1 , norm_dtw = col.get_columns()

    
X_train = pd.DataFrame(X_train,columns=features_clinic)
X_test = pd.DataFrame(X_test,columns=features_clinic)



print("n_s")
## Use this first
y_pred_rand_n_s = classifier.Linear_D(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])[2]
ab_normal_X_test_1 =X_test[y_pred_rand_n_s != 0]
ab_normal_y_test_1 =y_test[y_pred_rand_n_s != 0]


normal_x_test = X_test[y_pred_rand_n_s == 0]
normal_y_pred = y_pred_rand_n_s[y_pred_rand_n_s == 0]
normal_y_test = y_test[y_pred_rand_n_s == 0] 

n vs all results for various classifier
n_s
[[43360   229   352    80]
 [ 1519    35   463    33]
 [ 1448    38  1669    65]
 [  381     0     7     0]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.96     44021
           1       0.12      0.02      0.03      2050
           2       0.67      0.52      0.58      3220
           3       0.00      0.00      0.00       388

   micro avg       0.91      0.91      0.91     49679
   macro avg       0.43      0.38      0.39     49679
weighted avg       0.87      0.91      0.89     49679

[0.4313224958380087, 1.3213022351893482, 0.38082402731767284]


In [39]:
normal_x_test = pd.DataFrame(normal_x_test,columns=features_clinic)
##s_v seperate v class best
y_pred_ensemble_lin = classifier.voting_ensemble_lin(X_train[s_v], y_train, normal_x_test[s_v], normal_y_test, jk=True,labels=[0,1,2,3])[1]


normal_x_test_s_v =normal_x_test[y_pred_ensemble_lin != 2]
normal_y_test_s_v =normal_y_test[y_pred_ensemble_lin != 2]


normal_x_v_normal = normal_x_test[y_pred_ensemble_lin == 2]
y_pred_svm_v_normal = y_pred_ensemble_lin[y_pred_ensemble_lin == 2]
y_test_svm_v_normal = normal_y_test[y_pred_ensemble_lin == 2]   

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[41363    31   162  1804]
 [ 1509     2     4     4]
 [  202    42  1142    62]
 [  141     1    41   198]]
              precision    recall  f1-score   support

           0       0.96      0.95      0.96     43360
           1       0.03      0.00      0.00      1519
           2       0.85      0.79      0.82      1448
           3       0.10      0.52      0.16       381

   micro avg       0.91      0.91      0.91     46708
   macro avg       0.48      0.57      0.48     46708
weighted avg       0.92      0.91      0.91     46708

[0.3869327429872356, 1.6628594805412609, 0.4013238065612754]


In [17]:
y_pred_ensemble_lin

array([0, 0, 0, ..., 0, 0, 0])

In [37]:
normal_x_test = pd.DataFrame(normal_x_test,columns=features_clinic)
##s_v seperate v class best
y_pred_ensemble_lin = classifier.voting_ensemble_lin(X_train[s_v], y_train, normal_x_test[s_v], normal_y_test, jk=True,labels=[0,1,2,3])[1]


normal_x_test_s_v =normal_x_test[y_pred_ensemble_lin != 2]
normal_y_test_s_v =normal_y_test[y_pred_ensemble_lin != 2]

#y_pred_temp = y_pred_ensemble_lin[y_pred_ensemble_lin != 2]

#normal_x_test_s_v =normal_x_test_s_v[y_pred_temp != 3]
#normal_y_test_s_v =normal_y_test_s_v[y_pred_temp != 3]


y_pred_svm_f_normal = y_pred_ensemble_lin[y_pred_ensemble_lin == 3]
y_test_svm_f_normal = normal_y_test[y_pred_ensemble_lin == 3] 

y_pred_svm_v_normal = y_pred_ensemble_lin[y_pred_ensemble_lin == 2]
y_test_svm_v_normal = normal_y_test[y_pred_ensemble_lin == 2]   

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[41363    31   162  1804]
 [ 1509     2     4     4]
 [  202    42  1142    62]
 [  141     1    41   198]]
              precision    recall  f1-score   support

           0       0.96      0.95      0.96     43360
           1       0.03      0.00      0.00      1519
           2       0.85      0.79      0.82      1448
           3       0.10      0.52      0.16       381

   micro avg       0.91      0.91      0.91     46708
   macro avg       0.48      0.57      0.48     46708
weighted avg       0.92      0.91      0.91     46708

[0.3869327429872356, 1.6628594805412609, 0.4013238065612754]


False

In [48]:
normal_x_test_s_v = pd.DataFrame(normal_x_test_s_v,columns=features_clinic)
##s_v seperate v class best
y_pred_ensemble_lin = classifier.voting_ensemble_lin(X_train[v_f], y_train, normal_x_test_s_v[v_f], normal_y_test_s_v, jk=True,labels=[0,1,2,3])[1]


normal_x_test_v_f =normal_x_test_s_v[y_pred_ensemble_lin != 3]
normal_y_test_v_f =normal_y_test_s_v[y_pred_ensemble_lin != 3]


normal_x_test_f =normal_x_test_s_v[y_pred_ensemble_lin == 3]
y_pred_svm_f_normal = y_pred_ensemble_lin[y_pred_ensemble_lin == 3]
y_test_svm_f_normal = normal_x_test_s_v[y_pred_ensemble_lin == 3]   

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[42608    14   139   437]
 [ 1502    10     2     1]
 [  192     7    63    44]
 [   39     0     0   301]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.97     43198
           1       0.32      0.01      0.01      1515
           2       0.31      0.21      0.25       306
           3       0.38      0.89      0.54       340

   micro avg       0.95      0.95      0.95     45359
   macro avg       0.49      0.52      0.44     45359
weighted avg       0.93      0.95      0.93     45359

[0.2386826086238746, 0.8438871875802381, 0.22482720275946705]


In [52]:
from codes.python import load_DF_beats as DF
import numpy as np
from codes.python import metric
from codes.python import features_columns as col
from codes. python import post_process_features_ex as post_features
import pandas as pd
from codes.python import TunedClassifier as classifier
from sklearn.metrics import classification_report, confusion_matrix 
ls = []
ls.extend(['N', 'L', 'R'])                    # N
ls.extend(['A', 'a', 'J', 'S', 'e', 'j'])     # SVEB 
#ls.extend(['V', 'E'])                         # VEB
#ls.extend(['F'])
#ls.extend([ 'P', '/', 'f', 'u'])
patient_l_1 = [101]
#patient_l_2 = [100]
patient_ls_1 = [101,106,108,109,112,114,115,116,118,119,122,124,201,203,205,207,208,209,215,220,223,230]
patient_ls_2 = [100,103,105,111,113,117,121,123,200,202,210,212,213,214,219,221,222,228,231,232,233,234]


ls2 = []
ls2.extend(["['N']","['L']", "['R']"])                    # N
ls2.extend(["['A']", "['a']", "['J']", "['S']",  "['e']", "['j']"])     # SVEB 
#ls2.extend(["['V']", "['E']"])                         # VEB
#ls2.extend(["['F']"])
#ls.extend([ "['P']","[ '/']"," ['f']", "['u']"])


good_features_X = np.asarray(pd.read_csv("database/gooddata_X_train_no_outliers.csv").iloc[:,1:263])
good_features_y = np.asarray(pd.read_csv("database/gooddata_y_train_no_outliers.csv").iloc[:,1])



np_clinic_1_old, np_clinic_2_old,np_non_var_1_old, np_non_var_2_old, np_class_ID_1_old, np_class_ID_2_old, patients_ls_1, patients_ls_2, DB1, DB2, DB1_V1, DB2_V1, DB1_non_cli, DB2_non_cli, DB1_dwt, DB2_dwt, DB1_dwt_V1, DB2_dwt_V1 = DF.get_all_dataframe(patient_l_1=patient_ls_1,patient_l_2=patient_ls_2 , ls=ls, ls2=ls2 )


np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
#X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
#y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]

X_train = pd.DataFrame(X_train,columns=features_clinic)

rank_n_s = pd.read_csv("database/features_n_vs_s_randomforest.py").sort_values(['rfscore', 'features'], ascending=[0,1])

score_n_s = 0.01


n_s = rank_n_s[rank_n_s['rfscore'] >= score_n_s]['features'].values


y_pred_ensemble_lin = classifier.logisticRegress(X_train[n_s], y_train, normal_x_test_v_f[n_s], normal_y_test_v_f, jk=True,labels=[0,1,2,3])[1]


[[39933  2828     0     0]
 [  264  1250     0     0]
 [   57   205     0     0]
 [   35     4     0     0]]
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     42761
           1       0.29      0.83      0.43      1514
           2       0.00      0.00      0.00       262
           3       0.00      0.00      0.00        39

   micro avg       0.92      0.92      0.92     44576
   macro avg       0.32      0.44      0.35     44576
weighted avg       0.96      0.92      0.94     44576



C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


ZeroDivisionError: float division by zero

In [45]:
normal_y_test_v_f.shape

(44576,)

In [ ]:
np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]


features_clinic,c_ID,f_M, f_V, f_d , norm_mlii, norm_v1 , norm_dtw = col.get_columns()

    
X_train = pd.DataFrame(X_train,columns=features_clinic)
X_test = pd.DataFrame(X_test,columns=features_clinic)


y_train[y_train != 2] = 0
y_train[y_train == 2] = 1

y_test[y_test != 2] = 0
y_test[y_test == 2] = 1


print("svm_linear")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.svm_model_linear(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.svm_model_linear(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.svm_model_linear(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.svm_model_linear(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.svm_model_linear(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.svm_model_linear(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])


print("svm_poly")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.svm_model_poly(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.svm_model_poly(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.svm_model_poly(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.svm_model_poly(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.svm_model_poly(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.svm_model_poly(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])


print("randomforest")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.randomForest(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.randomForest(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.randomForest(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.randomForest(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.randomForest(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.randomForest(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])



print("xgboost")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.xgboost(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.xgboost(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.xgboost(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.xgboost(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.xgboost(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.xgboost(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])




print("ada")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.ada(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.ada(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.ada(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.ada(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.ada(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.ada(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])


print("ada")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.voting_ensemble(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.voting_ensemble(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f") 
classifier.voting_ensemble(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.voting_ensemble(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.voting_ensemble(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.voting_ensemble(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])


print("n_s")
classifier.svm_model_poly(X_train[n_s], y_train, X_test[n_s], y_test, jk=False,labels=[0,1,2,3])
print("n_v")
classifier.svm_model_poly(X_train[n_v], y_train, X_test[n_v], y_test, jk=False,labels=[0,1,2,3])
print("n_f")
classifier.svm_model_poly(X_train[n_f], y_train, X_test[n_f], y_test, jk=False,labels=[0,1,2,3])
print("s_v")
classifier.svm_model_poly(X_train[s_v], y_train, X_test[s_v], y_test, jk=False,labels=[0,1,2,3])
print("s_f")
classifier.svm_model_poly(X_train[s_f], y_train, X_test[s_f], y_test, jk=False,labels=[0,1,2,3])
print("v_f")
classifier.svm_model_poly(X_train[v_f], y_train, X_test[v_f], y_test, jk=False,labels=[0,1,2,3])




print("Log")
print("all")
#classifier.logisticRegress(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.logisticRegress(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.logisticRegress(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.logisticRegress(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.logisticRegress(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.logisticRegress(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.logisticRegress(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("Lin")
print("all")
#classifier.Linear_D(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.Linear_D(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.Linear_D(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.Linear_D(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.Linear_D(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.Linear_D(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.Linear_D(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("Random")
print("all")
#classifier.randomForest(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
## Use this first
classifier.randomForest(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.randomForest(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.randomForest(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.randomForest(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.randomForest(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.randomForest(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



svm_linear
all
n_s
[[45696   763     0     0]
 [  979  2241     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98     46459
           1       0.75      0.70      0.72      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.96      0.96      0.96     49679
   macro avg       0.43      0.42      0.43     49679
weighted avg       0.96      0.96      0.96     49679

n_v


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[45666   793     0     0]
 [ 1759  1461     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97     46459
           1       0.65      0.45      0.53      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.95      0.95      0.95     49679
   macro avg       0.40      0.36      0.38     49679
weighted avg       0.94      0.95      0.94     49679

n_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[45711   748     0     0]
 [  480  2740     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99     46459
           1       0.79      0.85      0.82      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.98      0.98      0.98     49679
   macro avg       0.44      0.46      0.45     49679
weighted avg       0.98      0.98      0.98     49679

s_v


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[45711   748     0     0]
 [  480  2740     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99     46459
           1       0.79      0.85      0.82      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.98      0.98      0.98     49679
   macro avg       0.44      0.46      0.45     49679
weighted avg       0.98      0.98      0.98     49679

s_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[46301   158     0     0]
 [ 1357  1863     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     46459
           1       0.92      0.58      0.71      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.97      0.97      0.97     49679
   macro avg       0.47      0.39      0.42     49679
weighted avg       0.97      0.97      0.97     49679

v_f


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[45972   487     0     0]
 [  963  2257     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.98     46459
           1       0.82      0.70      0.76      3220
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.97      0.97      0.97     49679
   macro avg       0.45      0.42      0.44     49679
weighted avg       0.97      0.97      0.97     49679

svm_poly
all
n_s


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[45654   805     0     0]
 [ 1345  1875     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.98     46459
           1       0.70      0.58      0.64      3220

   micro avg       0.96      0.96      0.96     49679
   macro avg       0.84      0.78      0.81     49679
weighted avg       0.95      0.96      0.95     49679

n_v
[[45967   492     0     0]
 [ 2570   650     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]
              precision    recall  f1-score   support

           0       0.95      0.99      0.97     46459
           1       0.57      0.20      0.30      3220

   micro avg       0.94      0.94      0.94     49679
   macro avg       0.76      0.60      0.63     49679
weighted avg       0.92      0.94      0.92     49679

n_f


In [ ]:
X_train = X_train_balanced

y_train = good_features_y

print("svm_linear")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.svm_model_linear(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.svm_model_linear(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.svm_model_linear(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.svm_model_linear(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.svm_model_linear(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.svm_model_linear(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


print("svm_poly")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.svm_model_poly(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.svm_model_poly(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.svm_model_poly(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.svm_model_poly(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.svm_model_poly(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.svm_model_poly(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


print("randomforest")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.randomForest(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.randomForest(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.randomForest(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.randomForest(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.randomForest(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.randomForest(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("xgboost")
print("all")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.xgboost(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.xgboost(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.xgboost(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.xgboost(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.xgboost(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.xgboost(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])




print("ada")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.ada(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.ada(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.ada(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.ada(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.ada(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.ada(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


print("ada")
#classifier.svm_model_linear(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.voting_ensemble(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.voting_ensemble(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.voting_ensemble(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.voting_ensemble(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.voting_ensemble(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.voting_ensemble(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])


print("Log")
print("all")
#classifier.logisticRegress(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.logisticRegress(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.logisticRegress(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.logisticRegress(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.logisticRegress(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.logisticRegress(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.logisticRegress(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("Lin")
print("all")
#classifier.Linear_D(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
classifier.Linear_D(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.Linear_D(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.Linear_D(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.Linear_D(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.Linear_D(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.Linear_D(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])



print("Random")
print("all")
#classifier.randomForest(X_train[feature_good], y_train, X_test[feature_good], y_test, jk=True,labels=[0,1,2,3])
print("n_s")
## Use this first
classifier.randomForest(X_train[n_s], y_train, X_test[n_s], y_test, jk=True,labels=[0,1,2,3])
print("n_v")
classifier.randomForest(X_train[n_v], y_train, X_test[n_v], y_test, jk=True,labels=[0,1,2,3])
print("n_f")
classifier.randomForest(X_train[n_f], y_train, X_test[n_f], y_test, jk=True,labels=[0,1,2,3])
print("s_v")
classifier.randomForest(X_train[s_v], y_train, X_test[s_v], y_test, jk=True,labels=[0,1,2,3])
print("s_f")
classifier.randomForest(X_train[s_f], y_train, X_test[s_f], y_test, jk=True,labels=[0,1,2,3])
print("v_f")
classifier.randomForest(X_train[v_f], y_train, X_test[v_f], y_test, jk=True,labels=[0,1,2,3])

