In [70]:
from codes.python import load_DF_beats as DF
import numpy as np
from codes.python import metric
from codes. python import post_process_features_ex as post_features
import pandas as pd

from sklearn.metrics import classification_report, confusion_matrix 
ls = []
ls.extend(['N', 'L', 'R'])                    # N
ls.extend(['A', 'a', 'J', 'S', 'e', 'j'])     # SVEB 
ls.extend(['V', 'E'])                         # VEB
ls.extend(['F'])
#ls.extend([ 'P', '/', 'f', 'u'])
patient_l_1 = [101]
#patient_l_2 = [100]
patient_ls_1 = [101,106,108,109,112,114,115,116,118,119,122,124,201,203,205,207,208,209,215,220,223,230]
patient_ls_2 = [100,103,105,111,113,117,121,123,200,202,210,212,213,214,219,221,222,228,231,232,233,234]


ls2 = []
ls2.extend(["['N']","['L']", "['R']"])                    # N
ls2.extend(["['A']", "['a']", "['J']", "['S']",  "['e']", "['j']"])     # SVEB 
ls2.extend(["['V']", "['E']"])                         # VEB
ls2.extend(["['F']"])
#ls.extend([ "['P']","[ '/']"," ['f']", "['u']"])

In [71]:
np_clinic_1_old, np_clinic_2_old,np_non_var_1_old, np_non_var_2_old, np_class_ID_1_old, np_class_ID_2_old, patients_ls_1, patients_ls_2, DB1, DB2, DB1_V1, DB2_V1, DB1_non_cli, DB2_non_cli, DB1_dwt, DB2_dwt, DB1_dwt_V1, DB2_dwt_V1 = DF.get_all_dataframe(patient_l_1=patient_ls_1,patient_l_2=patient_ls_2 , ls=ls, ls2=ls2 )


In [31]:
np_clinic_1, np_clinic_2,np_non_var_1, np_non_var_2, np_class_ID_1, np_class_ID_2 = DF.get_all_dataframe_patient_specific(200,patient_l_1=patient_ls_1,patient_l_2=patient_ls_2 , ls=ls, ls2=ls2 )

done norm
row 0 done
done norm
row 1 done


In [72]:
np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]

In [32]:
np_class_ID_1 = [int(i) for i in np_class_ID_1]
np_class_ID_2 = [int(i) for i in np_class_ID_2]

X_train = np_clinic_1
X_test = np_clinic_2
y_train = np.asarray(np_class_ID_1)
y_test = np.asarray(np_class_ID_2)
input_size=X_train.shape[1]

In [66]:
y_train = y_train.reshape(y_train.shape[0],1)

np_clinic_1_class = np.hstack((y_train,X_train))
#np_clinic_2_class = np.hstack((np_class_ID_2,np_clinic_2))


In [75]:
feat_labels = ["R_duration", "R_height", "R_amp0", "R_amp1","R_amp2","R_amp3", "R_amp4", "R_amp5", "R_amp6", "R_amp7", "R_amp8", "R_amp9", "R_prominence","R_areas","Q_duration", "Q_height", "Q_amp0", "Q_amp1","Q_amp2","Q_amp3", "Q_amp4", "Q_amp5", "Q_amp6", "Q_amp7", "Q_amp8", "Q_amp9", "Q_prominence","Q_areas", "S_duration", "S_height", "S_amp0", "S_amp1","S_amp2","S_amp3", "S_amp4", "S_amp5", "S_amp6", "S_amp7", "S_amp8", "S_amp9", "S_prominence","S_areas", "P_duration", "P_height", "P_amp0", "P_amp1","P_amp2","P_amp3", "P_amp4", "P_amp5", "P_amp6", "P_amp7", "P_amp8", "P_amp9", "P_prominence","P_areas", "P_neg_duration", "P_neg_height", "P_neg_amp0", "P_neg_amp1","P_neg_amp2","P_neg_amp3", "P_neg_amp4", "P_neg_amp5", "P_neg_amp6", "P_neg_amp7", "P_neg_amp8", "P_neg_amp9", "P_neg_prominence","P_neg_areas", "T_duration", "T_height", "T_amp0", "T_amp1","T_amp2","T_amp3", "T_amp4", "T_amp5", "T_amp6", "T_amp7", "T_amp8", "T_amp9", "T_prominence","T_areas","T_neg_durations","T_neg_height", "T_neg_amp0", "T_neg_amp1", "T_neg_amp2", "T_neg_amp3", "T_neg_amp4", "T_neg_amp5", "T_neg_amp6", "T_neg_amp7", "T_neg_amp8", "T_neg_amp9","T_neg_prominence","T_neg_areas", "rr_int_pre", "rr_int_post", "rr_int_10", "rr_int_50", "rr_int_all", "QRS_int", "QRS_int_10", "QRS_int_50", "PQ_int", "PQ_int_10", "PQ_int_50", "PR_int", "PR_int_10", "PR_int_50", "ST_int", "ST_int_10", "ST_int_50", "RT_int", "RT_int_10", "RT_int_50", "PT_int", "PT_int_10", "PT_int_50", "RP","TR","neg_RQ", "neg_PR", "neg_ST", "neg_RT", "neg_PT", "P_neg_T", "neg_P_neg_T"]
feat_labels_V = ["R_duration_V", "R_height_V", "R_amp0_V", "R_amp1_V","R_amp2_V","R_amp3_V", "R_amp4_V", "R_amp5_V", "R_amp6_V", "R_amp7_V", "R_amp8_V", "R_amp9_V", "R_prominence_V","R_areas_V","Q_duration_V", "Q_height_V", "Q_amp0_V", "Q_amp1_V","Q_amp2_V","Q_amp3_V", "Q_amp4_V", "Q_amp5_V", "Q_amp6_V", "Q_amp7_V", "Q_amp8_V", "Q_amp9_V", "Q_prominence_V","Q_areas_V", "S_duration_V", "S_height_V", "S_amp0_V", "S_amp1_V","S_amp2_V","S_amp3_V", "S_amp4_V", "S_amp5_V", "S_amp6_V", "S_amp7_V", "S_amp8_V", "S_amp9_V", "S_prominence_V","S_areas_V", "P_duration_V", "P_height_V", "P_amp0_V", "P_amp1_V","P_amp2_V","P_amp3_V", "P_amp4_V", "P_amp5_V", "P_amp6_V", "P_amp7_V", "P_amp8_V", "P_amp9_V", "P_prominence_V","P_areas_V", "P_neg_duration_V", "P_neg_height_V", "P_neg_amp0_V", "P_neg_amp1_V","P_neg_amp2_V","P_neg_amp3_V", "P_neg_amp4_V", "P_neg_amp5_V", "P_neg_amp6_V", "P_neg_amp7_V", "P_neg_amp8_V", "P_neg_amp9_V", "P_neg_prominence_V","P_neg_areas_V", "T_duration_V", "T_height_V", "T_amp0_V", "T_amp1_V","T_amp2_V","T_amp3_V", "T_amp4_V", "T_amp5_V", "T_amp6_V", "T_amp7_V", "T_amp8_V", "T_amp9_V", "T_prominence_V","T_areas_V","T_neg_durations_V","T_neg_height_V", "T_neg_amp0_V", "T_neg_amp1_V", "T_neg_amp2_V", "T_neg_amp3_V", "T_neg_amp4_V", "T_neg_amp5_V", "T_neg_amp6_V", "T_neg_amp7_V", "T_neg_amp8_V", "T_neg_amp9_V","T_neg_prominence_V","T_neg_areas_V", "rr_int_pre_V", "rr_int_post_V", "rr_int_10_V", "rr_int_50_V", "rr_int_all_V", "QRS_int_V", "QRS_int_10_V", "QRS_int_50_V", "PQ_int_V", "PQ_int_10_V", "PQ_int_50_V", "PR_int_V", "PR_int_10_V", "PR_int_50_V", "ST_int_V", "ST_int_10_V", "ST_int_50_V", "RT_int_V", "RT_int_10_V", "RT_int_50_V", "PT_int_V", "PT_int_10_V", "PT_int_50_V", "RP_V","TR_V","neg_RQ_V", "neg_PR_V", "neg_ST_V", "neg_RT_V", "neg_PT_V", "P_neg_T_V", "neg_P_neg_T_V"]
feat_labels_dtw = ["dtw1","dtw2"]
norm_dtw = ["dtw1_v1","dtw2_v1"]
classID = ["classID"]
non_clinic = list(DB1_non_cli.iloc[:,0:140].columns.values)

feature_norm_mill = []
for i in range(len(feat_labels)):
    feature_norm_mill.append(str(feat_labels[i]+"_n_MLII"))

feature_norm_V1 = []
for i in range(len(feat_labels)):
    feature_norm_V1.append(str(feat_labels[i]+"_n_V1"))
    

c_ID = np.asarray(classID)
f_M = np.asarray(feat_labels)
f_V = np.asarray(feat_labels_V)
f_d = np.asarray(feat_labels_dtw)
non_cli = np.asarray(non_clinic)
norm_mlii = np.asarray(feature_norm_mill)
norm_v1 = np.asarray(feature_norm_V1)
norm_dtw = np.asarray(norm_dtw)

features_clinic_with_class = np.hstack((c_ID,f_M,f_V, f_d))


features_clinic = np.hstack((f_M,f_V, f_d))
features_clinic_norm = np.hstack((f_M,f_V, f_d,norm_mlii,norm_v1,norm_dtw ))
#row=[]
#for i in range(0,len(np_clinic_new_1)):
    #row.append(i)
    
X_train_balanced = pd.DataFrame(good_features_X,columns=features_clinic)
X_train = pd.DataFrame(X_train,columns=features_clinic)
X_test = pd.DataFrame(X_test,columns=features_clinic)

#X_train_balanced_norm = pd.DataFrame(X_train_norm,columns=features_clinic_norm)
#X_test_norm = pd.DataFrame(X_test_norm,columns=features_clinic_norm)

In [67]:
import pandas as pd
df = pd.DataFrame(np_clinic_1_class,columns=features_clinic_with_class)

In [68]:
import pymrmr as mrmr

rank=mrmr.mRMR(df, 'MID', 50)

In [69]:
rank

['dtw1',
 'QRS_int_50_V',
 'R_amp0_V',
 'PQ_int_V',
 'neg_ST_V',
 'neg_RT_V',
 'PQ_int_10_V',
 'T_amp6',
 'T_neg_durations_V',
 'PR_int_50_V',
 'QRS_int_10_V',
 'QRS_int_V',
 'T_neg_areas_V',
 'PQ_int_50_V',
 'TR_V',
 'R_amp0',
 'PR_int_V',
 'S_amp0',
 'PT_int_10_V',
 'RT_int_10_V',
 'neg_PR_V',
 'RP_V',
 'T_amp8',
 'T_amp6_V',
 'PT_int_50_V',
 'PR_int_10_V',
 'R_amp1_V',
 'RT_int_50_V',
 'neg_RQ_V',
 'RT_int_V',
 'ST_int_50_V',
 'ST_int_V',
 'T_amp7',
 'ST_int_10_V',
 'R_duration',
 'T_areas_V',
 'QRS_int',
 'QRS_int_10',
 'T_areas',
 'T_neg_durations',
 'T_neg_areas',
 'dtw2',
 'P_neg_areas',
 'P_neg_prominence',
 'QRS_int_50',
 'PQ_int',
 'PQ_int_10',
 'T_duration',
 'T_amp4',
 'PR_int']

In [77]:
print("n vs all results for various classifier")


#Linear_D(train, train_labels, test, test_labels, labels=['N','S','V','F'])
print("SVM")
svm_model_poly(good_features_X, good_features_y,X_test , y_test, labels=[0,1,2,3])
print("XGboost")
xgboost(np.asarray(X_train_balanced[rank]), good_features_y, np.asarray(X_test[rank]), y_test, labels=[0,1,2,3])
#svm_model_poly(X_train_df[df[df['rfscore'] >= score]['features'].values], good_features_y,X_test_df[df[df['rfscore'] >= score]['features'].values] , y_test, labels=[0,1,2,3])[0]
print("Logistic")
logisticRegress(X_train_balanced[rank], good_features_y, X_test[rank], y_test, labels=[0,1,2,3])
print("Linear_D")
Linear_D(X_train_balanced[rank], good_features_y, X_test[rank], y_test,  labels=[0,1,2,3])
#ada(X_train_df[rank['features'].values], good_features_y, X_test_df[rank['features'].values], y_test,  labels=[0,1,2,3])
print("SVM_LN")
svm_model_linear(np.asarray(X_train_balanced[rank]), good_features_y, np.asarray(X_test[rank]), y_test,  labels=[0,1,2,3])
print("voting_ensemble")
voting_ensemble(np.asarray(X_train_balanced[rank]), good_features_y,np.asarray( X_test[rank]), y_test,  labels=[0,1,2,3])
print("ada")

#ada(np.asarray(X_train_balanced[n_s]), good_features_y,np.asarray( X_test[n_s]), y_test,  labels=[0,1,2,3])


#print("voting_ensemble")

#voting_ensemble(good_features_X, good_features_y,np.asarray(X_test) , y_test, labels=[0,1,2,3])

#feature_good = rank[rank['rfscore'] >= score]['features'].values

print("Linear_d all samples")
Linear_D(X_train[rank], y_train, X_test[rank], y_test, labels=[0,1,2,3])

n vs all results for various classifier
SVM
[[34986   635  3908  4492]
 [  502  1336   122    90]
 [  198    51  2525   446]
 [   26     0     7   355]]
              precision    recall  f1-score   support

           0       0.98      0.79      0.88     44021
           1       0.66      0.65      0.66      2050
           2       0.38      0.78      0.52      3220
           3       0.07      0.91      0.12       388

   micro avg       0.79      0.79      0.79     49679
   macro avg       0.52      0.79      0.54     49679
weighted avg       0.92      0.79      0.84     49679

[0.4007485524244452, 2.4813919785105343, 0.5105482735260394]
XGboost
[[32504  3265  5083  3169]
 [ 1605   356    65    24]
 [   98   100  2960    62]
 [   13     1   288    86]]
              precision    recall  f1-score   support

           0       0.95      0.74      0.83     44021
           1       0.10      0.17      0.12      2050
           2       0.35      0.92      0.51      3220
           3     

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[27124  6324  3569  7004]
 [ 1548   366    47    89]
 [   56   367  2639   158]
 [   10     6    17   355]]
              precision    recall  f1-score   support

           0       0.94      0.62      0.75     44021
           1       0.05      0.18      0.08      2050
           2       0.42      0.82      0.56      3220
           3       0.05      0.91      0.09       388

   micro avg       0.61      0.61      0.61     49679
   macro avg       0.37      0.63      0.37     49679
weighted avg       0.87      0.61      0.70     49679

[0.18168090715241353, 1.4706800715522876, 0.2746754625202427]
Linear_D


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[23977  9263  2018  8763]
 [ 1529   429    26    66]
 [  180   422  2374   244]
 [   11    10    11   356]]
              precision    recall  f1-score   support

           0       0.93      0.54      0.69     44021
           1       0.04      0.21      0.07      2050
           2       0.54      0.74      0.62      3220
           3       0.04      0.92      0.07       388

   micro avg       0.55      0.55      0.55     49679
   macro avg       0.39      0.60      0.36     49679
weighted avg       0.86      0.55      0.65     49679

[0.13728121179103422, 1.5249225728776072, 0.25925592750521803]
SVM_LN
[[30477  4400  3510  5634]
 [ 1629   282    65    74]
 [  189   492  2362   177]
 [   12     5    21   350]]
              precision    recall  f1-score   support

           0       0.94      0.69      0.80     44021
           1       0.05      0.14      0.08      2050
           2       0.40      0.73      0.51      3220
           3       0.06      0.90      0.11       388

   mi

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[30411  4603  3434  5573]
 [ 1606   336    49    59]
 [   81   312  2682   145]
 [   12     4    23   349]]
              precision    recall  f1-score   support

           0       0.95      0.69      0.80     44021
           1       0.06      0.16      0.09      2050
           2       0.43      0.83      0.57      3220
           3       0.06      0.90      0.11       388

   micro avg       0.68      0.68      0.68     49679
   macro avg       0.38      0.65      0.39     49679
weighted avg       0.87      0.68      0.75     49679

[0.2266152750072726, 1.4941803209512923, 0.30008017762254785]
ada
Linear_d all samples
[[38038   211  2301  3471]
 [ 1946    45    12    47]
 [  543   157  2283   237]
 [   20     3    16   349]]
              precision    recall  f1-score   support

           0       0.94      0.86      0.90     44021
           1       0.11      0.02      0.04      2050
           2       0.50      0.71      0.58      3220
           3       0.09      0.90      0.16

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


(LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
               solver='svd', store_covariance=False, tol=0.0001),
 array([0, 0, 0, ..., 0, 0, 0]),
 0.33233512079670813)

In [78]:
logisticRegress(X_train[rank[0:20]], y_train, X_test[rank[0:20]], y_test, labels=[0,1,2,3])

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[34058  2055  4191  3717]
 [ 1702   246    51    51]
 [  321   160  2586   153]
 [   18     3    28   339]]
              precision    recall  f1-score   support

           0       0.94      0.77      0.85     44021
           1       0.10      0.12      0.11      2050
           2       0.38      0.80      0.51      3220
           3       0.08      0.87      0.15       388

   micro avg       0.75      0.75      0.75     49679
   macro avg       0.38      0.64      0.40     49679
weighted avg       0.87      0.75      0.79     49679

[0.272441688453433, 1.4001311170438815, 0.3112372338572017]


(LogisticRegression(C=100, class_weight='balanced', dual=False,
           fit_intercept=True, intercept_scaling=10, max_iter=100,
           multi_class='warn', n_jobs=None, penalty='l2', random_state=None,
           solver='warn', tol=0.0001, verbose=0, warm_start=False),
 array([0, 0, 0, ..., 0, 0, 0]),
 0.3112372338572017)

In [ ]:

all_features

1        261     dtw1    0.179
2        246     RT_int_V        0.000
3        93      T_neg_amp6      0.012
4        82      T_amp9          0.009
5        3       R_amp0          0.012
6        133     R_amp0_V        0.009
7        31      S_amp0          0.003
8        94      T_neg_amp7      0.006
9        262     dtw2    0.015
10       81      T_amp8          0.005
11       92      T_neg_amp5      0.003
12       129     P_neg_T         0.003
13       73      T_amp0          0.004
14       88      T_neg_amp1      0.004
15       99      rr_int_pre      0.003
16       91      T_neg_amp4      0.004
17       80      T_amp7          0.005
18       87      T_neg_amp0      0.003
19       74      T_amp1          0.003
20       23      Q_amp6          0.003


rank20_all = ['dtw1',
     'RT_int_V',
     'T_neg_amp6',
     'T_amp9',
     'R_amp0',
     'R_amp0_V',
     'S_amp0',
     'T_neg_amp7',
     'dtw2',
     'T_amp8',
     'T_neg_amp5',
     'P_neg_T',
     'T_amp0',
     'T_neg_amp1',
     'rr_int_pre',
     'T_neg_amp4',
     'T_amp7',
     'T_neg_amp0',
     'T_amp1',
     'Q_amp6']


['dtw1',
 'PT_int_10_V',
 'R_amp0_V',
 'T_amp6',
 'T_neg_amp6',
 'R_amp0',
 'P_neg_T',
 'dtw2',
 'T_amp7',
 'T_neg_amp4',
 'T_neg_amp1',
 'T_amp4',
 'rr_int_post_V',
 'T_neg_amp7',
 'T_amp5',
 'S_amp0',
 'T_neg_amp5',
 'T_amp8',
 'T_neg_amp2',
 'T_prominence',
 'T_neg_amp9',
 'T_amp3',
 'T_neg_amp3',
 'R_amp5_V',
 'T_amp9',
 'neg_P_neg_T',
 'T_neg_amp0',
 'T_amp2',
 'T_neg_amp8',
 'Q_amp3',
 'T_amp1',
 'PT_int',
 'T_amp0',
 'R_prominence_V',
 'S_amp1',
 'T_neg_prominence',
 'T_height',
 'T_neg_height',
 'Q_amp9',
 'R_amp1',
 'rr_int_pre',
 'T_amp6_V',
 'R_amp1_V',
 'Q_amp0',
 'neg_PT',
 'S_amp9_V',
 'Q_amp9_V',
 'Q_amp1',
 'T_amp5_V',
 'P_amp6']



*** mRMR features ***
Order    Fea     Name    Score
1        261     dtw1    0.187
2        250     PT_int_10_V     0.000
3        133     R_amp0_V        0.012
4        79      T_amp6          0.012
5        93      T_neg_amp6      0.017
6        3       R_amp0          0.010
7        129     P_neg_T         0.005
8        262     dtw2    0.020
9        80      T_amp7          0.005
10       91      T_neg_amp4      0.007
11       88      T_neg_amp1      0.003
12       77      T_amp4          0.004
13       230     rr_int_post_V   0.003
14       94      T_neg_amp7      0.004
15       78      T_amp5          0.004
16       31      S_amp0          0.004
17       92      T_neg_amp5      0.005
18       81      T_amp8          0.004
19       89      T_neg_amp2      0.004
20       83      T_prominence    0.003
21       96      T_neg_amp9      0.003
22       76      T_amp3          0.004
23       90      T_neg_amp3      0.003
24       138     R_amp5_V        0.003
25       82      T_amp9          0.003
26       130     neg_P_neg_T     0.003
27       87      T_neg_amp0      0.004
28       75      T_amp2          0.003
29       95      T_neg_amp8      0.003
30       20      Q_amp3          0.003
31       74      T_amp1          0.003
32       119     PT_int          0.003
33       73      T_amp0          0.002
34       143     R_prominence_V          0.003
35       32      S_amp1          0.002
36       97      T_neg_prominence        0.002
37       72      T_height        0.002
38       86      T_neg_height    0.002
39       26      Q_amp9          0.002
40       4       R_amp1          0.002
41       99      rr_int_pre      0.002
42       209     T_amp6_V        0.001
43       134     R_amp1_V        0.002
44       17      Q_amp0          0.001
45       128     neg_PT          0.001
46       170     S_amp9_V        0.001
47       156     Q_amp9_V        0.001
48       18      Q_amp1          0.001
49       208     T_amp5_V        0.001
50       51      P_amp6          0.001


[[37065   240  3199  3517]
 [ 1568   230   220    32]
 [  418   263  2301   238]
 [   65     0    24   299]]
              precision    recall  f1-score   support

           0       0.95      0.84      0.89     44021
           1       0.31      0.11      0.17      2050
           2       0.40      0.71      0.51      3220
           3       0.07      0.77      0.13       388

   micro avg       0.80      0.80      0.80     49679
   macro avg       0.43      0.61      0.43     49679
weighted avg       0.88      0.80      0.83     49679

[0.3291050051577591, 1.5411623076989205, 0.3571977910412446]



n_f

['dtw1',
 'QRS_int_50_V',
 'R_amp0_V',
 'PQ_int_V',
 'neg_ST_V',
 'neg_RT_V',
 'PQ_int_10_V',
 'T_amp6',
 'T_neg_durations_V',
 'PR_int_50_V',
 'QRS_int_10_V',
 'QRS_int_V',
 'T_neg_areas_V',
 'PQ_int_50_V',
 'TR_V',
 'R_amp0',
 'PR_int_V',
 'S_amp0',
 'PT_int_10_V',
 'RT_int_10_V',
 'neg_PR_V',
 'RP_V',
 'T_amp8',
 'T_amp6_V',
 'PT_int_50_V',
 'PR_int_10_V',
 'R_amp1_V',
 'RT_int_50_V',
 'neg_RQ_V',
 'RT_int_V',
 'ST_int_50_V',
 'ST_int_V',
 'T_amp7',
 'ST_int_10_V',
 'R_duration',
 'T_areas_V',
 'QRS_int',
 'QRS_int_10',
 'T_areas',
 'T_neg_durations',
 'T_neg_areas',
 'dtw2',
 'P_neg_areas',
 'P_neg_prominence',
 'QRS_int_50',
 'PQ_int',
 'PQ_int_10',
 'T_duration',
 'T_amp4',
 'PR_int']


Order    Fea     Name    Score
1        261     dtw1    0.025
2        236     QRS_int_50_V    -0.000
3        133     R_amp0_V        0.001
4        237     PQ_int_V        -0.000
5        256     neg_ST_V        -0.000
6        257     neg_RT_V        -0.000
7        238     PQ_int_10_V     -0.000
8        79      T_amp6          0.000
9        215     T_neg_durations_V       -0.000
10       242     PR_int_50_V     -0.000
11       235     QRS_int_10_V    -0.000
12       234     QRS_int_V       -0.000
13       228     T_neg_areas_V   -0.000
14       239     PQ_int_50_V     -0.000
15       253     TR_V    -0.000
16       3       R_amp0          0.000
17       240     PR_int_V        -0.000
18       31      S_amp0          0.000
19       250     PT_int_10_V     -0.000
20       247     RT_int_10_V     -0.000
21       255     neg_PR_V        -0.000
22       252     RP_V    -0.000
23       81      T_amp8          0.000
24       209     T_amp6_V        0.000
25       251     PT_int_50_V     -0.000
26       241     PR_int_10_V     -0.000
27       134     R_amp1_V        0.000
28       248     RT_int_50_V     -0.000
29       254     neg_RQ_V        -0.000
30       246     RT_int_V        -0.000
31       245     ST_int_50_V     -0.000
32       243     ST_int_V        -0.000
33       80      T_amp7          0.000
34       244     ST_int_10_V     -0.000
35       1       R_duration      -0.000
36       214     T_areas_V       -0.000
37       104     QRS_int         -0.000
38       105     QRS_int_10      -0.000
39       84      T_areas         -0.000
40       85      T_neg_durations         -0.000
41       98      T_neg_areas     -0.000
42       262     dtw2    0.000
43       70      P_neg_areas     -0.000
44       69      P_neg_prominence        -0.000
45       106     QRS_int_50      -0.000
46       107     PQ_int          -0.000
47       108     PQ_int_10       -0.000
48       71      T_duration      -0.000
49       77      T_amp4          0.000
50       110     PR_int          -0.000


In [ ]:
n_s

['dtw1',
 'RT_int_V',
 'neg_ST',
 'PT_int',
 'TR_V',
 'PQ_int',
 'Q_amp3',
 'ST_int_V',
 'neg_RT',
 'neg_PT_V',
 'neg_PR',
 'RP',
 'QRS_int_50_V',
 'PR_int',
 'PQ_int_V',
 'PQ_int_10_V',
 'QRS_int_V',
 'PQ_int_50_V',
 'RP_V',
 'PR_int_V',
 'R_amp8',
 'PR_int_10_V',
 'ST_int_10_V',
 'QRS_int_10_V',
 'rr_int_pre',
 'neg_RT_V',
 'neg_PR_V',
 'PT_int_50_V',
 'RT_int_50_V',
 'Q_amp2',
 'neg_RQ_V',
 'ST_int_50_V',
 'PT_int_10_V',
 'RT_int_10_V',
 'neg_ST_V',
 'T_neg_areas_V',
 'PR_int_50_V',
 'PT_int_V',
 'R_duration',
 'T_neg_areas',
 'QRS_int_10',
 'Q_amp9',
 'T_areas',
 'T_neg_durations',
 'P_neg_areas',
 'QRS_int',
 'P_neg_height',
 'S_amp4_V',
 'QRS_int_50',
 'PQ_int_10']



*** mRMR features ***
Order    Fea     Name    Score
1        261     dtw1    0.013
2        246     RT_int_V        0.000
3        126     neg_ST          0.000
4        119     PT_int          0.000
5        253     TR_V    0.000
6        107     PQ_int          0.000
7        20      Q_amp3          0.000
8        243     ST_int_V        0.000
9        127     neg_RT          0.000
10       258     neg_PT_V        0.000
11       125     neg_PR          0.000
12       122     RP      0.000
13       236     QRS_int_50_V    0.000
14       110     PR_int          0.000
15       237     PQ_int_V        0.000
16       238     PQ_int_10_V     0.000
17       234     QRS_int_V       0.000
18       239     PQ_int_50_V     0.000
19       252     RP_V    0.000
20       240     PR_int_V        0.000
21       11      R_amp8          0.000
22       241     PR_int_10_V     0.000
23       244     ST_int_10_V     0.000
24       235     QRS_int_10_V    0.000
25       99      rr_int_pre      0.000
26       257     neg_RT_V        0.000
27       255     neg_PR_V        0.000
28       251     PT_int_50_V     0.000
29       248     RT_int_50_V     0.000
30       19      Q_amp2          0.000
31       254     neg_RQ_V        0.000
32       245     ST_int_50_V     0.000
33       250     PT_int_10_V     0.000
34       247     RT_int_10_V     0.000
35       256     neg_ST_V        0.000
36       228     T_neg_areas_V   0.000
37       242     PR_int_50_V     0.000
38       249     PT_int_V        0.000
39       1       R_duration      0.000
40       98      T_neg_areas     0.000
41       105     QRS_int_10      0.000
42       26      Q_amp9          0.000
43       84      T_areas         0.000
44       85      T_neg_durations         0.000
45       70      P_neg_areas     0.000
46       104     QRS_int         0.000
47       58      P_neg_height    0.000
48       165     S_amp4_V        0.000
49       106     QRS_int_50      0.000
50       108     PQ_int_10       0.000


n_v

['dtw1',
 'T_neg_durations_V',
 'T_neg_amp6',
 'T_amp6',
 'R_amp0_V',
 'T_neg_amp1',
 'T_amp7',
 'dtw2',
 'P_neg_T',
 'T_neg_amp4',
 'T_amp4',
 'T_neg_amp7',
 'T_amp8',
 'neg_P_neg_T',
 'T_neg_amp5',
 'T_amp5',
 'R_amp0',
 'S_amp0',
 'T_neg_amp2',
 'rr_int_post_V',
 'T_amp3',
 'T_neg_amp3',
 'T_prominence',
 'T_neg_amp9',
 'T_amp9',
 'T_neg_amp0',
 'T_amp2',
 'T_neg_amp8',
 'PT_int',
 'T_amp1',
 'R_prominence_V',
 'T_height',
 'T_amp0',
 'T_neg_height',
 'Q_amp1',
 'T_neg_prominence',
 'S_amp1',
 'Q_amp0',
 'Q_amp9_V',
 'R_amp5_V',
 'T_amp6_V',
 'neg_PT',
 'S_amp9_V',
 'P_amp6',
 'T_amp5_V',
 'P_amp8',
 'Q_amp2',
 'T_amp3_V',
 'R_amp1',
 'P_amp3']

*** mRMR features ***
Order    Fea     Name    Score
1        261     dtw1    0.164
2        215     T_neg_durations_V       -0.000
3        93      T_neg_amp6      0.012
4        79      T_amp6          0.011
5        133     R_amp0_V        0.010
6        88      T_neg_amp1      0.005
7        80      T_amp7          0.007
8        262     dtw2    0.024
9        129     P_neg_T         0.005
10       91      T_neg_amp4      0.005
11       77      T_amp4          0.006
12       94      T_neg_amp7      0.004
13       81      T_amp8          0.004
14       130     neg_P_neg_T     0.003
15       92      T_neg_amp5      0.005
16       78      T_amp5          0.004
17       3       R_amp0          0.005
18       31      S_amp0          0.003
19       89      T_neg_amp2      0.004
20       230     rr_int_post_V   0.003
21       76      T_amp3          0.003
22       90      T_neg_amp3      0.004
23       83      T_prominence    0.003
24       96      T_neg_amp9      0.004
25       82      T_amp9          0.003
26       87      T_neg_amp0      0.003
27       75      T_amp2          0.003
28       95      T_neg_amp8      0.003
29       119     PT_int          0.003
30       74      T_amp1          0.003
31       143     R_prominence_V          0.003
32       72      T_height        0.002
33       73      T_amp0          0.002
34       86      T_neg_height    0.002
35       18      Q_amp1          0.002
36       97      T_neg_prominence        0.002
37       32      S_amp1          0.002
38       17      Q_amp0          0.001
39       156     Q_amp9_V        0.001
40       138     R_amp5_V        0.002
41       209     T_amp6_V        0.001
42       128     neg_PT          0.001
43       170     S_amp9_V        0.001
44       51      P_amp6          0.001
45       208     T_amp5_V        0.001
46       53      P_amp8          0.001
47       19      Q_amp2          0.001
48       206     T_amp3_V        0.001
49       4       R_amp1          0.001
50       48      P_amp3          0.001

In [17]:
from sklearn import svm

## small C from 1 to 3 seems to be good for f class recalled
## degree 3 is better all around
## Tol at 0.01 seems best

def svm_model_poly(X_train, y_train, X_test, y_test, C=10, kernel='poly', degree=3, gamma='auto', 
                        coef0=0.001, shrinking=True, probability=True, tol=0.01, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None, labels = [0,1,2,3]):
    
    svm_model_linear = svm.SVC(C=C, kernel=kernel, degree=degree, gamma=gamma, 
                        coef0=coef0, shrinking=shrinking, probability=probability, tol=tol, 
                        cache_size=cache_size, verbose=verbose, 
                        max_iter=max_iter, decision_function_shape='ovo', random_state=random_state) 
    
    svm_model_linear.fit(X_train, y_train)
    y_pred = svm_model_linear.predict(X_test)    
    print(confusion_matrix(y_test,y_pred, labels=labels))  
    print(classification_report(y_test,y_pred))
    print(metric.get_metrics(y_pred,y_test,lb=labels))
    
    return svm_model_linear,y_pred, metric.get_metrics(y_pred,y_test, lb=labels)[2]


from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

def Linear_D(X_train, y_train, X_test, y_test, labels = [0,1,2,3]):
    clf = LinearDiscriminantAnalysis()
    clf.fit(X_train, y_train)  
    y_pred = clf.predict(X_test)
    print(confusion_matrix(y_test,y_pred, labels = labels))  
    print(classification_report(y_test,y_pred, labels=labels))
    print(metric.get_metrics(y_pred,y_test, lb=labels))
    
    return clf,y_pred, metric.get_metrics(y_pred,y_test,lb=labels)[2]

from sklearn.ensemble import RandomForestClassifier

## Number of feature at 50 or 100 is good too
## numner of estimators leaves at 1000 

def randomForest(X_train, y_train, X_test, y_test,n_estimators=1000, criterion='gini', max_depth=16, min_samples_split=2, min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, max_features=50, max_leaf_nodes=None, class_weight='balanced', labels = [0,1,2,3]):
    
    rf = RandomForestClassifier(n_estimators=n_estimators, criterion=criterion, max_depth=max_depth, min_samples_split=min_samples_split, min_samples_leaf=min_samples_leaf,min_weight_fraction_leaf=min_weight_fraction_leaf, class_weight=class_weight, min_impurity_decrease=min_impurity_decrease,max_features=max_features)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)    
    print(confusion_matrix(y_test,y_pred, labels=labels))  
    print(classification_report(y_test,y_pred, labels=labels))
    print(metric.get_metrics(y_pred,y_test, lb=labels))
    
    return rf, y_pred, metric.get_metrics(y_pred,y_test, lb=labels)[2]


### xgbo is good for normal classes too
## do this one next 
## XGB is very goos for V class
## XGboost tree classifcation is good with 5 or more tree depth
from xgboost import XGBClassifier


def xgboost(X_train,y_train, X_test, y_test, max_depth = 8, eta = 1, gamma = 0.001, min_child_weight=0.1,max_delta_step=10, subsample=0.6,colsample_bytree = 0.7, colsample_bylevel= 1, colsample_bynode=1, alpha=0, reg_lambda= 1, tree_method='exact', grow_policy='depthwise', refresh_leaf=True, process_type='default', predictor= 'cpu_predictor', labels = [0,1,2,3]): 
    model = XGBClassifier(max_depth = max_depth, eta = eta, gamma = gamma,min_child_weight=min_child_weight,subsample=subsample, max_delta_step= max_delta_step,colsample_bytree=colsample_bytree,colsample_bylevel=colsample_bylevel,colsample_bynode=colsample_bynode,alpha=alpha,reg_lambda=reg_lambda,grow_policy=grow_policy, tree_method=tree_method,refresh_leaf=refresh_leaf,process_type=process_type, predictor= predictor,objective = 'reg:logistic')
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return model, y_pred,metric.get_metrics(y_pred,y_test, lb=labels)[2]



from sklearn.linear_model import LogisticRegression
## L1 one is good , l2 would be used
## very good at f class recall
## solver = ['newton-cg', 'lbfgs', 'liblinear'are all good, ensemble with all would be good

## false dual is better
def logisticRegress(X_train, y_train, X_test, y_test, penalty='l2', dual=False, tol=0.0001, C=100, fit_intercept=True, intercept_scaling=10, class_weight='balanced', random_state=None, solver='warn', max_iter=100, multi_class='warn', verbose=0, warm_start=False, n_jobs=None, labels = [0,1,2,3]):
    lr = LogisticRegression(penalty=penalty, dual=dual, tol=tol, C=C, fit_intercept=fit_intercept, intercept_scaling=intercept_scaling, class_weight=class_weight, random_state=random_state, solver=solver, max_iter=max_iter, multi_class=multi_class, verbose=verbose, warm_start=warm_start, n_jobs=n_jobs)
        # dual=dual, tol=tol, C=C, fit_intercept=fit_intercept, intercept_scaling=1, class_weight=None, random_state=None, solver=’warn’, max_iter=100, multi_class=’warn’, verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
    lr.fit(X_train, y_train.ravel())  
    y_pred = lr.predict(X_test)
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return lr,y_pred, metric.get_metrics(y_pred,y_test, lb=labels)[2]



from sklearn.ensemble import AdaBoostClassifier

from sklearn import svm

def ada(X_train, y_train, X_test, y_test,labels = [0,1,2,3]):

    svm_model_poly = svm.SVC(C=10,  kernel='linear', degree=3, gamma='auto', 
                        coef0=0.0, shrinking=True, probability=True, tol=0.1, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None)

    ada = AdaBoostClassifier(base_estimator=svm_model_poly, n_estimators=50 )
    ada.fit(X_train, y_train)  
    y_pred = ada.predict(X_test)
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return ada, y_pred, metric.get_metrics(y_pred,y_test, lb=labels)[2]


from sklearn import svm

## Number of feature at 50 or 100 is good too


def svm_model_linear(X_train, y_train, X_test, y_test, C=10, kernel='linear', degree=3, gamma='auto', 
                        coef0=0.0, shrinking=True, probability=True, tol=0.1, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None, labels = [0,1,2,3] ):
    
    svm_model_linear = svm.SVC(C=C, kernel=kernel, degree=degree, gamma=gamma, 
                        coef0=coef0, shrinking=shrinking, probability=probability, tol=tol, 
                        cache_size=cache_size, verbose=verbose, 
                        max_iter=max_iter, decision_function_shape=decision_function_shape, random_state=random_state) 
    
    svm_model_linear.fit(X_train, y_train)
    y_pred = svm_model_linear.predict(X_test)    
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return svm_model_linear, y_pred, metric.get_metrics(y_pred,y_test, lb=labels)[2]






In [18]:
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import VotingClassifier
import time
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm



def voting_ensemble(X_train, y_train, X_test,y_test, labels=[0,1,2,3]):
    svm_model_linear = svm.SVC(C=10, kernel='linear', degree=3, gamma='auto', 
                            coef0=0.0, shrinking=True, probability=True, tol=0.1, 
                            cache_size=200, verbose=False, 
                            max_iter=-1, decision_function_shape='ovo', random_state=None)

    svm_model_poly = svm.SVC(C=10, kernel='poly', degree=3, gamma='auto', 
                            coef0=0.001, shrinking=True, probability=True, tol=0.01, 
                            cache_size=200, verbose=False, 
                            max_iter=-1, decision_function_shape='ovo', random_state=None)


    rf = RandomForestClassifier(n_estimators=1000, criterion='gini', max_depth=16, min_samples_split=2, 
                                min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, 
                                max_features=50, max_leaf_nodes=None, class_weight='balanced')


    lr = LogisticRegression( penalty='l2', dual=False, tol=0.0001, C=100, fit_intercept=True, intercept_scaling=10, 
                            class_weight='balanced', random_state=None, solver='warn', max_iter=100, multi_class='warn',
                            verbose=0, warm_start=False, n_jobs=None)


    xgb = XGBClassifier(max_depth = 8, eta = 1, gamma = 0.001, min_child_weight=0.1,max_delta_step=10, 
                        subsample=0.6,colsample_bytree = 0.7, colsample_bylevel= 1, colsample_bynode=1, alpha=0, 
                        reg_lambda= 1, tree_method='exact', grow_policy='depthwise', refresh_leaf=True, 
                        process_type='default', predictor= 'cpu_predictor',objective = 'reg:logistic')




    eclf = VotingClassifier(estimators=[ ('xgb',xgb), ('lr',lr), ('svm_ln',svm_model_linear)], voting='hard')#, weights=[2,2,2,2])



    #clf1 = clf1.fit(X, y)
    #clf2 = clf2.fit(X, y)
    #clf3 = clf3.fit(X, y)
    eclf = eclf.fit(X_train, y_train)

    predict = eclf.predict(X_test)
    #scores = cross_val_score(X_train, y_train.data, iris.target, cv=10)
    #scores.mean()                             

    print(confusion_matrix(y_test,predict, labels=labels))  
    print(classification_report(y_test,predict, labels=labels))
    print(metric.get_metrics(predict.ravel(),y_test.ravel(),lb=labels))
    
    return eclf, predict, metric.get_metrics(predict.ravel(),y_test.ravel(), lb=labels)[2]