In [1]:
from codes.python import metric
import numpy as np
from scipy import signal
import scipy
from numpy import array
import os
import matplotlib.pyplot as plt
import wfdb
from wfdb import processing, plot
from sklearn.decomposition import PCA
from sklearn import svm
from sklearn.preprocessing import normalize
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import pandas as pd
import pywt
from biosppy.signals import ecg
from sklearn import metrics
from codes.python import ecg_waveform_extractor as waveform
import time as system_time
from scipy import stats
import warnings
import termcolor as colored
from math import*
import pandas as pd
from sklearn.decomposition import PCA, FastICA
from mpl_toolkits.mplot3d import axes3d, Axes3D
from codes.python import post_process_features_ex as post_features

from collections import Counter
from keras.callbacks import LearningRateScheduler
from keras.layers import Dense, Dropout, Activation
from keras.models import Sequential
from keras.optimizers import SGD, RMSprop, Adam, Adagrad, Adadelta, Adamax, Nadam
from keras import backend as K
from keras.utils.generic_utils import get_custom_objects
from sklearn.metrics import classification_report, confusion_matrix 

from LossHistory import *
import time
from easyesn import ClassificationESN
from easyesn import OneHotEncoder
from easyesn.optimizers import GridSearchOptimizer
from easyesn import helper as hlp
from easyesn import RegressionESN

C:\Users\nimch681\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Using Numpy backend.


In [14]:
## clinically 
X_train = np_clinic_1
X_test = np_clinic_2
y_train = np_class_ID_1
y_test = np_class_ID_2



In [183]:
#non clinically
X_train = np_non_var_1
X_test = np_non_var_2
y_train = np_class_ID_1
y_test = np_class_ID_2

In [39]:
X_train = post_features.normalised_values_multiples(np_variables_1)
X_test = post_features.normalised_values_multiples(np_variables_2)

#norm_var_1_V1 = post_features.normalised_values_multiples(np_V1_1)
#norm_var_2_V2 = post_features.normalised_values_multiples(np_V1_2)

done norm
row 0 done
done norm
row 1 done
done norm
row 2 done
done norm
row 3 done
done norm
row 4 done
done norm
row 5 done
done norm
row 6 done
done norm
row 7 done
done norm
row 8 done
done norm
row 9 done
done norm
row 10 done
done norm
row 11 done
done norm
row 12 done
done norm
row 13 done
done norm
row 14 done
done norm
row 15 done
done norm
row 16 done
done norm
row 17 done
done norm
row 18 done
done norm
row 19 done
done norm
row 20 done
done norm
row 21 done
done norm
row 22 done
done norm
row 23 done
done norm
row 24 done
done norm
row 25 done
done norm
row 26 done
done norm
row 27 done
done norm
row 28 done
done norm
row 29 done
done norm
row 30 done
done norm
row 31 done
done norm
row 32 done
done norm
row 33 done
done norm
row 34 done
done norm
row 35 done
done norm
row 36 done
done norm
row 37 done
done norm
row 38 done
done norm
row 39 done
done norm
row 40 done
done norm
row 41 done
done norm
row 42 done
done norm
row 43 done
done norm
row 44 done
done norm
row 45 don

In [ ]:
#X_train = post_features.normalised_values_multiples(np_V1_1)
#X_test = post_features.normalised_values_multiples(np_V1_2)

In [7]:
bin_labels = y_train.copy()
bin_labels[y_train != 0]=1
bin_labels[y_train == 0]=0
bin_labels=np.array(bin_labels, dtype=int)

bin_labels_test = y_test.copy()
bin_labels_test[y_test != 0]=1
bin_labels_test[y_test == 0]=0
bin_labels_test=np.array(bin_labels_test, dtype=int)

In [8]:
class_weights = {}
for c in range(0,2):
    class_weights.update({c:len(bin_labels) / float(np.count_nonzero(bin_labels == c))})

In [160]:
class_weights

{0: 1.1130345565281932, 1: 9.846852066434916}

In [10]:
input_size=X_train.shape[1]
# Establish the NN
eps=150
opt=RMSprop(lr=0.001)
print (input_size)
X_train.shape

360


(50987, 360)

In [12]:
history=model.fit(X_train, bin_labels, class_weight=class_weights, epochs=eps, callbacks=cb)
y_pred=model.predict(X_test)
# binary classification based on probability.
y_pred[y_pred <= 0.5] = 0
y_pred[y_pred > 0.5] = 1
y_pred=y_pred.astype(int)

Epoch 1/150
50987/50987 [==============================] - 5s 108us/step - loss: 0.3207 - acc: 0.9653
Epoch 2/150
50987/50987 [==============================] - 4s 78us/step - loss: 0.2318 - acc: 0.9782
Epoch 3/150
50987/50987 [==============================] - 4s 78us/step - loss: 0.1976 - acc: 0.9825
Epoch 4/150
50987/50987 [==============================] - 4s 77us/step - loss: 0.1935 - acc: 0.9838
Epoch 5/150
50987/50987 [==============================] - 4s 77us/step - loss: 0.1797 - acc: 0.9863
Epoch 6/150
50987/50987 [==============================] - 4s 77us/step - loss: 0.1709 - acc: 0.9874
Epoch 7/150
50987/50987 [==============================] - 4s 77us/step - loss: 0.1738 - acc: 0.9871
Epoch 8/150
50987/50987 [==============================] - 4s 77us/step - loss: 0.1693 - acc: 0.9883
Epoch 9/150
50987/50987 [==============================] - 4s 77us/step - loss: 0.1556 - acc: 0.9889
Epoch 10/150
50987/50987 [==============================] - 4s 77us/step - loss: 0.1525 - 

In [19]:

esn = RegressionESN(n_input=1, n_output=1, n_reservoir=50, leakingRate=0.2, regressionParameters=[1e-2], solver="lsqr")

In [20]:
esn.fit(X_train, bin_labels, transientTime=100, verbose=1)



100% (50987 of 50987) |##################| Elapsed Time: 0:07:40 Time:  0:07:40


0.3020626090306063

In [21]:
y_pred = esn.predict(X_test, transientTime=100, verbose=1)
y_pred[y_pred <= 0.5] = 0
y_pred[y_pred > 0.5] = 1
y_pred=y_pred.astype(int)


100% (49679 of 49679) |##################| Elapsed Time: 0:08:13 Time:  0:08:13


In [22]:
print(confusion_matrix(bin_labels_test,y_pred))  
print(classification_report(bin_labels_test,y_pred)) 

[[43968    53]
 [ 5085   573]]
              precision    recall  f1-score   support

           0       0.90      1.00      0.94     44021
           1       0.92      0.10      0.18      5658

    accuracy                           0.90     49679
   macro avg       0.91      0.55      0.56     49679
weighted avg       0.90      0.90      0.86     49679



In [111]:
bin_labels = bin_labels.reshape(bin_labels.shape[0],1)
bin_labels = bin_labels.reshape(bin_labels.shape[0],1)



X_train_binary = np_clinic_1
X_test_binary = np_clinic_2
y_train = np_class_ID_1
y_test = np_class_ID_2



In [132]:
abnormal_train_ind = np.where(np_class_ID_1 != 0)[0]
abnormal_data = X_train_binary[abnormal_train_ind]
abnormal_labels = y_train[abnormal_train_ind]

In [15]:
C_value = 10
use_probability = True
multi_mode = 'ovo'
svm_model = svm.SVC(C=C_value, kernel='linear', degree=3, gamma='auto', 
                    coef0=0.0, shrinking=True, probability=use_probability, tol=0.001, 
                    cache_size=200, verbose=False, 
                    max_iter=-1, decision_function_shape=multi_mode, random_state=None)

In [16]:
start = time.time()
svm_model.fit(X_train, y_train)
end = time.time()
print(end-start)

1915.4335327148438


In [17]:
#abnormal_test_ind = np.where(y_pred == 1)[0]
# Train the abnormal on the SVM
pred_y = svm_model.predict(X_test)

# loop through each set of indices and insert approp value into labels copy
#predictions=np.zeros((test_labels.shape[0]), dtype=str)

In [137]:
y_test[abnormal_pred]

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
print(confusion_matrix(pred_y,y_test))  
print(classification_report(pred_y,y_test)) 

[[39872  1732   319    38]
 [  263   265    31     0]
 [ 1659    35  2659     7]
 [ 2227    18   211   343]]
              precision    recall  f1-score   support

           0       0.91      0.95      0.93     41961
           1       0.13      0.47      0.20       559
           2       0.83      0.61      0.70      4360
           3       0.88      0.12      0.22      2799

    accuracy                           0.87     49679
   macro avg       0.69      0.54      0.51     49679
weighted avg       0.89      0.87      0.86     49679



In [ ]:
#cinically important
[[35055  8966]
 [ 1622  4036]]
              precision    recall  f1-score   support

           0       0.96      0.80      0.87     44021
           1       0.31      0.71      0.43      5658

    accuracy                           0.79     49679
   macro avg       0.63      0.75      0.65     49679
weighted avg       0.88      0.79      0.82     49679

#clinicall non
[[25825 18196]
 [ 1881  3777]]
              precision    recall  f1-score   support

           0       0.93      0.59      0.72     44021
           1       0.17      0.67      0.27      5658

    accuracy                           0.60     49679
   macro avg       0.55      0.63      0.50     49679
weighted avg       0.85      0.60      0.67     49679

##normalised
[[30485 13536]
 [ 1391  4267]]
              precision    recall  f1-score   support

           0       0.96      0.69      0.80     44021
           1       0.24      0.75      0.36      5658

    accuracy                           0.70     49679
   macro avg       0.60      0.72      0.58     49679
weighted avg       0.87      0.70      0.75     49679

#pure signal
[[34274  9747]
 [ 2506  3152]]
              precision    recall  f1-score   support

           0       0.93      0.78      0.85     44021
           1       0.24      0.56      0.34      5658

    accuracy                           0.75     49679
   macro avg       0.59      0.67      0.59     49679
weighted avg       0.85      0.75      0.79     49679


#clicinally imp svm for all lables
[[39872  1732   319    38]
 [  263   265    31     0]
 [ 1659    35  2659     7]
 [ 2227    18   211   343]]
              precision    recall  f1-score   support

           0       0.91      0.95      0.93     41961
           1       0.13      0.47      0.20       559
           2       0.83      0.61      0.70      4360
           3       0.88      0.12      0.22      2799

    accuracy                           0.87     49679
   macro avg       0.69      0.54      0.51     49679
weighted avg       0.89      0.87      0.86     49679


In [3]:
#ls = [0,1,2,3]
ls = []
ls.extend(['N', 'L', 'R'])                    # N
ls.extend(['A', 'a', 'J', 'S', 'e', 'j'])     # SVEB 
ls.extend(['V', 'E'])                         # VEB
ls.extend(['F'])
#ls.extend([ 'P', '/', 'f', 'u'])
patient_l_1 = [101]
#patient_l_2 = [100]
patient_ls_1 = [101,106,108,109,112,114,115,116,118,119,122,124,201,203,205,207,208,209,215,220,223,230]
#patient_ls_2 = [100,103,105,111,113,117,121,123,200,202,210,212,213,214,219,221,222,228,231,232,233,234]

DB1_patients = pd.read_csv("DB1_patient_list.csv")
#DB1_patients = DB1_patients.drop([1872])
DB1_patients = DB1_patients[DB1_patients['2'].isin(ls)]
#DB1_patients = DB1_patients[DB1_patients['0'].isin(patient_l_1)]


DB2_patients = pd.read_csv("DB2_patient_list.csv")
#DB2_patients= DB2_patients.drop([18692, 31865])
DB2_patients = DB2_patients[DB2_patients['2'].isin(ls)]
#DB2_patients = DB2_patients[DB2_patients['0'].isin(patient_l_2)]


DB1 = pd.read_csv("DB1.csv")
#DB1 = DB1.drop([1872])
DB1 = DB1[DB1['class_beat'].isin(ls)]
#DB1 = DB1[DB1['patient'].isin(patient_l_1)]


DB2 = pd.read_csv("DB2.csv")
#DB2 = DB2.drop([18692, 31865])
DB2 = DB2[DB2['class_beat'].isin(ls)]
#DB2 = DB2[DB2['patient'].isin(patient_l_2)]

patients_ls_1 = DB1_patients.iloc[:,0]
patients_ls_2 = DB2_patients.iloc[:,0]

patients_ls_1_ID = DB1_patients.iloc[:,1]
patients_ls_2_ID = DB2_patients.iloc[:,1]

patients_ls_1_type = DB1_patients.iloc[:,2]
patients_ls_2_type = DB2_patients.iloc[:,2]

#patients_ls_1 = np.asarray(DB1_patients, dtype=int)
patients_ls_1 = [int(i) for i in patients_ls_1]
patients_ls_1 = np.asarray(patients_ls_1, dtype=int)
patients_ls_1 = patients_ls_1.reshape(patients_ls_1.shape[0],1)
#patients_ls_2 = np.asarray(DB2_patients, dtype=int)
patients_ls_2 = [int(i) for i in patients_ls_2]
patients_ls_2 = np.asarray(patients_ls_2, dtype=int)
patients_ls_2 = patients_ls_2.reshape(patients_ls_2.shape[0],1)

patients_ls_all = np.vstack((patients_ls_1,patients_ls_2))

#patients_ls_all = patients_ls_all.reshape(7980,1)

patients_ls_all = [int(i) for i in patients_ls_all]

patients_ls_2 = [int(i) for i in patients_ls_2]
patients_ls_1 = [int(i) for i in patients_ls_1]


DB1_non_cli = pd.read_csv("DB1_non_clinic.csv")
#DB1_non_cli = DB1_non_cli.drop([1872])
#DB1_non_cli = DB1_non_cli[DB1_non_cli['patient'].isin(patient_l_1)]


DB1_non_cli = DB1_non_cli[DB1_non_cli['y0'].isin(ls)]


DB2_non_cli = pd.read_csv("DB2_non_clinic.csv")
#DB2_non_cli= DB2_non_cli.drop([18692, 31865])
DB2_non_cli = DB2_non_cli[DB2_non_cli['y0'].isin(ls)]
#DB2_non_cli = DB2_non_cli[DB2_non_cli['patient'].isin(patient_l_2)]


DB1_V1 = pd.read_csv("DB1_V1.csv")
#DB1_V1 = DB1_V1.drop([1872])
DB1_V1 = DB1_V1[DB1_V1['class_beat'].isin(ls)]
#DB1_V1 = DB1_V1[DB1_V1['patient'].isin(patient_l_1)]



DB2_V1 = pd.read_csv("DB2_V1.csv")
#DB2_V1 = DB2_V1.drop([18692, 31865])
DB2_V1 = DB2_V1[DB2_V1['class_beat'].isin(ls)]
#DB2_V1 = DB2_V1[DB2_V1['patient'].isin(patient_l_2)]

ls = []
ls.extend(["['N']","['L']", "['R']"])                    # N
ls.extend(["['A']", "['a']", "['J']", "['S']",  "['e']", "['j']"])     # SVEB 
ls.extend(["['V']", "['E']"])                         # VEB
ls.extend(["['F']"])
#ls.extend([ "['P']","[ '/']"," ['f']", "['u']"])
DB1_dwt = pd.read_csv("DB1_DTW_MLII.csv")
#DB1_dwt = DB1_dwt.drop([1872])
DB1_dwt = DB1_dwt[DB1_dwt['beat_type'].isin(ls)]
#DB1_dwt = DB1_dwt[DB1_dwt['patient'].isin(patient_l_1)]


DB2_dwt = pd.read_csv("DB2_DTW_MLII.csv")
#DB2_dwt = DB2_dwt.drop([18692, 31865])
DB2_dwt = DB2_dwt[DB2_dwt['beat_type'].isin(ls)]
#DB2_dwt = DB2_dwt[DB2_dwt['patient'].isin(patient_l_2)]


DB1_dwt_V1 = pd.read_csv("DB1_DTW_V1.csv")
#DB1_dwt_V1 = DB1_dwt_V1.drop([1872])
DB1_dwt_V1 = DB1_dwt_V1[DB1_dwt_V1['beat_type'].isin(ls)]
#DB1_dwt_V1 = DB1_dwt_V1[DB1_dwt_V1['patient'].isin(patient_l_1)]



DB2_dwt_V1 = pd.read_csv("DB2_DTW_V1.csv")
#DB2_dwt_V1 = DB2_dwt_V1.drop([18692, 31865])
DB2_dwt_V1 = DB2_dwt_V1[DB2_dwt_V1['beat_type'].isin(ls)]
#DB2_dwt_V1 = DB2_dwt_V1[DB2_dwt_V1['patient'].isin(patient_l_2)]

 #list(DB1.columns.values)
variables_1 = DB1.iloc[:,0:130]
class_beat_1 = DB1_patients.iloc[:,2]
class_ID_1 = DB1_patients.iloc[:,1]

np_variables_1 = np.asarray(variables_1)
np_class_beat_1 = np.asarray(class_beat_1)
np_class_ID_1 = np.asarray(class_ID_1)

np_class_beat_1 = np_class_beat_1.reshape(np_class_beat_1.shape[0],1)
np_class_ID_1 = np_class_ID_1.reshape(np_class_ID_1.shape[0],1)

variables_2 = DB2.iloc[:,0:130]
class_beat_2 = DB2_patients.iloc[:,2]
class_ID_2 = DB2_patients.iloc[:,1]

np_variables_2 = np.asarray(variables_2)
np_class_beat_2 = np.asarray(class_beat_2)
np_class_ID_2 = np.asarray(class_ID_2)

np_class_beat_2 = np_class_beat_2.reshape(np_class_beat_2.shape[0],1)
np_class_ID_2 = np_class_ID_2.reshape(np_class_ID_2.shape[0],1)

DB_var_all = np.vstack((np_variables_1,np_variables_2))
DB_class_all = np.vstack((np_class_ID_1,np_class_ID_2))
DB_type_all = np.vstack((np_class_beat_1,np_class_beat_2))

np_class_beat_1 = [str(i) for i in np_class_beat_1]
np_class_ID_1 = [int(i) for i in np_class_ID_1]

np_class_beat_1 = np.asarray(np_class_beat_1)
np_class_ID_1 = np.asarray(np_class_ID_1)


np_class_beat_2 = [str(i) for i in np_class_beat_2]
np_class_ID_2 = [int(i) for i in np_class_ID_2]

np_class_beat_2 = np.asarray(np_class_beat_2)
np_class_ID_2 = np.asarray(np_class_ID_2)

DB_type_all = [str(i) for i in DB_type_all]
DB_class_all = [int(i) for i in DB_class_all]

DB_type_all = np.asarray(DB_type_all)
DB_class_all = np.asarray(DB_class_all)

np_non_1 = np.asarray(DB1_non_cli)
np_non_2 = np.asarray(DB2_non_cli)

np_non_var_1 = np.asarray(DB1_non_cli.iloc[:,0:140])



np_non_var_2 = np.asarray(DB2_non_cli.iloc[:,0:140])

DB_var_non_all = np.vstack((np_non_var_1,np_non_var_2))

dis_1 = DB1_dwt.iloc[:,0]


dis_2 = DB2_dwt.iloc[:,0]

dis_1_V1 = DB1_dwt_V1.iloc[:,0]


dis_2_V1 = DB2_dwt_V1.iloc[:,0]

dtw_1 = np.asarray(dis_1)
dtw_1 = dtw_1.reshape(dtw_1.shape[0],1)

dtw_2 = np.asarray(dis_2)
dtw_2 = dtw_2.reshape(dtw_2.shape[0],1)

dtw_1_V1 = np.asarray(dis_1_V1)
dtw_1_V1 = dtw_1_V1.reshape(dtw_1_V1.shape[0],1)


dtw_2_V1 = np.asarray(dis_2_V1)
dtw_2_V1 = dtw_2_V1.reshape(dtw_2_V1.shape[0],1)

v1_1 = DB1_V1.iloc[:,0:130]

np_V1_1 = np.asarray(v1_1)


v1_2 = DB2_V1.iloc[:,0:130]

np_V1_2 = np.asarray(v1_2)

DB_v_var_all = np.vstack((np_V1_1,np_V1_2))

dtw_clinic_1 = np.hstack((dtw_1, dtw_1_V1))
dtw_clinic_2 = np.hstack((dtw_2, dtw_2_V1))


norm_dtw_clinic_1 = post_features.normalised_values_multiples(dtw_clinic_1)
norm_dtw_clinic_2 = post_features.normalised_values_multiples(dtw_clinic_2)


np_clinic_1 = np.hstack((np_variables_1, np_V1_1, dtw_clinic_1))
np_clinic_2 = np.hstack((np_variables_2,np_V1_2, dtw_clinic_2))

np_clinic_all = np.hstack((DB_var_all,DB_v_var_all))

done norm
row 0 done
done norm
row 1 done
done norm
row 0 done
done norm
row 1 done


In [4]:
ls = []
ls.extend(['N', 'L', 'R'])                    # N
ls.extend(['A', 'a', 'J', 'S', 'e', 'j'])     # SVEB 
ls.extend(['V', 'E'])                         # VEB
ls.extend(['F'])
DB1_amp = pd.read_csv("DB1_amp_time.csv")
#DB1_amp = DB1_amp.drop([1872])
#DB1_amp = DB1_amp[DB1_amp['patient'].isin(patient_l_1)]
DB1_amp = DB1_amp[DB1_amp['col1080'].isin(ls)]




DB2_amp = pd.read_csv("DB2_amp_time.csv")
#DB2_amp = DB2_amp.drop([18692, 31865])
#DB2_amp = DB2_amp[DB2_amp['patient'].isin(patient_l_2)]
DB2_amp = DB2_amp[DB2_amp['col1080'].isin(ls)]


In [5]:
ampt_time_1 = DB1_amp.iloc[:,0:1082-2]


ampt_time_2 = DB2_amp.iloc[:,0:1082-2]

np_amp_1 = np.asarray(ampt_time_1)
np_amp_2 = np.asarray(ampt_time_2)