In [1]:
from codes.python import load_DF_beats as DF
import numpy as np
from codes.python import metric
from codes. python import post_process_features_ex as post_features
import pandas as pd

from sklearn.metrics import classification_report, confusion_matrix 
ls = []
ls.extend(['N', 'L', 'R'])                    # N
ls.extend(['A', 'a', 'J', 'S', 'e', 'j'])     # SVEB 
ls.extend(['V', 'E'])                         # VEB
ls.extend(['F'])
#ls.extend([ 'P', '/', 'f', 'u'])
patient_l_1 = [101]
#patient_l_2 = [100]
patient_ls_1 = [101,106,108,109,112,114,115,116,118,119,122,124,201,203,205,207,208,209,215,220,223,230]
patient_ls_2 = [100,103,105,111,113,117,121,123,200,202,210,212,213,214,219,221,222,228,231,232,233,234]


ls2 = []
ls2.extend(["['N']","['L']", "['R']"])                    # N
ls2.extend(["['A']", "['a']", "['J']", "['S']",  "['e']", "['j']"])     # SVEB 
ls2.extend(["['V']", "['E']"])                         # VEB
ls2.extend(["['F']"])
#ls.extend([ "['P']","[ '/']"," ['f']", "['u']"])

In [2]:
np_clinic_1_old, np_clinic_2_old,np_non_var_1_old, np_non_var_2_old, np_class_ID_1_old, np_class_ID_2_old, patients_ls_1, patients_ls_2, DB1, DB2, DB1_V1, DB2_V1, DB1_non_cli, DB2_non_cli, DB1_dwt, DB2_dwt, DB1_dwt_V1, DB2_dwt_V1 = DF.get_all_dataframe(patient_l_1=patient_ls_1,patient_l_2=patient_ls_2 , ls=ls, ls2=ls2 )

In [3]:
np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]

In [4]:
good_features_X = np.asarray(pd.read_csv("database/gooddata_X_train_no_outliers.csv").iloc[:,1:263])
good_features_y = np.asarray(pd.read_csv("database/gooddata_y_train_no_outliers.csv").iloc[:,1])

rank = pd.read_csv("database/features_ranking.py")

In [36]:
norm_var_1_clinic = post_features.normalised_values_multiples(good_features_X)
norm_var_2_clinic = post_features.normalised_values_multiples(X_test)
#norm_var_1_non = post_features.normalised_values_multiples(np_non_var_1)
#norm_var_2_non = post_features.normalised_values_multiples(np_non_var_2)



X_train_norm = np.hstack((good_features_X,norm_var_1_clinic))
X_test_norm = np.hstack((X_test,norm_var_2_clinic))
rank_norm = pd.read_csv("database/features_ranking_with_norm.py")

done norm
row 0 done
done norm
row 1 done
done norm
row 2 done
done norm
row 3 done
done norm
row 4 done
done norm
row 5 done
done norm
row 6 done
done norm
row 7 done
done norm
row 8 done
done norm
row 9 done
done norm
row 10 done
done norm
row 11 done
done norm
row 12 done
done norm
row 13 done
done norm
row 14 done
done norm
row 15 done
done norm
row 16 done
done norm
row 17 done
done norm
row 18 done
done norm
row 19 done
done norm
row 20 done
done norm
row 21 done
done norm
row 22 done
done norm
row 23 done
done norm
row 24 done
done norm
row 25 done
done norm
row 26 done
done norm
row 27 done
done norm
row 28 done
done norm
row 29 done
done norm
row 30 done
done norm
row 31 done
done norm
row 32 done
done norm
row 33 done
done norm
row 34 done
done norm
row 35 done
done norm
row 36 done
done norm
row 37 done
done norm
row 38 done
done norm
row 39 done
done norm
row 40 done
done norm
row 41 done
done norm
row 42 done
done norm
row 43 done
done norm
row 44 done
done norm
row 45 don

done norm
row 105 done
done norm
row 106 done
done norm
row 107 done
done norm
row 108 done
done norm
row 109 done
done norm
row 110 done
done norm
row 111 done
done norm
row 112 done
done norm
row 113 done
done norm
row 114 done
done norm
row 115 done
done norm
row 116 done
done norm
row 117 done
done norm
row 118 done
done norm
row 119 done
done norm
row 120 done
done norm
row 121 done
done norm
row 122 done
done norm
row 123 done
done norm
row 124 done
done norm
row 125 done
done norm
row 126 done
done norm
row 127 done
done norm
row 128 done
done norm
row 129 done
done norm
row 130 done
done norm
row 131 done
done norm
row 132 done
done norm
row 133 done
done norm
row 134 done
done norm
row 135 done
done norm
row 136 done
done norm
row 137 done
done norm
row 138 done
done norm
row 139 done
done norm
row 140 done
done norm
row 141 done
done norm
row 142 done
done norm
row 143 done
done norm
row 144 done
done norm
row 145 done
done norm
row 146 done
done norm
row 147 done
done norm
r

In [5]:
feat_labels = ["R_duration", "R_height", "R_amp0", "R_amp1","R_amp2","R_amp3", "R_amp4", "R_amp5", "R_amp6", "R_amp7", "R_amp8", "R_amp9", "R_prominence","R_areas","Q_duration", "Q_height", "Q_amp0", "Q_amp1","Q_amp2","Q_amp3", "Q_amp4", "Q_amp5", "Q_amp6", "Q_amp7", "Q_amp8", "Q_amp9", "Q_prominence","Q_areas", "S_duration", "S_height", "S_amp0", "S_amp1","S_amp2","S_amp3", "S_amp4", "S_amp5", "S_amp6", "S_amp7", "S_amp8", "S_amp9", "S_prominence","S_areas", "P_duration", "P_height", "P_amp0", "P_amp1","P_amp2","P_amp3", "P_amp4", "P_amp5", "P_amp6", "P_amp7", "P_amp8", "P_amp9", "P_prominence","P_areas", "P_neg_duration", "P_neg_height", "P_neg_amp0", "P_neg_amp1","P_neg_amp2","P_neg_amp3", "P_neg_amp4", "P_neg_amp5", "P_neg_amp6", "P_neg_amp7", "P_neg_amp8", "P_neg_amp9", "P_neg_prominence","P_neg_areas", "T_duration", "T_height", "T_amp0", "T_amp1","T_amp2","T_amp3", "T_amp4", "T_amp5", "T_amp6", "T_amp7", "T_amp8", "T_amp9", "T_prominence","T_areas","T_neg_durations","T_neg_height", "T_neg_amp0", "T_neg_amp1", "T_neg_amp2", "T_neg_amp3", "T_neg_amp4", "T_neg_amp5", "T_neg_amp6", "T_neg_amp7", "T_neg_amp8", "T_neg_amp9","T_neg_prominence","T_neg_areas", "rr_int_pre", "rr_int_post", "rr_int_10", "rr_int_50", "rr_int_all", "QRS_int", "QRS_int_10", "QRS_int_50", "PQ_int", "PQ_int_10", "PQ_int_50", "PR_int", "PR_int_10", "PR_int_50", "ST_int", "ST_int_10", "ST_int_50", "RT_int", "RT_int_10", "RT_int_50", "PT_int", "PT_int_10", "PT_int_50", "RP","TR","neg_RQ", "neg_PR", "neg_ST", "neg_RT", "neg_PT", "P_neg_T", "neg_P_neg_T"]
feat_labels_V = ["R_duration_V", "R_height_V", "R_amp0_V", "R_amp1_V","R_amp2_V","R_amp3_V", "R_amp4_V", "R_amp5_V", "R_amp6_V", "R_amp7_V", "R_amp8_V", "R_amp9_V", "R_prominence_V","R_areas_V","Q_duration_V", "Q_height_V", "Q_amp0_V", "Q_amp1_V","Q_amp2_V","Q_amp3_V", "Q_amp4_V", "Q_amp5_V", "Q_amp6_V", "Q_amp7_V", "Q_amp8_V", "Q_amp9_V", "Q_prominence_V","Q_areas_V", "S_duration_V", "S_height_V", "S_amp0_V", "S_amp1_V","S_amp2_V","S_amp3_V", "S_amp4_V", "S_amp5_V", "S_amp6_V", "S_amp7_V", "S_amp8_V", "S_amp9_V", "S_prominence_V","S_areas_V", "P_duration_V", "P_height_V", "P_amp0_V", "P_amp1_V","P_amp2_V","P_amp3_V", "P_amp4_V", "P_amp5_V", "P_amp6_V", "P_amp7_V", "P_amp8_V", "P_amp9_V", "P_prominence_V","P_areas_V", "P_neg_duration_V", "P_neg_height_V", "P_neg_amp0_V", "P_neg_amp1_V","P_neg_amp2_V","P_neg_amp3_V", "P_neg_amp4_V", "P_neg_amp5_V", "P_neg_amp6_V", "P_neg_amp7_V", "P_neg_amp8_V", "P_neg_amp9_V", "P_neg_prominence_V","P_neg_areas_V", "T_duration_V", "T_height_V", "T_amp0_V", "T_amp1_V","T_amp2_V","T_amp3_V", "T_amp4_V", "T_amp5_V", "T_amp6_V", "T_amp7_V", "T_amp8_V", "T_amp9_V", "T_prominence_V","T_areas_V","T_neg_durations_V","T_neg_height_V", "T_neg_amp0_V", "T_neg_amp1_V", "T_neg_amp2_V", "T_neg_amp3_V", "T_neg_amp4_V", "T_neg_amp5_V", "T_neg_amp6_V", "T_neg_amp7_V", "T_neg_amp8_V", "T_neg_amp9_V","T_neg_prominence_V","T_neg_areas_V", "rr_int_pre_V", "rr_int_post_V", "rr_int_10_V", "rr_int_50_V", "rr_int_all_V", "QRS_int_V", "QRS_int_10_V", "QRS_int_50_V", "PQ_int_V", "PQ_int_10_V", "PQ_int_50_V", "PR_int_V", "PR_int_10_V", "PR_int_50_V", "ST_int_V", "ST_int_10_V", "ST_int_50_V", "RT_int_V", "RT_int_10_V", "RT_int_50_V", "PT_int_V", "PT_int_10_V", "PT_int_50_V", "RP_V","TR_V","neg_RQ_V", "neg_PR_V", "neg_ST_V", "neg_RT_V", "neg_PT_V", "P_neg_T_V", "neg_P_neg_T_V"]
feat_labels_dtw = ["dtw1","dtw2"]
norm_dtw = ["dtw1_v1","dtw2_v1"]
classID = ["classID"]
non_clinic = list(DB1_non_cli.iloc[:,0:140].columns.values)

feature_norm_mill = []
for i in range(len(feat_labels)):
    feature_norm_mill.append(str(feat_labels[i]+"_n_MLII"))

feature_norm_V1 = []
for i in range(len(feat_labels)):
    feature_norm_V1.append(str(feat_labels[i]+"_n_V1"))
    

c_ID = np.asarray(classID)
f_M = np.asarray(feat_labels)
f_V = np.asarray(feat_labels_V)
f_d = np.asarray(feat_labels_dtw)
non_cli = np.asarray(non_clinic)
norm_mlii = np.asarray(feature_norm_mill)
norm_v1 = np.asarray(feature_norm_V1)
norm_dtw = np.asarray(norm_dtw)


features_clinic = np.hstack((f_M,f_V, f_d))
features_clinic_norm = np.hstack((f_M,f_V, f_d,norm_mlii,norm_v1,norm_dtw ))
#row=[]
#for i in range(0,len(np_clinic_new_1)):
    #row.append(i)
    
X_train_balanced = pd.DataFrame(good_features_X,columns=features_clinic)
X_train = pd.DataFrame(X_train,columns=features_clinic)
X_test = pd.DataFrame(X_test,columns=features_clinic)

#X_train_balanced_norm = pd.DataFrame(X_train_norm,columns=features_clinic_norm)
#X_test_norm = pd.DataFrame(X_test_norm,columns=features_clinic_norm)

In [23]:
score = 0.01
#Linear_D(train, train_labels, test, test_labels, labels=['N','S','V','F'])
print("SVM")
svm_model_poly(good_features_X, good_features_y,X_test , y_test, labels=[0,1,2,3])
print("XGboost")
xgboost(np.asarray(X_train_balanced[rank[rank['rfscore'] >= score]['features'].values]), good_features_y, np.asarray(X_test[rank[rank['rfscore'] >= score]['features'].values]), y_test, labels=[0,1,2,3])
#svm_model_poly(X_train_df[df[df['rfscore'] >= score]['features'].values], good_features_y,X_test_df[df[df['rfscore'] >= score]['features'].values] , y_test, labels=[0,1,2,3])[0]
print("Logistic")
logisticRegress(X_train_balanced[rank[rank['rfscore'] >= score]['features'].values], good_features_y, X_test[rank[rank['rfscore'] >= score]['features'].values], y_test, labels=[0,1,2,3])
print("Linear_D")
Linear_D(X_train_balanced[rank[rank['rfscore'] >= score]['features'].values], good_features_y, X_test[rank[rank['rfscore'] >= score]['features'].values], y_test,  labels=[0,1,2,3])
#ada(X_train_df[rank['features'].values], good_features_y, X_test_df[rank['features'].values], y_test,  labels=[0,1,2,3])
print("SVM_LN")
svm_model_linear(np.asarray(X_train_balanced[rank[rank['rfscore'] >= score]['features'].values]), good_features_y, np.asarray(X_test[rank[rank['rfscore'] >= score]['features'].values]), y_test,  labels=[0,1,2,3])
print("voting_ensemble")
#voting_ensemble(np.asarray(X_train_balanced[rank[rank['rfscore'] >= score]['features'].values]), good_features_y,np.asarray( X_test[rank[rank['rfscore'] >= score]['features'].values]), y_test,  labels=[0,1,2,3])
print("ada")

#ada(np.asarray(X_train_balanced[rank[rank['rfscore'] >= score]['features'].values]), good_features_y,np.asarray( X_test[rank[rank['rfscore'] >= score]['features'].values]), y_test,  labels=[0,1,2,3])


print("voting_ensemble")

#voting_ensemble(good_features_X, good_features_y,np.asarray(X_test) , y_test, labels=[0,1,2,3])

feature_good = rank[rank['rfscore'] >= score]['features'].values


#Linear_D(X_train[feature_good], y_train, X_test[feature_good], y_test, labels=[0,1,2,3])



SVM
[[34986   635  3908  4492]
 [  502  1336   122    90]
 [  198    51  2525   446]
 [   26     0     7   355]]
              precision    recall  f1-score   support

           0       0.98      0.79      0.88     44021
           1       0.66      0.65      0.66      2050
           2       0.38      0.78      0.52      3220
           3       0.07      0.91      0.12       388

   micro avg       0.79      0.79      0.79     49679
   macro avg       0.52      0.79      0.54     49679
weighted avg       0.92      0.79      0.84     49679

XGboost
[[34424  2201  2976  4420]
 [ 1189   469   383     9]
 [   49    75  3050    46]
 [   26     2    67   293]]
              precision    recall  f1-score   support

           0       0.96      0.78      0.86     44021
           1       0.17      0.23      0.20      2050
           2       0.47      0.95      0.63      3220
           3       0.06      0.76      0.11       388

   micro avg       0.77      0.77      0.77     49679
   macro 

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[30605  5051  1006  7359]
 [  262  1441   296    51]
 [   46   250  2644   280]
 [   14     0    14   360]]
              precision    recall  f1-score   support

           0       0.99      0.70      0.82     44021
           1       0.21      0.70      0.33      2050
           2       0.67      0.82      0.74      3220
           3       0.04      0.93      0.09       388

   micro avg       0.71      0.71      0.71     49679
   macro avg       0.48      0.79      0.49     49679
weighted avg       0.93      0.71      0.79     49679

[0.32512357477278625, 2.4054564061636237, 0.4632438381568461]
Linear_D


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[26769 10324   211  6717]
 [  317  1435   250    48]
 [   56   265  2534   365]
 [   17     0    11   360]]
              precision    recall  f1-score   support

           0       0.99      0.61      0.75     44021
           1       0.12      0.70      0.20      2050
           2       0.84      0.79      0.81      3220
           3       0.05      0.93      0.09       388

   micro avg       0.63      0.63      0.63     49679
   macro avg       0.50      0.76      0.47     49679
weighted avg       0.93      0.63      0.73     49679

[0.2526846194659283, 2.4492818710405277, 0.4325025436130301]
SVM_LN
[[34172  2882   617  6350]
 [  277  1495   240    38]
 [   70   335  2665   150]
 [   15     1    15   357]]
              precision    recall  f1-score   support

           0       0.99      0.78      0.87     44021
           1       0.32      0.73      0.44      2050
           2       0.75      0.83      0.79      3220
           3       0.05      0.92      0.10       388

   micr

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[39772   356   118  3775]
 [ 1708    49   254    39]
 [  379    63  2487   291]
 [   23     0     9   356]]
              precision    recall  f1-score   support

           0       0.95      0.90      0.93     44021
           1       0.10      0.02      0.04      2050
           2       0.87      0.77      0.82      3220
           3       0.08      0.92      0.15       388

   micro avg       0.86      0.86      0.86     49679
   macro avg       0.50      0.65      0.48     49679
weighted avg       0.90      0.86      0.88     49679

[0.4309214399351081, 1.768118353887931, 0.43647551420354547]


(LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
               solver='svd', store_covariance=False, tol=0.0001),
 array([1, 0, 0, ..., 0, 0, 0]),
 0.43647551420354547)

In [ ]:
from sklearn import svm

score = 0.01
feature_good = rank[rank['rfscore'] >= score]['features'].values


clf = svm.SVC(kernel='linear')

clf.fit(X_train[feature_good], y_train)
y_pred = clf.predict(X_test[feature_good])
print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))

In [93]:
score = 0.01
#Linear_D(train, train_labels, test, test_labels, labels=['N','S','V','F'])
svm_model_poly(good_features_X, good_features_y,X_test , y_test, labels=[0,1,2,3])
#xgboost(np.asarray(X_train[rank[rank['rfscore'] >= score]['features'].values]), good_features_y, np.asarray(X_test[rank[rank['rfscore'] >= score]['features'].values]), y_test, labels=[0,1,2,3])
#svm_model_poly(X_train_df[df[df['rfscore'] >= score]['features'].values], good_features_y,X_test_df[df[df['rfscore'] >= score]['features'].values] , y_test, labels=[0,1,2,3])[0]
logisticRegress(X_train[rank[rank['rfscore'] >= score]['features'].values], y_train, X_test[rank[rank['rfscore'] >= score]['features'].values], y_test, labels=[0,1,2,3])
Linear_D(X_train[rank[rank['rfscore'] >= score]['features'].values], y_train, X_test[rank[rank['rfscore'] >= score]['features'].values], y_test,  labels=[0,1,2,3])
#ada(X_train_df[rank['features'].values], good_features_y, X_test_df[rank['features'].values], y_test,  labels=[0,1,2,3])
#svm_model_linear(np.asarray(X_train[rank[rank['rfscore'] >= score]['features'].values]), good_features_y, np.asarray(X_test[rank[rank['rfscore'] >= score]['features'].values]), y_test,  labels=[0,1,2,3])
#voting_ensemble(np.asarray(X_train[rank[rank['rfscore'] >= score]['features'].values]), good_features_y,np.asarray( X_test[rank[rank['rfscore'] >= score]['features'].values]), y_test,  labels=[0,1,2,3])
#ada(np.asarray(X_train[rank[rank['rfscore'] >= score]['features'].values]), good_features_y,np.asarray( X_test[rank[rank['rfscore'] >= score]['features'].values]), y_test,  labels=[0,1,2,3])



#voting_ensemble(good_features_X, good_features_y,np.asarray(X_test) , y_test, labels=[0,1,2,3])


[[34986   635  3908  4492]
 [  502  1336   122    90]
 [  198    51  2525   446]
 [   26     0     7   355]]
              precision    recall  f1-score   support

           0       0.98      0.79      0.88     44021
           1       0.66      0.65      0.66      2050
           2       0.38      0.78      0.52      3220
           3       0.07      0.91      0.12       388

   micro avg       0.79      0.79      0.79     49679
   macro avg       0.52      0.79      0.54     49679
weighted avg       0.92      0.79      0.84     49679

[0.4007485524244452, 2.4813919785105343, 0.5105482735260394]


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[38399   783   351  4488]
 [ 1493   183   329    45]
 [   91    77  2839   213]
 [   20     0    12   356]]
              precision    recall  f1-score   support

           0       0.96      0.87      0.91     44021
           1       0.18      0.09      0.12      2050
           2       0.80      0.88      0.84      3220
           3       0.07      0.92      0.13       388

   micro avg       0.84      0.84      0.84     49679
   macro avg       0.50      0.69      0.50     49679
weighted avg       0.91      0.84      0.87     49679

[0.4323372331587701, 1.9504222520303145, 0.45997139808317433]
[[39772   356   118  3775]
 [ 1708    49   254    39]
 [  379    63  2487   291]
 [   23     0     9   356]]
              precision    recall  f1-score   support

           0       0.95      0.90      0.93     44021
           1       0.10      0.02      0.04      2050
           2       0.87      0.77      0.82      3220
           3       0.08      0.92      0.15       388

   micro avg 

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


(LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
               solver='svd', store_covariance=False, tol=0.0001),
 0.43647551420354547)

In [52]:
score = 0.009
#Linear_D(train, train_labels, test, test_labels, labels=['N','S','V','F'])
svm_model_poly(good_features_X, good_features_y,X_test , y_test, labels=[0,1,2,3])
logisticRegress(X_train_balanced_norm, good_features_y,X_test_norm , y_test, labels=[0,1,2,3])

xgboost(np.asarray(X_train_balanced_norm[rank_norm[rank_norm['rfscore'] >= score]['features'].values]), good_features_y, np.asarray(X_test_norm[rank_norm[rank_norm['rfscore'] >= score]['features'].values]), y_test, labels=[0,1,2,3])
#svm_model_poly(X_train_df[df[df['rfscore'] >= score]['features'].values], good_features_y,X_test_df[df[df['rfscore'] >= score]['features'].values] , y_test, labels=[0,1,2,3])[0]
logisticRegress(X_train_balanced_norm[rank_norm[rank_norm['rfscore'] >= score]['features'].values], good_features_y, X_test_norm[rank_norm[rank_norm['rfscore'] >= score]['features'].values], y_test, labels=[0,1,2,3])
Linear_D(X_train_balanced_norm[rank_norm[rank_norm['rfscore'] >= score]['features'].values], good_features_y, X_test_norm[rank_norm[rank_norm['rfscore'] >= score]['features'].values], y_test,  labels=[0,1,2,3])
#ada(X_train_df[rank['features'].values], good_features_y, X_test_df[rank['features'].values], y_test,  labels=[0,1,2,3])
svm_model_linear(X_train_balanced_norm[rank_norm[rank_norm['rfscore'] >= score]['features'].values], good_features_y, X_test_norm[rank_norm[rank_norm['rfscore'] >= score]['features'].values], y_test,  labels=[0,1,2,3])


[[34986   635  3908  4492]
 [  502  1336   122    90]
 [  198    51  2525   446]
 [   26     0     7   355]]
              precision    recall  f1-score   support

           0       0.98      0.79      0.88     44021
           1       0.66      0.65      0.66      2050
           2       0.38      0.78      0.52      3220
           3       0.07      0.91      0.12       388

   micro avg       0.79      0.79      0.79     49679
   macro avg       0.52      0.79      0.54     49679
weighted avg       0.92      0.79      0.84     49679

[0.4007485524244452, 2.4813919785105343, 0.5105482735260394]


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[[ 5940 10612  5189 22280]
 [   28  1620    42   360]
 [   89  1968   348   815]
 [   10    12    18   348]]
              precision    recall  f1-score   support

           0       0.98      0.13      0.24     44021
           1       0.11      0.79      0.20      2050
           2       0.06      0.11      0.08      3220
           3       0.01      0.90      0.03       388

   micro avg       0.17      0.17      0.17     49679
   macro avg       0.29      0.48      0.14     49679
weighted avg       0.88      0.17      0.22     49679

[0.040419908159769806, 1.0744827814072828, 0.15452030175579526]
[[26710  2582  7599  7130]
 [  652   429   940    29]
 [    6     4  3202     8]
 [   12     2   373     1]]
              precision    recall  f1-score   support

           0       0.98      0.61      0.75     44021
           1       0.14      0.21      0.17      2050
           2       0.26      0.99      0.42      3220
           3       0.00      0.00      0.00       388

   micro av

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[26285 10827   659  6250]
 [  217  1509   311    13]
 [   16   245  2839   120]
 [   11     1    19   357]]
              precision    recall  f1-score   support

           0       0.99      0.60      0.75     44021
           1       0.12      0.74      0.21      2050
           2       0.74      0.88      0.81      3220
           3       0.05      0.92      0.10       388

   micro avg       0.62      0.62      0.62     49679
   macro avg       0.48      0.78      0.46     49679
weighted avg       0.93      0.62      0.72     49679

[0.2628040160327314, 2.4793483609328204, 0.44132055313296825]


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[26508  8288   256  8969]
 [  222  1453   352    23]
 [   11   100  2965   144]
 [   12     0    16   360]]
              precision    recall  f1-score   support

           0       0.99      0.60      0.75     44021
           1       0.15      0.71      0.24      2050
           2       0.83      0.92      0.87      3220
           3       0.04      0.93      0.07       388

   micro avg       0.63      0.63      0.63     49679
   macro avg       0.50      0.79      0.48     49679
weighted avg       0.94      0.63      0.73     49679

[0.2718542460334204, 2.603370951774251, 0.4613484919884916]
[[24981  9489  1327  8224]
 [  197  1550   290    13]
 [   25   809  2326    60]
 [   10     2    74   302]]
              precision    recall  f1-score   support

           0       0.99      0.57      0.72     44021
           1       0.13      0.76      0.22      2050
           2       0.58      0.72      0.64      3220
           3       0.04      0.78      0.07       388

   micro avg   

(SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
   decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
   max_iter=-1, probability=True, random_state=None, shrinking=True,
   tol=0.1, verbose=False), 0.38667442190918655)

In [105]:
y_pred = svm_model_poly(good_features_X, good_features_y,X_test , y_test, labels=[0,1,2,3])[1]


[[34986   635  3908  4492]
 [  502  1336   122    90]
 [  198    51  2525   446]
 [   26     0     7   355]]
              precision    recall  f1-score   support

           0       0.98      0.79      0.88     44021
           1       0.66      0.65      0.66      2050
           2       0.38      0.78      0.52      3220
           3       0.07      0.91      0.12       388

   micro avg       0.79      0.79      0.79     49679
   macro avg       0.52      0.79      0.54     49679
weighted avg       0.92      0.79      0.84     49679

[0.4007485524244452, 2.4813919785105343, 0.5105482735260394]


In [32]:
y_pred = svm_model_poly(good_features_X, good_features_y,X_test , y_test, labels=[0,1,2,3])[1]

X_test_n_1 =X_test[y_pred != 1]
y_test_n_1=y_test[y_pred != 1]

y_pred_n = y_pred[y_pred == 1]
y_true_1 = y_test[y_pred == 1]

score = 0.01

feature_good = rank[rank['rfscore'] >= score]['features'].values
y_pred_voting_ensemble =voting_ensemble(np.asarray(X_train_balanced[rank[rank['rfscore'] >= score]['features'].values]), good_features_y,np.asarray( X_test_n_1[rank[rank['rfscore'] >= score]['features'].values]), np.asarray(y_test_n_1),  labels=[0,1,2,3])[1]

X_test_n_2 =X_test_n_1[y_pred_voting_ensemble != 2]
y_test_n_2=y_test_n_1[y_pred_voting_ensemble != 2]

y_pred_voting_ensemble_n = y_pred_voting_ensemble[y_pred_voting_ensemble == 2]
y_true_2 = y_test_n_1[y_pred_voting_ensemble == 2]


y_pred_linear_D =Linear_D(np.asarray(X_train[feature_good]), y_train,np.asarray( X_test_n_2[feature_good]), y_test_n_2,  labels=[0,1,2,3])[1]

X_test_n_3 =X_test_n_2[y_pred_linear_D != 2]
y_test_n_3=y_test_n_2[y_pred_linear_D != 2]

y_pred_linear_D_2 = y_pred_linear_D[y_pred_linear_D == 2]
y_true_3 = y_test_n_2[y_pred_linear_D == 2]

#y_true_1 = y_test_n_1[y_pred_voting_ensemble == 2]


X_test_n_3 =X_test_n_2[y_pred_linear_D != 0]
y_test_n_3=y_test_n_2[y_pred_linear_D != 0]

y_pred_linear_D_0 = y_pred_linear_D[y_pred_linear_D == 0]
y_true_4 = y_test_n_2[y_pred_linear_D == 0]

y_svm = svm_model_poly(X_train_balanced, good_features_y, X_test_n_3, y_test_n_3, labels=[0,1,2,3])[1]


X_test_n_4 =X_test_n_3[y_svm != 0]
y_test_n_4=y_test_n_3[y_svm != 0]

y_svm_n = y_svm[y_svm == 0]
y_true_5 = y_test_n_3[y_svm == 0]

y_v_e = Linear_D(X_train_balanced, good_features_y, X_test_n_4, y_test_n_4, labels=[0,1,2,3])[1]

y_final_pred = np.hstack((y_pred_n,y_pred_voting_ensemble_n, y_pred_linear_D_2,y_pred_linear_D_0,y_svm_n,y_v_e))
y_final_true = np.hstack((y_true_1,y_true_2,y_true_3,y_true_4,y_true_5,y_test_n_4))



[[34986   635  3908  4492]
 [  502  1336   122    90]
 [  198    51  2525   446]
 [   26     0     7   355]]
              precision    recall  f1-score   support

           0       0.98      0.79      0.88     44021
           1       0.66      0.65      0.66      2050
           2       0.38      0.78      0.52      3220
           3       0.07      0.91      0.12       388

   micro avg       0.79      0.79      0.79     49679
   macro avg       0.52      0.79      0.54     49679
weighted avg       0.92      0.79      0.84     49679



C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[34303  2467   450  6166]
 [  269   364    52    29]
 [   58   187  2778   146]
 [   16     0    15   357]]
              precision    recall  f1-score   support

           0       0.99      0.79      0.88     43386
           1       0.12      0.51      0.20       714
           2       0.84      0.88      0.86      3169
           3       0.05      0.92      0.10       388

   micro avg       0.79      0.79      0.79     47657
   macro avg       0.50      0.77      0.51     47657
weighted avg       0.96      0.79      0.86     47657



C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[38936   249     7  3744]
 [  621    17     6    18]
 [   95    26   140   130]
 [   17     0     1   355]]
              precision    recall  f1-score   support

           0       0.98      0.91      0.94     42936
           1       0.06      0.03      0.04       662
           2       0.91      0.36      0.51       391
           3       0.08      0.95      0.15       373

   micro avg       0.89      0.89      0.89     44362
   macro avg       0.51      0.56      0.41     44362
weighted avg       0.96      0.89      0.92     44362

[0.17087378697643424, 1.3510461114659127, 0.2543176574214562]
[[1174    0  140 2686]
 [   9    0   15   17]
 [  11    0  158  127]
 [   4    0    1  351]]
              precision    recall  f1-score   support

           0       0.98      0.29      0.45      4000
           1       0.00      0.00      0.00        41
           2       0.50      0.53      0.52       296
           3       0.11      0.99      0.20       356

   micro avg       0.36      

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[ 668  123  255 1780]
 [   3   14    7    8]
 [   2   41  113  129]
 [   0    0    1  351]]
              precision    recall  f1-score   support

           0       0.99      0.24      0.38      2826
           1       0.08      0.44      0.13        32
           2       0.30      0.40      0.34       285
           3       0.15      1.00      0.27       352

   micro avg       0.33      0.33      0.33      3495
   macro avg       0.38      0.52      0.28      3495
weighted avg       0.84      0.33      0.36      3495

[0.12680155733899456, 1.213174828357051, 0.21504763221412865]


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [33]:
print(confusion_matrix(y_final_true,y_final_pred, labels=[0,1,2,3]))  
print(classification_report(y_final_true,y_final_pred, labels=[0,1,2,3]))
print(metric.get_metrics(y_final_true,y_final_pred, lb=[0,1,2,3]))

[[40778   758   712  1780]
 [  633  1350    65     8]
 [  108    92  3031   129]
 [   21     0    17   351]]
              precision    recall  f1-score   support

           0       0.98      0.93      0.95     44028
           1       0.61      0.66      0.63      2056
           2       0.79      0.90      0.84      3360
           3       0.15      0.90      0.26       389

   micro avg       0.91      0.91      0.91     49833
   macro avg       0.64      0.85      0.67     49833
weighted avg       0.95      0.91      0.93     49833

[0.6613550772862884, 2.96475278361551, 0.701271636595083]


In [8]:
from sklearn import svm

## small C from 1 to 3 seems to be good for f class recalled
## degree 3 is better all around
## Tol at 0.01 seems best

def svm_model_poly(X_train, y_train, X_test, y_test, C=10, kernel='poly', degree=3, gamma='auto', 
                        coef0=0.001, shrinking=True, probability=True, tol=0.01, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None, labels = [0,1,2,3]):
    
    svm_model_linear = svm.SVC(C=C, kernel=kernel, degree=degree, gamma=gamma, 
                        coef0=coef0, shrinking=shrinking, probability=probability, tol=tol, 
                        cache_size=cache_size, verbose=verbose, 
                        max_iter=max_iter, decision_function_shape='ovo', random_state=random_state) 
    
    svm_model_linear.fit(X_train, y_train)
    y_pred = svm_model_linear.predict(X_test)    
    print(confusion_matrix(y_test,y_pred, labels=labels))  
    print(classification_report(y_test,y_pred))
    #print(metric.get_metrics(y_pred,y_test,lb=labels))
    
    return svm_model_linear,y_pred#, metric.get_metrics(y_pred,y_test, lb=labels)[2]


from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

def Linear_D(X_train, y_train, X_test, y_test, labels = [0,1,2,3]):
    clf = LinearDiscriminantAnalysis()
    clf.fit(X_train, y_train)  
    y_pred = clf.predict(X_test)
    print(confusion_matrix(y_test,y_pred, labels = labels))  
    print(classification_report(y_test,y_pred, labels=labels))
    print(metric.get_metrics(y_pred,y_test, lb=labels))
    
    return clf,y_pred, metric.get_metrics(y_pred,y_test,lb=labels)[2]

from sklearn.ensemble import RandomForestClassifier

## Number of feature at 50 or 100 is good too
## numner of estimators leaves at 1000 

def randomForest(X_train, y_train, X_test, y_test,n_estimators=1000, criterion='gini', max_depth=16, min_samples_split=2, min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, max_features=50, max_leaf_nodes=None, class_weight='balanced', labels = [0,1,2,3]):
    
    rf = RandomForestClassifier(n_estimators=n_estimators, criterion=criterion, max_depth=max_depth, min_samples_split=min_samples_split, min_samples_leaf=min_samples_leaf,min_weight_fraction_leaf=min_weight_fraction_leaf, class_weight=class_weight, min_impurity_decrease=min_impurity_decrease,max_features=max_features)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)    
    print(confusion_matrix(y_test,y_pred, labels=labels))  
    print(classification_report(y_test,y_pred, labels=labels))
    print(metric.get_metrics(y_pred,y_test, lb=labels))
    
    return rf, y_pred, metric.get_metrics(y_pred,y_test, lb=labels)[2]


### xgbo is good for normal classes too
## do this one next 
## XGB is very goos for V class
## XGboost tree classifcation is good with 5 or more tree depth
from xgboost import XGBClassifier


def xgboost(X_train,y_train, X_test, y_test, max_depth = 8, eta = 1, gamma = 0.001, min_child_weight=0.1,max_delta_step=10, subsample=0.6,colsample_bytree = 0.7, colsample_bylevel= 1, colsample_bynode=1, alpha=0, reg_lambda= 1, tree_method='exact', grow_policy='depthwise', refresh_leaf=True, process_type='default', predictor= 'cpu_predictor', labels = [0,1,2,3]): 
    model = XGBClassifier(max_depth = max_depth, eta = eta, gamma = gamma,min_child_weight=min_child_weight,subsample=subsample, max_delta_step= max_delta_step,colsample_bytree=colsample_bytree,colsample_bylevel=colsample_bylevel,colsample_bynode=colsample_bynode,alpha=alpha,reg_lambda=reg_lambda,grow_policy=grow_policy, tree_method=tree_method,refresh_leaf=refresh_leaf,process_type=process_type, predictor= predictor,objective = 'reg:logistic')
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return model, y_pred,metric.get_metrics(y_pred,y_test, lb=labels)[2]



from sklearn.linear_model import LogisticRegression
## L1 one is good , l2 would be used
## very good at f class recall
## solver = ['newton-cg', 'lbfgs', 'liblinear'are all good, ensemble with all would be good

## false dual is better
def logisticRegress(X_train, y_train, X_test, y_test, penalty='l2', dual=False, tol=0.0001, C=100, fit_intercept=True, intercept_scaling=10, class_weight='balanced', random_state=None, solver='warn', max_iter=100, multi_class='warn', verbose=0, warm_start=False, n_jobs=None, labels = [0,1,2,3]):
    lr = LogisticRegression(penalty=penalty, dual=dual, tol=tol, C=C, fit_intercept=fit_intercept, intercept_scaling=intercept_scaling, class_weight=class_weight, random_state=random_state, solver=solver, max_iter=max_iter, multi_class=multi_class, verbose=verbose, warm_start=warm_start, n_jobs=n_jobs)
        # dual=dual, tol=tol, C=C, fit_intercept=fit_intercept, intercept_scaling=1, class_weight=None, random_state=None, solver=’warn’, max_iter=100, multi_class=’warn’, verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
    lr.fit(X_train, y_train.ravel())  
    y_pred = lr.predict(X_test)
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return lr,y_pred, metric.get_metrics(y_pred,y_test, lb=labels)[2]



from sklearn.ensemble import AdaBoostClassifier

from sklearn import svm

def ada(X_train, y_train, X_test, y_test,labels = [0,1,2,3]):

    svm_model_poly = svm.SVC(C=10,  kernel='linear', degree=3, gamma='auto', 
                        coef0=0.0, shrinking=True, probability=True, tol=0.1, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None)

    ada = AdaBoostClassifier(base_estimator=svm_model_poly, n_estimators=50 )
    ada.fit(X_train, y_train)  
    y_pred = ada.predict(X_test)
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return ada, y_pred, metric.get_metrics(y_pred,y_test, lb=labels)[2]


from sklearn import svm

## Number of feature at 50 or 100 is good too


def svm_model_linear(X_train, y_train, X_test, y_test, C=10, kernel='linear', degree=3, gamma='auto', 
                        coef0=0.0, shrinking=True, probability=True, tol=0.1, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None, labels = [0,1,2,3] ):
    
    svm_model_linear = svm.SVC(C=C, kernel=kernel, degree=degree, gamma=gamma, 
                        coef0=coef0, shrinking=shrinking, probability=probability, tol=tol, 
                        cache_size=cache_size, verbose=verbose, 
                        max_iter=max_iter, decision_function_shape=decision_function_shape, random_state=random_state) 
    
    svm_model_linear.fit(X_train, y_train)
    y_pred = svm_model_linear.predict(X_test)    
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return svm_model_linear, y_pred, metric.get_metrics(y_pred,y_test, lb=labels)[2]








In [9]:
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import VotingClassifier
import time
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm



def voting_ensemble(X_train, y_train, X_test,y_test, labels=[0,1,2,3]):
    svm_model_linear = svm.SVC(C=10, kernel='linear', degree=3, gamma='auto', 
                            coef0=0.0, shrinking=True, probability=True, tol=0.1, 
                            cache_size=200, verbose=False, 
                            max_iter=-1, decision_function_shape='ovo', random_state=None)

    svm_model_poly = svm.SVC(C=10, kernel='poly', degree=3, gamma='auto', 
                            coef0=0.001, shrinking=True, probability=True, tol=0.01, 
                            cache_size=200, verbose=False, 
                            max_iter=-1, decision_function_shape='ovo', random_state=None)


    rf = RandomForestClassifier(n_estimators=1000, criterion='gini', max_depth=16, min_samples_split=2, 
                                min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, 
                                max_features=50, max_leaf_nodes=None, class_weight='balanced')


    lr = LogisticRegression( penalty='l2', dual=False, tol=0.0001, C=100, fit_intercept=True, intercept_scaling=10, 
                            class_weight='balanced', random_state=None, solver='warn', max_iter=100, multi_class='warn',
                            verbose=0, warm_start=False, n_jobs=None)


    xgb = XGBClassifier(max_depth = 8, eta = 1, gamma = 0.001, min_child_weight=0.1,max_delta_step=10, 
                        subsample=0.6,colsample_bytree = 0.7, colsample_bylevel= 1, colsample_bynode=1, alpha=0, 
                        reg_lambda= 1, tree_method='exact', grow_policy='depthwise', refresh_leaf=True, 
                        process_type='default', predictor= 'cpu_predictor',objective = 'reg:logistic')




    eclf = VotingClassifier(estimators=[ ('xgb',xgb), ('lr',lr), ('svm_ln',svm_model_linear)], voting='hard')#, weights=[2,2,2,2])



    #clf1 = clf1.fit(X, y)
    #clf2 = clf2.fit(X, y)
    #clf3 = clf3.fit(X, y)
    eclf = eclf.fit(X_train, y_train)

    predict = eclf.predict(X_test)
    #scores = cross_val_score(X_train, y_train.data, iris.target, cv=10)
    #scores.mean()                             

    print(confusion_matrix(y_test,predict, labels=labels))  
    print(classification_report(y_test,predict, labels=labels))
    #print(metric.get_metrics(predict.ravel(),y_test.ravel(),lb=labels))
    
    return eclf, predict#, metric.get_metrics(predict.ravel(),y_test.ravel(), lb=labels)[2]

In [29]:
def ensemble(X_train, y_train, X_test, y_test, X_train_2,y_train_2, feature_rank ,score=0.01):   
    score = 0.01

    feature_good = feature_rank[feature_rank['rfscore'] >= score]['features'].values

    y_pred = svm_model_poly(X_train_2, y_train_2,X_test , y_test, labels=[0,1,2,3])[1]

    X_test_n_1 =X_test[y_pred != 1]
    y_test_n_1=y_test[y_pred != 1]

    y_pred_n = y_pred[y_pred == 1]
    y_true_1 = y_test[y_pred == 1]

   
    y_pred_voting_ensemble =voting_ensemble(np.asarray(X_train_2[rank[rank['rfscore'] >= score]['features'].values]), y_train_2,np.asarray( X_test_n_1[rank[rank['rfscore'] >= score]['features'].values]), np.asarray(y_test_n_1),  labels=[0,1,2,3])[1]

    X_test_n_2 =X_test_n_1[y_pred_voting_ensemble != 2]
    y_test_n_2=y_test_n_1[y_pred_voting_ensemble != 2]

    y_pred_voting_ensemble_n = y_pred_voting_ensemble[y_pred_voting_ensemble == 2]
    y_true_2 = y_test_n_1[y_pred_voting_ensemble == 2]


    y_pred_linear_D =Linear_D(np.asarray(X_train[feature_good]), y_test,np.asarray( X_test_n_2[feature_good]), y_test_n_2,  labels=[0,1,2,3])[1]

    X_test_n_3 =X_test_n_2[y_pred_linear_D != 2]
    y_test_n_3=y_test_n_2[y_pred_linear_D != 2]

    y_pred_linear_D_2 = y_pred_linear_D[y_pred_linear_D == 2]
    y_true_3 = y_test_n_2[y_pred_linear_D == 2]

    #y_true_1 = y_test_n_1[y_pred_voting_ensemble == 2]


    X_test_n_3 =X_test_n_2[y_pred_linear_D != 0]
    y_test_n_3=y_test_n_2[y_pred_linear_D != 0]

    y_pred_linear_D_0 = y_pred_linear_D[y_pred_linear_D == 0]
    y_true_4 = y_test_n_2[y_pred_linear_D == 0]

    y_svm = svm_model_poly(X_train_2, y_train_2, X_test_n_3, y_test_n_3, labels=[0,1,2,3])[1]


    X_test_n_4 =X_test_n_3[y_svm != 0]
    y_test_n_4=y_test_n_3[y_svm != 0]

    y_svm_n = y_svm[y_svm == 0]
    y_true_5 = y_test_n_3[y_svm == 0]

    y_v_e = svm_model_linear(X_train_2, y_train_2, X_test_n_4, y_test_n_4, labels=[0,1,2,3])[1]

    y_final_pred = np.hstack((y_pred_n,y_pred_voting_ensemble_n, y_pred_linear_D_2,y_pred_linear_D_0,y_svm_n,y_v_e))
    y_final_true = np.hstack((y_true_1,y_true_2,y_true_3,y_true_4,y_true_5,y_test_n_4))
    
    return y_final_pred, y_final_true
