In [1]:
from codes.python import load_DF_beats as DF
import numpy as np
from codes.python import metric
from codes. python import post_process_features_ex as post_features
import pandas as pd

from sklearn.metrics import classification_report, confusion_matrix 
ls = []
ls.extend(['N', 'L', 'R'])                    # N
ls.extend(['A', 'a', 'J', 'S', 'e', 'j'])     # SVEB 
ls.extend(['V', 'E'])                         # VEB
ls.extend(['F'])
#ls.extend([ 'P', '/', 'f', 'u'])
patient_l_1 = [101]
#patient_l_2 = [100]
patient_ls_1 = [101,106,108,109,112,114,115,116,118,119,122,124,201,203,205,207,208,209,215,220,223,230]
patient_ls_2 = [100,103,105,111,113,117,121,123,200,202,210,212,213,214,219,221,222,228,231,232,233,234]


ls2 = []
ls2.extend(["['N']","['L']", "['R']"])                    # N
ls2.extend(["['A']", "['a']", "['J']", "['S']",  "['e']", "['j']"])     # SVEB 
ls2.extend(["['V']", "['E']"])                         # VEB
ls2.extend(["['F']"])
#ls.extend([ "['P']","[ '/']"," ['f']", "['u']"])

In [2]:
np_clinic_1_old, np_clinic_2_old,np_non_var_1_old, np_non_var_2_old, np_class_ID_1_old, np_class_ID_2_old, patients_ls_1, patients_ls_2, DB1, DB2, DB1_V1, DB2_V1, DB1_non_cli, DB2_non_cli, DB1_dwt, DB2_dwt, DB1_dwt_V1, DB2_dwt_V1 = DF.get_all_dataframe(patient_l_1=patient_ls_1,patient_l_2=patient_ls_2 , ls=ls, ls2=ls2 )

In [3]:
np_clinic_1, np_clinic_2,np_non_var_1, np_non_var_2, np_class_ID_1, np_class_ID_2 = DF.get_all_dataframe_patient_specific(500,patient_l_1=patient_ls_1,patient_l_2=patient_ls_2 , ls=ls, ls2=ls2 )

done norm
row 0 done
done norm
row 1 done


In [4]:
np_class_ID_1_old = [int(i) for i in np_class_ID_1_old]
np_class_ID_2_old = [int(i) for i in np_class_ID_2_old]
X_train = np_clinic_1_old
X_test = np_clinic_2_old
y_train = np.asarray(np_class_ID_1_old)
y_test = np.asarray(np_class_ID_2_old)
input_size=X_train.shape[1]

In [58]:
np_class_ID_1 = [int(i) for i in np_class_ID_1]
np_class_ID_2 = [int(i) for i in np_class_ID_2]
X_train_new = np_clinic_1
X_test_new = np_clinic_2
y_train_new = np.asarray(np_class_ID_1)
y_test_new = np.asarray(np_class_ID_2)
input_size=X_train.shape[1]

In [59]:
from imblearn.under_sampling import RandomUnderSampler, ClusterCentroids

ada=RandomUnderSampler(sampling_strategy='all', replacement=True)
train, train_labels=ada.fit_sample(X_train_new, y_train_new)
test, test_labels=ada.fit_sample(X_test_new, y_test_new)

X_train_new = train
#X_test = test
y_train_new = train_labels
#y_test = test_labels
input_size=X_train.shape[1]

In [7]:
good_features_X = np.asarray(pd.read_csv("database/good_X_train.csv").iloc[:,1:263])
good_features_y = np.asarray(pd.read_csv("database/good_y_train.csv").iloc[:,1])


In [29]:
good_features_X = np.asarray(pd.read_csv("database/gooddata_X_train_no_outliers.csv").iloc[:,1:263])
good_features_y = np.asarray(pd.read_csv("database/gooddata_y_train_no_outliers.csv").iloc[:,1])

In [50]:
from sklearn.ensemble import IsolationForest
old_beats_train = y_train
n_beat = X_train[y_train==0]
s_beat = X_train[y_train==1]
v_beat = X_train[y_train==2]
f_beat = X_train[y_train==3]

print(len(n_beat), len(s_beat), len(v_beat),len(f_beat) )

n_beat_y = y_train[y_train==0]
s_beat_y = y_train[y_train==1]
v_beat_y = y_train[y_train==2]
f_beat_y = y_train[y_train==3]

print(len(n_beat_y), len(s_beat_y), len(v_beat_y),len(f_beat_y) )

outdetect = IsolationForest(max_features = input_size)

outliers_n = outdetect.fit_predict(n_beat)
outliers_s = outdetect.fit_predict(s_beat)
outliers_v = outdetect.fit_predict(v_beat)
outliers_f = outdetect.fit_predict(f_beat)

print(len(outliers_n), len(outliers_s), len(outliers_v),len(outliers_f) )

n_beat = n_beat[outliers_n==1]
s_beat = s_beat[outliers_s==1]
v_beat = v_beat[outliers_v==1]
f_beat = f_beat[outliers_f==1]

print(len(n_beat), len(s_beat), len(v_beat),len(f_beat) )

n_beat_y = n_beat_y[outliers_n==1]
s_beat_y = s_beat_y[outliers_s==1]
v_beat_y = v_beat_y[outliers_v==1]
f_beat_y = f_beat_y[outliers_f==1]

print(len(n_beat_y), len(s_beat_y), len(v_beat_y),len(f_beat_y) )

n_beat_y = n_beat_y.reshape(n_beat_y.shape[0],1)
s_beat_y = s_beat_y.reshape(s_beat_y.shape[0],1)
v_beat_y = v_beat_y.reshape(v_beat_y.shape[0],1)
f_beat_y = f_beat_y.reshape(f_beat_y.shape[0],1)


X_train = np.vstack((n_beat,s_beat, v_beat, f_beat))
y_train = np.vstack((n_beat_y,s_beat_y, v_beat_y, f_beat_y))


#outlers_test = outdetect.fit_predict(X_test)

45809 976 3788 414
45809 976 3788 414


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:213: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:223: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:417: DeprecationWarning: threshold_ attribute is deprecated in 0.20 and will be removed in 0.22.
  " be removed in 0.22.", DeprecationWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\ensemble\iforest.py:213: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-pa

45809 976 3788 414
41228 878 3409 372
41228 878 3409 372


In [ ]:

from sklearn.ensemble import IsolationForest
old_beats_train = y_test
n_beat = X_test[y_test==0]
s_beat = X_test[y_test==1]
v_beat = X_test[y_test==2]
f_beat = X_test[y_test==3]

print(len(n_beat), len(s_beat), len(v_beat),len(f_beat) )

n_beat_y = y_test[y_test==0]
s_beat_y = y_test[y_test==1]
v_beat_y = y_test[y_test==2]
f_beat_y = y_test[y_test==3]

print(len(n_beat_y), len(s_beat_y), len(v_beat_y),len(f_beat_y) )

outdetect = IsolationForest(max_features = input_size)

outliers_n = outdetect.fit_predict(n_beat)
outliers_s = outdetect.fit_predict(s_beat)
outliers_v = outdetect.fit_predict(v_beat)
outliers_f = outdetect.fit_predict(f_beat)

print(len(outliers_n), len(outliers_s), len(outliers_v),len(outliers_f) )

n_beat = n_beat[outliers_n==1]
s_beat = s_beat[outliers_s==1]
v_beat = v_beat[outliers_v==1]
f_beat = f_beat[outliers_f==1]

print(len(n_beat), len(s_beat), len(v_beat),len(f_beat) )

n_beat_y = n_beat_y[outliers_n==1]
s_beat_y = s_beat_y[outliers_s==1]
v_beat_y = v_beat_y[outliers_v==1]
f_beat_y = f_beat_y[outliers_f==1]

print(len(n_beat_y), len(s_beat_y), len(v_beat_y),len(f_beat_y) )

n_beat_y = n_beat_y.reshape(n_beat_y.shape[0],1)
s_beat_y = s_beat_y.reshape(s_beat_y.shape[0],1)
v_beat_y = v_beat_y.reshape(v_beat_y.shape[0],1)
f_beat_y = f_beat_y.reshape(f_beat_y.shape[0],1)


X_test = np.vstack((n_beat,s_beat, v_beat, f_beat))
y_test = np.vstack((n_beat_y,s_beat_y, v_beat_y, f_beat_y))


#outlers_test = outdetect.fit_predict(X_test)

In [5]:
from imblearn.under_sampling import RandomUnderSampler, ClusterCentroids

ada=RandomUnderSampler(sampling_strategy='all', replacement=True)
train, train_labels=ada.fit_sample(X_train, y_train)
test, test_labels=ada.fit_sample(X_test, y_test)

X_train = train
#X_test = test
y_train = train_labels
#y_test = test_labels
input_size=X_train.shape[1]

In [36]:
gooddata_X_train= X_train
gooddata_y_train = y_train 
#gooddata_X_test = X_test
#gooddata_y_test = y_test



df = pd.DataFrame(gooddata_X_train,columns=features_clinic)
df2 = pd.DataFrame(gooddata_y_train)
df.to_csv('database/gooddata_X_train_no_outliers.csv')
df2.to_csv('database/gooddata_y_train_no_outliers.csv')

In [ ]:
X_train=gooddata_X_train
y_train=gooddata_y_train 
X_test=gooddata_X_test 
y_test=gooddata_y_test 

In [48]:
predictions_svm_poly = svm_model_poly(X_train, y_train, X_test,y_test)

[[37945   984  3305  1787]
 [ 1399   471   105    75]
 [  233   221  1831   935]
 [   47     2     5   334]]
              precision    recall  f1-score   support

           0       0.96      0.86      0.91     44021
           1       0.28      0.23      0.25      2050
           2       0.35      0.57      0.43      3220
           3       0.11      0.86      0.19       388

   micro avg       0.82      0.82      0.82     49679
   macro avg       0.42      0.63      0.45     49679
weighted avg       0.88      0.82      0.84     49679

[0.35630862598200463, 1.4281087678274935, 0.356667908969439]


In [18]:
from sklearn import svm

## small C from 1 to 3 seems to be good for f class recalled
## degree 3 is better all around
## Tol at 0.01 seems best

def svm_model_poly(X_train, y_train, X_test, y_test, C=10, kernel='poly', degree=3, gamma='auto', 
                        coef0=0.001, shrinking=True, probability=True, tol=0.01, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None, labels = [0,1,2,3]):
    
    svm_model_linear = svm.SVC(C=C, kernel=kernel, degree=degree, gamma=gamma, 
                        coef0=coef0, shrinking=shrinking, probability=probability, tol=tol, 
                        cache_size=cache_size, verbose=verbose, 
                        max_iter=max_iter, decision_function_shape='ovo', random_state=random_state) 
    
    svm_model_linear.fit(X_train, y_train)
    y_pred = svm_model_linear.predict(X_test)    
    print(confusion_matrix(y_test,y_pred, labels=labels))  
    print(classification_report(y_test,y_pred))
    print(metric.get_metrics(y_pred,y_test,lb=labels))
    
    return svm_model_linear,y_pred, metric.get_metrics(y_pred,y_test, lb=labels)[2]

In [19]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

def Linear_D(X_train, y_train, X_test, y_test, labels = [0,1,2,3]):
    clf = LinearDiscriminantAnalysis()
    clf.fit(X_train, y_train)  
    y_pred = clf.predict(X_test)
    print(confusion_matrix(y_test,y_pred, labels = labels))  
    print(classification_report(y_test,y_pred, labels=labels))
    print(metric.get_metrics(y_pred,y_test, lb=labels))
    
    return clf, metric.get_metrics(y_pred,y_test,lb=labels)[2]

In [20]:
from sklearn.ensemble import RandomForestClassifier

## Number of feature at 50 or 100 is good too
## numner of estimators leaves at 1000 

def randomForest(X_train, y_train, X_test, y_test,n_estimators=1000, criterion='gini', max_depth=16, min_samples_split=2, min_samples_leaf=3, min_weight_fraction_leaf=0.0001,min_impurity_decrease=0.0, max_features=50, max_leaf_nodes=None, class_weight='balanced', labels = [0,1,2,3]):
    
    rf = RandomForestClassifier(n_estimators=n_estimators, criterion=criterion, max_depth=max_depth, min_samples_split=min_samples_split, min_samples_leaf=min_samples_leaf,min_weight_fraction_leaf=min_weight_fraction_leaf, class_weight=class_weight, min_impurity_decrease=min_impurity_decrease,max_features=max_features)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)    
    print(confusion_matrix(y_test,y_pred, labels=labels))  
    print(classification_report(y_test,y_pred, labels=labels))
    print(metric.get_metrics(y_pred,y_test, lb=labels))
    
    return rf, metric.get_metrics(y_pred,y_test, lb=labels)[2]


In [21]:
### xgbo is good for normal classes too
## do this one next 
## XGB is very goos for V class
## XGboost tree classifcation is good with 5 or more tree depth
from xgboost import XGBClassifier


def xgboost(X_train,y_train, X_test, y_test, max_depth = 8, eta = 1, gamma = 0.001, min_child_weight=0.1,max_delta_step=10, subsample=0.6,colsample_bytree = 0.7, colsample_bylevel= 1, colsample_bynode=1, alpha=0, reg_lambda= 1, tree_method='exact', grow_policy='depthwise', refresh_leaf=True, process_type='default', predictor= 'cpu_predictor', labels = [0,1,2,3]): 
    model = XGBClassifier(max_depth = max_depth, eta = eta, gamma = gamma,min_child_weight=min_child_weight,subsample=subsample, max_delta_step= max_delta_step,colsample_bytree=colsample_bytree,colsample_bylevel=colsample_bylevel,colsample_bynode=colsample_bynode,alpha=alpha,reg_lambda=reg_lambda,grow_policy=grow_policy, tree_method=tree_method,refresh_leaf=refresh_leaf,process_type=process_type, predictor= predictor,objective = 'reg:logistic')
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return model, metric.get_metrics(y_pred,y_test, lb=labels)[2]

In [22]:
from sklearn.linear_model import LogisticRegression
## L1 one is good , l2 would be used
## very good at f class recall
## solver = ['newton-cg', 'lbfgs', 'liblinear'are all good, ensemble with all would be good

## false dual is better
def logisticRegress(X_train, y_train, X_test, y_test, penalty='l2', dual=False, tol=0.0001, C=100, fit_intercept=True, intercept_scaling=10, class_weight='balanced', random_state=None, solver='warn', max_iter=100, multi_class='warn', verbose=0, warm_start=False, n_jobs=None, labels = [0,1,2,3]):
    lr = LogisticRegression(penalty=penalty, dual=dual, tol=tol, C=C, fit_intercept=fit_intercept, intercept_scaling=intercept_scaling, class_weight=class_weight, random_state=random_state, solver=solver, max_iter=max_iter, multi_class=multi_class, verbose=verbose, warm_start=warm_start, n_jobs=n_jobs)
        # dual=dual, tol=tol, C=C, fit_intercept=fit_intercept, intercept_scaling=1, class_weight=None, random_state=None, solver=’warn’, max_iter=100, multi_class=’warn’, verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
    lr.fit(X_train, y_train.ravel())  
    y_pred = lr.predict(X_test)
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return lr, metric.get_metrics(y_pred,y_test, lb=labels)[2]

In [23]:
from sklearn.ensemble import AdaBoostClassifier

from sklearn import svm

def ada(X_train, y_train, X_test, y_test,labels = [0,1,2,3]):

    svm_model_poly = svm.SVC(C=10, kernel='poly', degree=3, gamma='auto', 
                            coef0=0.001, shrinking=True, probability=True, tol=0.01, 
                            cache_size=200, verbose=False, 
                            max_iter=-1, decision_function_shape='ovo', random_state=None)

    ada = AdaBoostClassifier(base_estimator=svm_model_poly, n_estimators=50 )
    ada.fit(X_train, y_train)  
    y_pred = ada.predict(X_test)
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return ada, metric.get_metrics(y_pred,y_test, lb=labels)[2]

In [24]:
from sklearn import svm

## Number of feature at 50 or 100 is good too


def svm_model_linear(X_train, y_train, X_test, y_test, C=10, kernel='linear', degree=3, gamma='auto', 
                        coef0=0.0, shrinking=True, probability=True, tol=0.1, 
                        cache_size=200, verbose=False, 
                        max_iter=-1, decision_function_shape='ovo', random_state=None, labels = [0,1,2,3] ):
    
    svm_model_linear = svm.SVC(C=C, kernel=kernel, degree=degree, gamma=gamma, 
                        coef0=coef0, shrinking=shrinking, probability=probability, tol=tol, 
                        cache_size=cache_size, verbose=verbose, 
                        max_iter=max_iter, decision_function_shape='ovo', random_state=random_state) 
    
    svm_model_linear.fit(X_train, y_train)
    y_pred = svm_model_linear.predict(X_test)    
    print(confusion_matrix(y_test.ravel(),y_pred.ravel(), labels=labels))  
    print(classification_report(y_test.ravel(),y_pred.ravel(), labels=labels))
    print(metric.get_metrics(y_pred.ravel(),y_test.ravel(), lb=labels))
    
    return svm_model_linear, metric.get_metrics(y_pred,y_test, lb=labels)[2]

In [25]:
# rr, HOS, myMorph training features
train_rr=np.loadtxt('rr-train.txt', dtype=float)[:,1:] # extract class labels
train_hos=np.loadtxt('hos_train.txt', dtype=float)
train_mmorph=np.loadtxt('morph_train.txt', dtype=float)

# rr, HOS, myMorph testing features
test_rr=np.loadtxt('rr-test.txt', dtype=float)[:,1:] # extract class labels
test_rr=np.loadtxt('rr-test.txt', dtype=float)[:,1:] # extract class labels
test_hos=np.loadtxt('hos_test.txt', dtype=float)
test_mmorph=np.loadtxt('morph_test.txt', dtype=float)

# training and testing class labels.
train_labels=np.loadtxt('labels_train.txt', dtype=str)
test_labels=np.loadtxt('labels_test.txt', dtype=str)

# aggregate all features.
train=np.hstack((train_rr, train_hos, train_mmorph))
test=np.hstack((test_rr, test_hos, test_mmorph))

#train=np.hstack((train_rr, train_mmorph))
#test=np.hstack((test_rr, test_mmorph))


from imblearn.under_sampling import RandomUnderSampler, ClusterCentroids

ada=RandomUnderSampler(sampling_strategy='all', replacement=True)
train, train_labels=ada.fit_sample(train, train_labels)
#test, test_labels=ada.fit_sample(test_rr, test_labels)





ada=RandomUnderSampler(sampling_strategy='all', replacement=True)
#new_train, new_train_labels=ada.fit_sample(df[rank], y_train)
#new_x_test, new_y_test=ada.fit_sample(X_test, y_test)


#input_size=X_train.shape[1]


In [40]:
score = 0.02
#Linear_D(train, train_labels, test, test_labels, labels=['N','S','V','F'])
svm_model_poly(good_features_X, good_features_y,X_test , y_test, labels=[0,1,2,3])
xgboost(X_train_df[df[df['rfscore'] >= score]['features'].values], good_features_y, X_test_df[df[df['rfscore'] >= score]['features'].values], y_test, labels=[0,1,2,3])
#svm_model_poly(X_train_df[df[df['rfscore'] >= score]['features'].values], good_features_y,X_test_df[df[df['rfscore'] >= score]['features'].values] , y_test, labels=[0,1,2,3])[0]
logisticRegress(X_train_df[df[df['rfscore'] >= score]['features'].values], good_features_y, X_test_df[df[df['rfscore'] >= score]['features'].values], y_test, labels=[0,1,2,3])
Linear_D(X_train_df[df[df['rfscore'] >= score]['features'].values], good_features_y, X_test_df[df[df['rfscore'] >= score]['features'].values], y_test,  labels=[0,1,2,3])
#ada(X_train_df[rank['features'].values], good_features_y, X_test_df[rank['features'].values], y_test,  labels=[0,1,2,3])
svm_model_linear(X_train_df[df[df['rfscore'] >= score]['features'].values], good_features_y, X_test_df[df[df['rfscore'] >= score]['features'].values], y_test,  labels=[0,1,2,3])

#randomForest(train, train_labels, test, test_labels, max_depth=5, labels=['N','S','V','F'])
#rf = randomForest(X_train_new, y_train_new ,X_test_new , y_test_new, labels=[0,1,2,3])[0]
#Linear_D(np_non_var_1_old, y_train, np_non_var_2_old, y_test, labels=[0,1,2,3])

[[34986   635  3908  4492]
 [  502  1336   122    90]
 [  198    51  2525   446]
 [   26     0     7   355]]
              precision    recall  f1-score   support

           0       0.98      0.79      0.88     44021
           1       0.66      0.65      0.66      2050
           2       0.38      0.78      0.52      3220
           3       0.07      0.91      0.12       388

   micro avg       0.79      0.79      0.79     49679
   macro avg       0.52      0.79      0.54     49679
weighted avg       0.92      0.79      0.84     49679

[0.4007485524244452, 2.4813919785105343, 0.5105482735260394]
[[33692  2528  3085  4716]
 [ 1283   356   389    22]
 [   72    48  3056    44]
 [   31     1    69   287]]
              precision    recall  f1-score   support

           0       0.96      0.77      0.85     44021
           1       0.12      0.17      0.14      2050
           2       0.46      0.95      0.62      3220
           3       0.06      0.74      0.11       388

   micro avg  

C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\chont\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[32181  3319   379  8142]
 [  263  1407   348    32]
 [   50   285  2546   339]
 [   13     0    12   363]]
              precision    recall  f1-score   support

           0       0.99      0.73      0.84     44021
           1       0.28      0.69      0.40      2050
           2       0.78      0.79      0.78      3220
           3       0.04      0.94      0.08       388

   micro avg       0.73      0.73      0.73     49679
   macro avg       0.52      0.79      0.53     49679
weighted avg       0.94      0.73      0.81     49679

[0.35335561088176926, 2.5328450239649096, 0.49328343343649833]


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


[[30913  4469   126  8513]
 [  528  1165   319    38]
 [   40   251  2362   567]
 [   13     0     7   368]]
              precision    recall  f1-score   support

           0       0.98      0.70      0.82     44021
           1       0.20      0.57      0.29      2050
           2       0.84      0.73      0.78      3220
           3       0.04      0.95      0.07       388

   micro avg       0.70      0.70      0.70     49679
   macro avg       0.51      0.74      0.49     49679
weighted avg       0.93      0.70      0.79     49679

[0.30093057297025216, 2.339168528977189, 0.4428613526072747]
[[34264  2626   435  6696]
 [  270  1455   307    18]
 [  123   622  2238   237]
 [   15     0    11   362]]
              precision    recall  f1-score   support

           0       0.99      0.78      0.87     44021
           1       0.31      0.71      0.43      2050
           2       0.75      0.70      0.72      3220
           3       0.05      0.93      0.09       388

   micro avg  

(SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
   decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
   max_iter=-1, probability=True, random_state=None, shrinking=True,
   tol=0.1, verbose=False), 0.5009529762854108)

In [42]:
score = 0.1
#Linear_D(train, train_labels, test, test_labels, labels=['N','S','V','F'])
svm_model_poly(good_features_X, good_features_y,X_test , y_test, labels=[0,1,2,3])
xgboost(good_features_X, good_features_y, X_test, y_test, labels=[0,1,2,3])
#svm_model_poly(X_train_df[df[df['rfscore'] >= score]['features'].values], good_features_y,X_test_df[df[df['rfscore'] >= score]['features'].values] , y_test, labels=[0,1,2,3])[0]
logisticRegress(good_features_X, good_features_y, X_test, y_test, labels=[0,1,2,3])
Linear_D(good_features_X, good_features_y, X_test, y_test, labels=[0,1,2,3])
#ada(X_train_df[rank['features'].values], good_features_y, X_test_df[rank['features'].values], y_test,  labels=[0,1,2,3])
svm_model_linear(good_features_X, good_features_y, X_test, y_test, labels=[0,1,2,3])

#randomForest(train, train_labels, test, test_labels, max_depth=5, labels=['N','S','V','F'])
#rf = randomForest(X_train_new, y_train_new ,X_test_new , y_test_new, labels=[0,1,2,3])[0]
#Linear_D(np_non_var_1_old, y_train, np_non_var_2_old, y_test, labels=[0,1,2,3])

[[34986   635  3908  4492]
 [  502  1336   122    90]
 [  198    51  2525   446]
 [   26     0     7   355]]
              precision    recall  f1-score   support

           0       0.98      0.79      0.88     44021
           1       0.66      0.65      0.66      2050
           2       0.38      0.78      0.52      3220
           3       0.07      0.91      0.12       388

   micro avg       0.79      0.79      0.79     49679
   macro avg       0.52      0.79      0.54     49679
weighted avg       0.92      0.79      0.84     49679

[0.4007485524244452, 2.4813919785105343, 0.5105482735260394]


ValueError: feature_names mismatch: ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36', 'f37', 'f38', 'f39', 'f40', 'f41', 'f42', 'f43', 'f44', 'f45', 'f46', 'f47', 'f48', 'f49', 'f50', 'f51', 'f52', 'f53', 'f54', 'f55', 'f56', 'f57', 'f58', 'f59', 'f60', 'f61', 'f62', 'f63', 'f64', 'f65', 'f66', 'f67', 'f68', 'f69', 'f70', 'f71', 'f72', 'f73', 'f74', 'f75', 'f76', 'f77', 'f78', 'f79', 'f80', 'f81', 'f82', 'f83', 'f84', 'f85', 'f86', 'f87', 'f88', 'f89', 'f90', 'f91', 'f92', 'f93', 'f94', 'f95', 'f96', 'f97', 'f98', 'f99', 'f100', 'f101', 'f102', 'f103', 'f104', 'f105', 'f106', 'f107', 'f108', 'f109', 'f110', 'f111', 'f112', 'f113', 'f114', 'f115', 'f116', 'f117', 'f118', 'f119', 'f120', 'f121', 'f122', 'f123', 'f124', 'f125', 'f126', 'f127', 'f128', 'f129', 'f130', 'f131', 'f132', 'f133', 'f134', 'f135', 'f136', 'f137', 'f138', 'f139', 'f140', 'f141', 'f142', 'f143', 'f144', 'f145', 'f146', 'f147', 'f148', 'f149', 'f150', 'f151', 'f152', 'f153', 'f154', 'f155', 'f156', 'f157', 'f158', 'f159', 'f160', 'f161', 'f162', 'f163', 'f164', 'f165', 'f166', 'f167', 'f168', 'f169', 'f170', 'f171', 'f172', 'f173', 'f174', 'f175', 'f176', 'f177', 'f178', 'f179', 'f180', 'f181', 'f182', 'f183', 'f184', 'f185', 'f186', 'f187', 'f188', 'f189', 'f190', 'f191', 'f192', 'f193', 'f194', 'f195', 'f196', 'f197', 'f198', 'f199', 'f200', 'f201', 'f202', 'f203', 'f204', 'f205', 'f206', 'f207', 'f208', 'f209', 'f210', 'f211', 'f212', 'f213', 'f214', 'f215', 'f216', 'f217', 'f218', 'f219', 'f220', 'f221', 'f222', 'f223', 'f224', 'f225', 'f226', 'f227', 'f228', 'f229', 'f230', 'f231', 'f232', 'f233', 'f234', 'f235', 'f236', 'f237', 'f238', 'f239', 'f240', 'f241', 'f242', 'f243', 'f244', 'f245', 'f246', 'f247', 'f248', 'f249', 'f250', 'f251', 'f252', 'f253', 'f254', 'f255', 'f256', 'f257', 'f258', 'f259', 'f260', 'f261'] ['R_duration', 'R_height', 'R_amp0', 'R_amp1', 'R_amp2', 'R_amp3', 'R_amp4', 'R_amp5', 'R_amp6', 'R_amp7', 'R_amp8', 'R_amp9', 'R_prominence', 'R_areas', 'Q_duration', 'Q_height', 'Q_amp0', 'Q_amp1', 'Q_amp2', 'Q_amp3', 'Q_amp4', 'Q_amp5', 'Q_amp6', 'Q_amp7', 'Q_amp8', 'Q_amp9', 'Q_prominence', 'Q_areas', 'S_duration', 'S_height', 'S_amp0', 'S_amp1', 'S_amp2', 'S_amp3', 'S_amp4', 'S_amp5', 'S_amp6', 'S_amp7', 'S_amp8', 'S_amp9', 'S_prominence', 'S_areas', 'P_duration', 'P_height', 'P_amp0', 'P_amp1', 'P_amp2', 'P_amp3', 'P_amp4', 'P_amp5', 'P_amp6', 'P_amp7', 'P_amp8', 'P_amp9', 'P_prominence', 'P_areas', 'P_neg_duration', 'P_neg_height', 'P_neg_amp0', 'P_neg_amp1', 'P_neg_amp2', 'P_neg_amp3', 'P_neg_amp4', 'P_neg_amp5', 'P_neg_amp6', 'P_neg_amp7', 'P_neg_amp8', 'P_neg_amp9', 'P_neg_prominence', 'P_neg_areas', 'T_duration', 'T_height', 'T_amp0', 'T_amp1', 'T_amp2', 'T_amp3', 'T_amp4', 'T_amp5', 'T_amp6', 'T_amp7', 'T_amp8', 'T_amp9', 'T_prominence', 'T_areas', 'T_neg_durations', 'T_neg_height', 'T_neg_amp0', 'T_neg_amp1', 'T_neg_amp2', 'T_neg_amp3', 'T_neg_amp4', 'T_neg_amp5', 'T_neg_amp6', 'T_neg_amp7', 'T_neg_amp8', 'T_neg_amp9', 'T_neg_prominence', 'T_neg_areas', 'rr_int_pre', 'rr_int_post', 'rr_int_10', 'rr_int_50', 'rr_int_all', 'QRS_int', 'QRS_int_10', 'QRS_int_50', 'PQ_int', 'PQ_int_10', 'PQ_int_50', 'PR_int', 'PR_int_10', 'PR_int_50', 'ST_int', 'ST_int_10', 'ST_int_50', 'RT_int', 'RT_int_10', 'RT_int_50', 'PT_int', 'PT_int_10', 'PT_int_50', 'RP', 'TR', 'neg_RQ', 'neg_PR', 'neg_ST', 'neg_RT', 'neg_PT', 'P_neg_T', 'neg_P_neg_T', 'R_duration_V', 'R_height_V', 'R_amp0_V', 'R_amp1_V', 'R_amp2_V', 'R_amp3_V', 'R_amp4_V', 'R_amp5_V', 'R_amp6_V', 'R_amp7_V', 'R_amp8_V', 'R_amp9_V', 'R_prominence_V', 'R_areas_V', 'Q_duration_V', 'Q_height_V', 'Q_amp0_V', 'Q_amp1_V', 'Q_amp2_V', 'Q_amp3_V', 'Q_amp4_V', 'Q_amp5_V', 'Q_amp6_V', 'Q_amp7_V', 'Q_amp8_V', 'Q_amp9_V', 'Q_prominence_V', 'Q_areas_V', 'S_duration_V', 'S_height_V', 'S_amp0_V', 'S_amp1_V', 'S_amp2_V', 'S_amp3_V', 'S_amp4_V', 'S_amp5_V', 'S_amp6_V', 'S_amp7_V', 'S_amp8_V', 'S_amp9_V', 'S_prominence_V', 'S_areas_V', 'P_duration_V', 'P_height_V', 'P_amp0_V', 'P_amp1_V', 'P_amp2_V', 'P_amp3_V', 'P_amp4_V', 'P_amp5_V', 'P_amp6_V', 'P_amp7_V', 'P_amp8_V', 'P_amp9_V', 'P_prominence_V', 'P_areas_V', 'P_neg_duration_V', 'P_neg_height_V', 'P_neg_amp0_V', 'P_neg_amp1_V', 'P_neg_amp2_V', 'P_neg_amp3_V', 'P_neg_amp4_V', 'P_neg_amp5_V', 'P_neg_amp6_V', 'P_neg_amp7_V', 'P_neg_amp8_V', 'P_neg_amp9_V', 'P_neg_prominence_V', 'P_neg_areas_V', 'T_duration_V', 'T_height_V', 'T_amp0_V', 'T_amp1_V', 'T_amp2_V', 'T_amp3_V', 'T_amp4_V', 'T_amp5_V', 'T_amp6_V', 'T_amp7_V', 'T_amp8_V', 'T_amp9_V', 'T_prominence_V', 'T_areas_V', 'T_neg_durations_V', 'T_neg_height_V', 'T_neg_amp0_V', 'T_neg_amp1_V', 'T_neg_amp2_V', 'T_neg_amp3_V', 'T_neg_amp4_V', 'T_neg_amp5_V', 'T_neg_amp6_V', 'T_neg_amp7_V', 'T_neg_amp8_V', 'T_neg_amp9_V', 'T_neg_prominence_V', 'T_neg_areas_V', 'rr_int_pre_V', 'rr_int_post_V', 'rr_int_10_V', 'rr_int_50_V', 'rr_int_all_V', 'QRS_int_V', 'QRS_int_10_V', 'QRS_int_50_V', 'PQ_int_V', 'PQ_int_10_V', 'PQ_int_50_V', 'PR_int_V', 'PR_int_10_V', 'PR_int_50_V', 'ST_int_V', 'ST_int_10_V', 'ST_int_50_V', 'RT_int_V', 'RT_int_10_V', 'RT_int_50_V', 'PT_int_V', 'PT_int_10_V', 'PT_int_50_V', 'RP_V', 'TR_V', 'neg_RQ_V', 'neg_PR_V', 'neg_ST_V', 'neg_RT_V', 'neg_PT_V', 'P_neg_T_V', 'neg_P_neg_T_V', 'dtw1', 'dtw2']
expected f214, f93, f102, f46, f105, f125, f182, f196, f229, f258, f65, f151, f218, f139, f224, f195, f33, f56, f31, f18, f118, f103, f9, f48, f39, f4, f245, f115, f34, f167, f148, f26, f17, f44, f86, f109, f185, f226, f260, f63, f217, f91, f10, f72, f113, f249, f236, f187, f252, f40, f152, f121, f162, f190, f163, f88, f180, f2, f110, f183, f154, f209, f14, f142, f19, f165, f75, f23, f20, f94, f235, f248, f250, f52, f155, f108, f212, f160, f131, f129, f207, f179, f261, f92, f120, f66, f173, f64, f0, f80, f145, f169, f3, f51, f135, f166, f146, f222, f53, f227, f193, f8, f77, f54, f144, f156, f253, f194, f96, f211, f233, f254, f177, f204, f117, f221, f161, f27, f15, f42, f184, f59, f12, f97, f90, f138, f6, f5, f76, f176, f191, f239, f41, f237, f68, f198, f82, f157, f208, f87, f78, f192, f189, f197, f219, f16, f127, f71, f247, f47, f257, f172, f111, f220, f58, f60, f171, f28, f243, f25, f100, f175, f61, f123, f79, f232, f69, f158, f74, f85, f95, f244, f231, f210, f149, f188, f106, f49, f246, f36, f35, f114, f1, f234, f242, f255, f251, f37, f83, f29, f101, f147, f13, f225, f141, f107, f200, f24, f168, f112, f186, f153, f201, f104, f181, f81, f30, f43, f159, f136, f215, f122, f89, f134, f143, f132, f205, f98, f213, f99, f128, f203, f124, f170, f50, f22, f11, f45, f57, f84, f116, f199, f73, f126, f238, f21, f67, f70, f7, f240, f230, f137, f150, f55, f174, f133, f62, f32, f140, f178, f241, f259, f256, f38, f130, f206, f164, f228, f216, f223, f202, f119 in input data
training data did not have the following fields: Q_amp2, R_amp8, PT_int, T_amp2, Q_duration, P_neg_amp0, T_areas_V, PT_int_10, PR_int_10_V, S_amp8_V, P_duration_V, P_neg_amp5, Q_amp5_V, P_neg_amp9, T_neg_amp9_V, P_neg_amp9_V, P_amp4, neg_ST, P_amp2, R_height_V, R_amp7_V, P_amp3, P_prominence_V, Q_amp4, R_amp8_V, T_areas, T_neg_durations_V, R_amp0_V, P_amp9, rr_int_all_V, RP_V, Q_areas_V, R_amp5_V, neg_PR_V, Q_amp5, T_amp6, S_height_V, P_neg_T_V, T_amp4, R_prominence, T_amp3, T_neg_amp5, T_neg_prominence, T_neg_amp4, R_duration_V, S_amp0_V, P_neg_amp2, P_amp5_V, P_areas_V, R_amp1, R_amp4_V, Q_amp8_V, T_amp5, P_neg_amp8, neg_RT_V, Q_amp9, S_amp7, P_neg_areas_V, ST_int_50_V, P_neg_amp7_V, T_height_V, T_amp9_V, P_duration, Q_height, rr_int_post_V, P_neg_prominence_V, T_amp1_V, S_amp3_V, T_neg_amp0, S_amp1_V, S_amp9_V, S_height, S_amp7_V, P_amp0_V, T_neg_amp1_V, T_neg_amp0_V, PQ_int_10_V, neg_RQ_V, P_neg_amp7, T_amp7, P_neg_amp4_V, P_neg_amp4, T_height, RT_int_10_V, P_amp1, QRS_int_50, PQ_int, Q_amp0, P_neg_amp1, TR, P_neg_amp8_V, RT_int_V, S_amp5_V, S_amp9, TR_V, R_amp7, P_neg_T, S_amp4, neg_RQ, P_neg_amp0_V, P_amp5, T_amp1, Q_areas, P_neg_areas, T_amp9, neg_RT, T_neg_amp2, S_amp5, Q_amp7_V, T_neg_height, P_neg_duration_V, RT_int, R_amp3_V, T_amp5_V, T_neg_prominence_V, ST_int_10_V, T_neg_amp4_V, P_amp9_V, T_duration_V, T_neg_areas_V, P_height_V, T_neg_amp1, P_amp6_V, S_amp2, Q_amp6, neg_P_neg_T, R_amp4, neg_PR, PQ_int_10, P_amp2_V, T_neg_amp7_V, rr_int_pre, PR_int_50_V, T_neg_amp3, P_amp3_V, R_amp5, T_amp7_V, T_neg_height_V, P_amp7, P_height, P_prominence, S_amp6_V, P_amp4_V, PR_int_V, R_amp1_V, R_areas_V, S_prominence_V, rr_int_all, T_amp6_V, rr_int_50_V, S_prominence, P_amp1_V, rr_int_10_V, QRS_int_50_V, P_neg_amp3, R_amp2, P_neg_amp6_V, S_amp1, QRS_int_V, T_amp3_V, neg_ST_V, R_amp6_V, P_areas, Q_duration_V, PT_int_50_V, R_amp6, Q_amp3_V, T_amp8_V, R_height, Q_amp1_V, rr_int_50, PT_int_V, Q_amp7, RT_int_50, T_neg_durations, S_areas, R_prominence_V, T_amp8, Q_amp1, PQ_int_V, Q_prominence, P_neg_height, PR_int, PT_int_10_V, neg_PT, P_amp8, ST_int, S_amp2_V, PQ_int_50, P_amp7_V, S_amp6, P_amp0, Q_prominence_V, T_amp0_V, PR_int_50, neg_PT_V, S_amp8, P_neg_amp1_V, T_amp0, dtw2, ST_int_50, ST_int_V, R_amp9_V, R_amp0, P_amp8_V, R_amp3, P_amp6, T_neg_amp6, QRS_int, P_neg_amp5_V, RT_int_50_V, T_amp4_V, Q_amp6_V, S_amp4_V, RT_int_10, Q_amp3, T_duration, T_neg_amp9, ST_int_10, R_amp2_V, Q_amp0_V, Q_height_V, QRS_int_10_V, T_neg_areas, Q_amp8, T_amp2_V, S_amp0, QRS_int_10, T_neg_amp7, P_neg_amp2_V, neg_P_neg_T_V, P_neg_height_V, Q_amp4_V, T_prominence_V, S_duration, P_neg_amp6, T_neg_amp6_V, PQ_int_50_V, P_neg_amp3_V, T_neg_amp3_V, S_duration_V, T_neg_amp2_V, T_neg_amp8_V, PR_int_10, Q_amp2_V, rr_int_pre_V, T_neg_amp8, rr_int_post, T_prominence, PT_int_50, rr_int_10, S_amp3, R_amp9, RP, T_neg_amp5_V, R_duration, P_neg_duration, P_neg_prominence, dtw1, R_areas, S_areas_V, Q_amp9_V

In [46]:
good_features_y.shape

(1656,)

In [38]:
Linear_D(X_train[df[df['rfscore'] >= score]['features'].values], y_train, X_test[df[df['rfscore'] >= score]['features'].values], y_test,  labels=[0,1,2,3])


[[40286   194    90  3451]
 [ 1725    28   260    37]
 [  341    55  2421   403]
 [   26     0     6   356]]
              precision    recall  f1-score   support

           0       0.95      0.92      0.93     44021
           1       0.10      0.01      0.02      2050
           2       0.87      0.75      0.81      3220
           3       0.08      0.92      0.15       388

   micro avg       0.87      0.87      0.87     49679
   macro avg       0.50      0.65      0.48     49679
weighted avg       0.90      0.87      0.88     49679

[0.44652078814722895, 1.7384090282630495, 0.44056152260649567]


C:\Users\chont\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


(LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
               solver='svd', store_covariance=False, tol=0.0001),
 0.44056152260649567)

rf.feature_importances_

In [60]:
norm_var_1_clinic = post_features.normalised_values_multiples(X_train_new)
norm_var_2_clinic = post_features.normalised_values_multiples(np_clinic_2)

norm_var_1_non = post_features.normalised_values_multiples(np_non_var_1)
norm_var_2_non = post_features.normalised_values_multiples(np_non_var_2)

X_train_new = np.hstack((X_train_new,norm_var_1_clinic))
X_test_new = np.hstack((np_clinic_2,norm_var_2_clinic))


done norm
row 0 done
done norm
row 1 done
done norm
row 2 done
done norm
row 3 done
done norm
row 4 done
done norm
row 5 done
done norm
row 6 done
done norm
row 7 done
done norm
row 8 done
done norm
row 9 done
done norm
row 10 done
done norm
row 11 done
done norm
row 12 done
done norm
row 13 done
done norm
row 14 done
done norm
row 15 done
done norm
row 16 done
done norm
row 17 done
done norm
row 18 done
done norm
row 19 done
done norm
row 20 done
done norm
row 21 done
done norm
row 22 done
done norm
row 23 done
done norm
row 24 done
done norm
row 25 done
done norm
row 26 done
done norm
row 27 done
done norm
row 28 done
done norm
row 29 done
done norm
row 30 done
done norm
row 31 done
done norm
row 32 done
done norm
row 33 done
done norm
row 34 done
done norm
row 35 done
done norm
row 36 done
done norm
row 37 done
done norm
row 38 done
done norm
row 39 done
done norm
row 40 done
done norm
row 41 done
done norm
row 42 done
done norm
row 43 done
done norm
row 44 done
done norm
row 45 don

done norm
row 115 done
done norm
row 116 done
done norm
row 117 done
done norm
row 118 done
done norm
row 119 done
done norm
row 120 done
done norm
row 121 done
done norm
row 122 done
done norm
row 123 done
done norm
row 124 done
done norm
row 125 done
done norm
row 126 done
done norm
row 127 done
done norm
row 128 done
done norm
row 129 done
done norm
row 130 done
done norm
row 131 done
done norm
row 132 done
done norm
row 133 done
done norm
row 134 done
done norm
row 135 done
done norm
row 136 done
done norm
row 137 done
done norm
row 138 done
done norm
row 139 done
done norm
row 140 done
done norm
row 141 done
done norm
row 142 done
done norm
row 143 done
done norm
row 144 done
done norm
row 145 done
done norm
row 146 done
done norm
row 147 done
done norm
row 148 done
done norm
row 149 done
done norm
row 150 done
done norm
row 151 done
done norm
row 152 done
done norm
row 153 done
done norm
row 154 done
done norm
row 155 done
done norm
row 156 done
done norm
row 157 done
done norm
r

done norm
row 78 done
done norm
row 79 done
done norm
row 80 done
done norm
row 81 done
done norm
row 82 done
done norm
row 83 done
done norm
row 84 done
done norm
row 85 done
done norm
row 86 done
done norm
row 87 done
done norm
row 88 done
done norm
row 89 done
done norm
row 90 done
done norm
row 91 done
done norm
row 92 done
done norm
row 93 done
done norm
row 94 done
done norm
row 95 done
done norm
row 96 done
done norm
row 97 done
done norm
row 98 done
done norm
row 99 done
done norm
row 100 done
done norm
row 101 done
done norm
row 102 done
done norm
row 103 done
done norm
row 104 done
done norm
row 105 done
done norm
row 106 done
done norm
row 107 done
done norm
row 108 done
done norm
row 109 done
done norm
row 110 done
done norm
row 111 done
done norm
row 112 done
done norm
row 113 done
done norm
row 114 done
done norm
row 115 done
done norm
row 116 done
done norm
row 117 done
done norm
row 118 done
done norm
row 119 done
done norm
row 120 done
done norm
row 121 done
done norm


In [61]:
rf = randomForest(X_train_new, y_train_new ,X_test_new , y_test_new, labels=[0,1,2,3])[0]

rf.feature_importances_

[[26230  2439  1108  4357]
 [  210  1381    50    13]
 [   15    53  2436    73]
 [    7     4    11   270]]
              precision    recall  f1-score   support

           0       0.99      0.77      0.87     34134
           1       0.36      0.83      0.50      1654
           2       0.68      0.95      0.79      2577
           3       0.06      0.92      0.11       292

   micro avg       0.78      0.78      0.78     38657
   macro avg       0.52      0.87      0.57     38657
weighted avg       0.94      0.78      0.84     38657

[0.4383588429181813, 2.812162207099102, 0.5706996973464784]


array([0.01224338, 0.00262943, 0.00156042, 0.0026396 , 0.00252463,
       0.0038379 , 0.00431359, 0.00502345, 0.00747251, 0.00748938,
       0.00539596, 0.00935091, 0.00251766, 0.00542588, 0.00263724,
       0.00438373, 0.00066302, 0.00087843, 0.00056888, 0.00062152,
       0.0008627 , 0.00065381, 0.00055323, 0.00032957, 0.00039459,
       0.0005349 , 0.00551031, 0.00042176, 0.0007129 , 0.00334684,
       0.0019257 , 0.00081275, 0.00112662, 0.00084212, 0.00069075,
       0.00075486, 0.00061316, 0.00056535, 0.00068565, 0.00081098,
       0.00314891, 0.00050349, 0.00255472, 0.00514555, 0.00160234,
       0.00131449, 0.00105005, 0.00051623, 0.00083934, 0.00114121,
       0.00076764, 0.00085289, 0.00112406, 0.00226696, 0.00426258,
       0.00138857, 0.00082762, 0.00055925, 0.00051742, 0.00041184,
       0.00041901, 0.00036265, 0.00071274, 0.00067027, 0.00044498,
       0.00044325, 0.00046753, 0.0004081 , 0.000805  , 0.00020019,
       0.00043018, 0.00106789, 0.00248378, 0.00265278, 0.00189

In [46]:
DB1.columns.get_loc('rr_int_pre')

98

In [55]:
y_test_new.shape

(38657,)

In [62]:
feat_labels = ["R_duration", "R_height", "R_amp0", "R_amp1","R_amp2","R_amp3", "R_amp4", "R_amp5", "R_amp6", "R_amp7", "R_amp8", "R_amp9", "R_prominence","R_areas","Q_duration", "Q_height", "Q_amp0", "Q_amp1","Q_amp2","Q_amp3", "Q_amp4", "Q_amp5", "Q_amp6", "Q_amp7", "Q_amp8", "Q_amp9", "Q_prominence","Q_areas", "S_duration", "S_height", "S_amp0", "S_amp1","S_amp2","S_amp3", "S_amp4", "S_amp5", "S_amp6", "S_amp7", "S_amp8", "S_amp9", "S_prominence","S_areas", "P_duration", "P_height", "P_amp0", "P_amp1","P_amp2","P_amp3", "P_amp4", "P_amp5", "P_amp6", "P_amp7", "P_amp8", "P_amp9", "P_prominence","P_areas", "P_neg_duration", "P_neg_height", "P_neg_amp0", "P_neg_amp1","P_neg_amp2","P_neg_amp3", "P_neg_amp4", "P_neg_amp5", "P_neg_amp6", "P_neg_amp7", "P_neg_amp8", "P_neg_amp9", "P_neg_prominence","P_neg_areas", "T_duration", "T_height", "T_amp0", "T_amp1","T_amp2","T_amp3", "T_amp4", "T_amp5", "T_amp6", "T_amp7", "T_amp8", "T_amp9", "T_prominence","T_areas","T_neg_durations","T_neg_height", "T_neg_amp0", "T_neg_amp1", "T_neg_amp2", "T_neg_amp3", "T_neg_amp4", "T_neg_amp5", "T_neg_amp6", "T_neg_amp7", "T_neg_amp8", "T_neg_amp9","T_neg_prominence","T_neg_areas", "rr_int_pre", "rr_int_post", "rr_int_10", "rr_int_50", "rr_int_all", "QRS_int", "QRS_int_10", "QRS_int_50", "PQ_int", "PQ_int_10", "PQ_int_50", "PR_int", "PR_int_10", "PR_int_50", "ST_int", "ST_int_10", "ST_int_50", "RT_int", "RT_int_10", "RT_int_50", "PT_int", "PT_int_10", "PT_int_50", "RP","TR","neg_RQ", "neg_PR", "neg_ST", "neg_RT", "neg_PT", "P_neg_T", "neg_P_neg_T"]
feat_labels_V = ["R_duration_V", "R_height_V", "R_amp0_V", "R_amp1_V","R_amp2_V","R_amp3_V", "R_amp4_V", "R_amp5_V", "R_amp6_V", "R_amp7_V", "R_amp8_V", "R_amp9_V", "R_prominence_V","R_areas_V","Q_duration_V", "Q_height_V", "Q_amp0_V", "Q_amp1_V","Q_amp2_V","Q_amp3_V", "Q_amp4_V", "Q_amp5_V", "Q_amp6_V", "Q_amp7_V", "Q_amp8_V", "Q_amp9_V", "Q_prominence_V","Q_areas_V", "S_duration_V", "S_height_V", "S_amp0_V", "S_amp1_V","S_amp2_V","S_amp3_V", "S_amp4_V", "S_amp5_V", "S_amp6_V", "S_amp7_V", "S_amp8_V", "S_amp9_V", "S_prominence_V","S_areas_V", "P_duration_V", "P_height_V", "P_amp0_V", "P_amp1_V","P_amp2_V","P_amp3_V", "P_amp4_V", "P_amp5_V", "P_amp6_V", "P_amp7_V", "P_amp8_V", "P_amp9_V", "P_prominence_V","P_areas_V", "P_neg_duration_V", "P_neg_height_V", "P_neg_amp0_V", "P_neg_amp1_V","P_neg_amp2_V","P_neg_amp3_V", "P_neg_amp4_V", "P_neg_amp5_V", "P_neg_amp6_V", "P_neg_amp7_V", "P_neg_amp8_V", "P_neg_amp9_V", "P_neg_prominence_V","P_neg_areas_V", "T_duration_V", "T_height_V", "T_amp0_V", "T_amp1_V","T_amp2_V","T_amp3_V", "T_amp4_V", "T_amp5_V", "T_amp6_V", "T_amp7_V", "T_amp8_V", "T_amp9_V", "T_prominence_V","T_areas_V","T_neg_durations_V","T_neg_height_V", "T_neg_amp0_V", "T_neg_amp1_V", "T_neg_amp2_V", "T_neg_amp3_V", "T_neg_amp4_V", "T_neg_amp5_V", "T_neg_amp6_V", "T_neg_amp7_V", "T_neg_amp8_V", "T_neg_amp9_V","T_neg_prominence_V","T_neg_areas_V", "rr_int_pre_V", "rr_int_post_V", "rr_int_10_V", "rr_int_50_V", "rr_int_all_V", "QRS_int_V", "QRS_int_10_V", "QRS_int_50_V", "PQ_int_V", "PQ_int_10_V", "PQ_int_50_V", "PR_int_V", "PR_int_10_V", "PR_int_50_V", "ST_int_V", "ST_int_10_V", "ST_int_50_V", "RT_int_V", "RT_int_10_V", "RT_int_50_V", "PT_int_V", "PT_int_10_V", "PT_int_50_V", "RP_V","TR_V","neg_RQ_V", "neg_PR_V", "neg_ST_V", "neg_RT_V", "neg_PT_V", "P_neg_T_V", "neg_P_neg_T_V"]
feat_labels_dtw = ["dtw1","dtw2"]
norm_dtw = ["dtw1_v1","dtw2_v1"]
classID = ["classID"]
non_clinic = list(DB1_non_cli.iloc[:,0:140].columns.values)

feature_norm_mill = []
for i in range(len(feat_labels)):
    feature_norm_mill.append(str(feat_labels[i]+"_n_MLII"))

feature_norm_V1 = []
for i in range(len(feat_labels)):
    feature_norm_V1.append(str(feat_labels[i]+"_n_V1"))
    

c_ID = np.asarray(classID)
f_M = np.asarray(feat_labels)
f_V = np.asarray(feat_labels_V)
f_d = np.asarray(feat_labels_dtw)
non_cli = np.asarray(non_clinic)
norm_mlii = np.asarray(feature_norm_mill)
norm_v1 = np.asarray(feature_norm_V1)
norm_dtw = np.asarray(norm_dtw)


features_clinic = np.hstack((f_M,f_V, f_d,norm_mlii, norm_v1,norm_dtw ))

#row=[]
#for i in range(0,len(np_clinic_new_1)):
    #row.append(i)
    
features = []
for feature in zip(features_clinic, rf.feature_importances_):
    
    features.append(feature)

In [63]:
columns = ['features', 'rfscore']
import pandas as pd
df = pd.DataFrame(features,columns=columns)


In [67]:
df = df.sort_values(['rfscore', 'features'], ascending=[0,1])
df[df['rfscore'] >= 0.01]['features'].values
df.to_csv('database/features_ranking_with_norm.py')


In [30]:
X_train_df = pd.DataFrame(good_features_X,columns=features_clinic)
X_test_df = pd.DataFrame(X_test,columns=features_clinic)

In [34]:
X_train = pd.DataFrame(X_train,columns=features_clinic)
X_test = pd.DataFrame(X_test,columns=features_clinic)

In [123]:
np.mean(X_test_df[rank['features'].values]['QRS_int_50'])

0.1558750839562633

In [8]:
rank = array(['rr_int_pre_V', 'dtw1', 'rr_int_pre', 'dtw2', 'rr_int_post',
       'R_duration', 'neg_RQ', 'rr_int_post_V', 'R_amp7', 'rr_int_all_V',
       'RP_V', 'rr_int_all', 'R_amp3_V', 'PR_int_V', 'R_amp4_V',
       'PQ_int_V', 'R_amp6', 'R_amp5', 'R_amp9', 'R_amp2_V', 'R_amp4',
       'R_amp1_V', 'Q_prominence', 'Q_height', 'R_areas', 'rr_int_50_V',
       'T_amp9', 'P_height', 'R_amp8', 'R_prominence', 'S_amp0',
       'rr_int_50', 'T_amp2', 'R_amp3', 'QRS_int_50', 'P_prominence',
       'T_amp1', 'R_height', 'PQ_int_50', 'TR', 'R_amp0_V', 'T_amp8',
       'S_prominence', 'R_amp5_V', 'RT_int', 'S_amp9_V', 'S_height',
       'T_amp3', 'T_neg_amp0', 'T_amp0', 'neg_RT_V', 'Q_duration',
       'R_duration_V', 'S_amp2', 'T_neg_amp2', 'rr_int_10_V',
       'PQ_int_50_V', 'P_duration_V'], dtype=object)

NameError: name 'array' is not defined

In [109]:
np.mean(train_rr[:,7])

1.0040356294719912